(function(root,factory){const api=factory(typeof module==='object'?require('./engine.js'):root.TuneLabEngine,typeof module==='object'?require('./workbench-engine.js'):root.TuneLabWorkbench);if(typeof module==='object'&&module.exports)module.exports=api;else root.TuneLabSessions=api;})(globalThis,(E,W)=>{
'use strict';
function segments(rows){let out=[],part=[],last=null;for(const r of rows){if(last&&(r.sourceIndex!==last.sourceIndex+1||r.time<=last.time||r.time-last.time>.25||(Number.isFinite(r.gear)&&Number.isFinite(last.gear)&&r.gear!==last.gear))){if(part.length)out.push(part);part=[];}part.push(r);last=r;}if(part.length)out.push(part);return out;}
function filtered(log,opts={}){if(opts.preset&&!['raw','loaded','steady','transient','afm'].includes(opts.preset))throw Error('Unknown filter preset');const mapping=opts.mapping??{time:'time_ms',rpm:'RPM',bp:'BP',cmd:'BP CMD',pedal:'TPedal',gear:'Gear',wg:'WGCMD'},ids=Object.fromEntries(Object.entries(mapping).map(([k,v])=>[k,E.index(log,v)]));if(['time','rpm','bp','cmd'].some(k=>ids[k]<0))throw Error('Map timestamp, RPM, actual boost and command before plotting');if(['loaded','steady','transient'].includes(opts.preset)&&ids.pedal<0)throw Error('This preset requires an accelerator-pedal channel');const lo=opts.minRpm??0,hi=opts.maxRpm??10000,pedalMin=opts.minPedal??80,deltaMax=opts.maxPedalDelta??2;if(![lo,hi,pedalMin,deltaMax].every(Number.isFinite)||lo>hi||pedalMin<0||pedalMin>100||deltaMax<0)throw Error('Check filter thresholds');let eligible=null;if(opts.preset==='afm'){const afm={...E.AFM_DEFAULTS,...opts.afm,channels:{...E.AFM_DEFAULTS.channels,...opts.afm?.channels}};eligible=new Set(E.observations(log,afm).samples.map(x=>x.sourceIndex));}
const convert=x=>Number.isFinite(x)?W.pressure(x,opts.pressure==='psi'?'ktuner':opts.pressure==='kpa'?'kpa':'bar','ktuner',opts.pa??.98):NaN;const rows=[],reasons={},timeFactor=opts.timeUnit==='s'?1:1000;const get=(r,k)=>ids[k]===undefined||ids[k]<0?NaN:r[ids[k]];log.data.forEach((r,j)=>{const v={sourceIndex:j,time:get(r,'time')/timeFactor,rpm:get(r,'rpm'),bp:convert(get(r,'bp')),cmd:convert(get(r,'cmd')),pedal:get(r,'pedal'),gear:get(r,'gear'),wg:get(r,'wg')};let reason=null;if(![v.time,v.rpm,v.bp,v.cmd].every(Number.isFinite))reason='Missing required numeric values';else if(v.rpm<lo||v.rpm>hi)reason='Outside RPM range';else if(opts.preset==='afm'&&!eligible.has(j))reason='AFM eligibility';else if(['loaded','steady','transient'].includes(opts.preset)&&(!Number.isFinite(v.pedal)||v.pedal<pedalMin||v.cmd<=0))reason='Outside loaded acceleration';else if(opts.preset==='steady'){const p=log.data[j-1];const dt=p?v.time-get(p,'time')/timeFactor:NaN;if(!p||!(dt>0&&dt<=.25))reason='Sampling continuity';else if(!Number.isFinite(get(p,'pedal'))||Math.abs(v.pedal-get(p,'pedal'))>deltaMax)reason='Pedal transient';}
if(opts.event&&(v.sourceIndex<opts.event.first||v.sourceIndex>opts.event.last))reason=reason??'Outside selected event';if(reason)reasons[reason]=(reasons[reason]??0)+1;else rows.push(v);});const parts=segments(rows),events=parts.filter(p=>p.length>=2&&p.at(-1).time-p[0].time>=.25).map(p=>({first:p[0].sourceIndex,last:p.at(-1).sourceIndex,start:p[0].time,end:p.at(-1).time,gear:p[0].gear,rpmStart:p[0].rpm,rpmEnd:p.at(-1).rpm}));return{rows,segments:parts,events,accepted:rows.length,rejected:log.data.length-rows.length,reasons};}
function histogram(values,bins=20){const nums=values.filter(Number.isFinite);if(!Number.isInteger(bins)||bins<1||bins>200)throw Error('Histogram bins must be 1–200');if(!nums.length)return[];const min=nums.reduce((a,b)=>Math.min(a,b),Infinity),max=nums.reduce((a,b)=>Math.max(a,b),-Infinity),width=max===min?1:(max-min)/bins,counts=Array(bins).fill(0);nums.forEach(v=>counts[Math.min(bins-1,Math.floor((v-min)/width))]++);return counts.map((count,j)=>({min:min+j*width,max:min+(j+1)*width,count}));}
function regrid(table,rpm,axis,{keepProtected=true}={}){E.validateTable(table);const repeat=table.kind==='mpr';if(!rpm.length||!axis.length||rpm.some((v,j)=>!Number.isFinite(v)||j&&v<=rpm[j-1])||axis.some((v,j)=>!Number.isFinite(v)||j&&(repeat?v<axis[j-1]:v<=axis[j-1])))throw Error('New indices must be ordered; repeated atmospheric endpoints are only supported for MPR');if(keepProtected)for(let r=0;r<table.rpm.length;r++)for(let c=0;c<table.axis.length;c++)if(table.protect?.[r]?.[c]&&(!rpm.includes(table.rpm[r])||!axis.includes(table.axis[c])))throw Error('New grid removes protected coordinates. Retain those breakpoints or explicitly release protection first.');const sameAxis=JSON.stringify(axis)===JSON.stringify(table.axis);if(!sameAxis&&table.axis.some((v,j)=>j&&v===table.axis[j-1]))throw Error('This table has repeated atmospheric indices. Keep the native column axis while regridding RPM; resolve duplicate-column meanings explicitly before replacing it.');const values=rpm.map(y=>{const[rl,rh,rw]=E.bracket(table.rpm,y);return axis.map((x,c)=>{const[cl,ch,cw]=sameAxis?[c,c,0]:E.bracket(table.axis,x);const a=table.values[rl][cl]*(1-cw)+table.values[rl][ch]*cw,b=table.values[rh][cl]*(1-cw)+table.values[rh][ch]*cw;return a*(1-rw)+b*rw;});});const protect=rpm.map(y=>axis.map((x,col)=>{const r=table.rpm.indexOf(y),c=sameAxis?col:table.axis.lastIndexOf(x);return r>=0&&c>=0&&!!table.protect?.[r]?.[c];}));const out={...table,rpm:[...rpm],axis:[...axis],values,protect};E.validateTable(out);return out;}
function changes(before,after){const result=[];if(before.length!==after.length||before.some((r,j)=>r.length!==after[j].length))throw Error('Dimension-changing edits need whole-table restoration');before.forEach((row,r)=>row.forEach((v,c)=>{if(Math.abs(v-after[r][c])>1e-10)result.push({r,c,before:v,after:after[r][c]});}));return result;}
function reverseChanges(current,delta){const out=current.map(r=>[...r]);for(const d of delta){if(out[d.r]?.[d.c]===undefined||Math.abs(out[d.r][d.c]-d.after)>1e-9)throw Error('Later edits overlap this change. Restore a revision or undo later edits first.');out[d.r][d.c]=d.before;}return out;}
return{segments,filtered,histogram,regrid,changes,reverseChanges};
});
