const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('assert');
const dir=require('path').resolve(__dirname,'..');
const vm=require('vm');const dom=new JSDOM(fs.readFileSync(dir+'/index.html','utf8'),{runScripts:'outside-only',url:'http://localhost/'}),w=dom.window;
w.matchMedia=()=>({matches:true,addEventListener(){}});w.confirm=()=>true;w.prompt=()=>null;w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};
for(const file of ['tables.js','engine.js','workbench-engine.js','app.js','workbench.js','session-engine.js','sessions.js'])vm.runInContext(fs.readFileSync(dir+'/'+file,'utf8'),dom.getInternalVMContext());
const $=id=>w.document.getElementById(id),click=id=>$(id).click(),change=(id,value)=>{$(id).value=value;$(id).dispatchEvent(new w.Event('change',{bubbles:true}));},evalx=s=>vm.runInContext(s,dom.getInternalVMContext()),tick=()=>new Promise(r=>setImmediate(r));
(async()=>{
const text='time_ms,RPM,BP,BP CMD,TPedal,Gear,WGCMD\n0,3000,18,20,90,3,30\n100,3100,20,20,90,3,30\n200,3200,22,20,90,3,30\n300,3300,21,20,90,3,30\n400,3400,2,1,10,3,30\n500,3500,20,20,90,3,30\n600,3600,21,20,90,3,30\n700,3700,22,20,90,3,30\n800,3800,23,20,90,3,30';
await evalx('importSession('+JSON.stringify(text)+',"Historical synthetic fixture.csv")');await tick();
assert.equal(evalx('sessions.length'),1);assert.ok($('logChart').querySelector('#inspectionCursor'));assert.equal(evalx('reviewRows.length'),4);
$('frameSlider').value=2;$('frameSlider').dispatchEvent(new w.Event('input',{bubbles:true}));assert.ok($('frameReadout').textContent.includes('error 2.000 PSI'));const cursor=$('logChart').querySelector('#inspectionCursor').getAttribute('x1');$('frameSlider').value=0;$('frameSlider').dispatchEvent(new w.Event('input',{bubbles:true}));assert.notEqual($('logChart').querySelector('#inspectionCursor').getAttribute('x1'),cursor);
await evalx('importSession('+JSON.stringify(text)+',"Duplicate.csv")');assert.equal(evalx('sessions.length'),1);assert.equal(evalx('learning.length'),1);
change('logEvent','all');assert.equal(evalx('reviewRows.length'),8);assert.equal($('logChart').querySelectorAll('polyline').length,4,'two channels in two disjoint segments');
const second=text.replace('18,20,90','19,20,90');const firstId=evalx('activeSession');await evalx('importSession('+JSON.stringify(second)+',"Second synthetic historical session.csv")');change('comparisonSession',firstId);await tick();assert.ok($('logChart').querySelector('[stroke="#d1aaed"]'));assert.equal(evalx('sessions.length'),2);
change('baselineSession',evalx('activeSession'));assert.equal(evalx('baseline===review'),true);assert.equal($('baselineConfirm').checked,false);
click('recordInsight');assert.equal(evalx('learning.length'),3);
evalx('goPage("logs")');click('openHelp');const logHelp=$('helpBody').textContent;evalx('goPage("afm")');click('openHelp');assert.notEqual($('helpBody').textContent,logHelp);assert.ok($('helpBody').querySelector('a'));
evalx('goPage("boost")');click('previewBoost');await tick();const original=evalx('state.mpr.proposal.values[0][0]');$('proposedGrid').querySelector('[data-edit]').click();change('boostOp','add');change('boostEditAmount','.05');w.document.querySelector('[data-apply="boost"]').click();await tick();const entry=evalx('journal.at(-1).id');assert.ok(evalx('entryDelta(journal.at(-1)).length')>0);w.document.querySelector('[data-undo-edit="'+entry+'"]').click();await tick();assert.ok(Math.abs(evalx('state.mpr.proposal.values[0][0]')-original)<1e-10);
change('appearanceScope','page');change('theme','light');assert.equal(evalx('layoutPrefs.pages.boost.theme'),'light');evalx('goPage("logs")');assert.equal($('theme').value,'dark');evalx('goPage("boost")');assert.equal($('theme').value,'light');
const nrows=evalx('state.mpr.source.rpm.length'),rpm=evalx('state.mpr.source.rpm');change('sourceRpm',[rpm[0],(rpm[0]+rpm[1])/2,...rpm.slice(1)].join(','));click('regridSource');assert.equal($('applyRegrid').hidden,false);click('applyRegrid');await tick();assert.equal(evalx('state.mpr.source.rpm.length'),nrows+1);click('restoreImport');await tick();assert.equal(evalx('state.mpr.source.rpm.length'),nrows);
const project=evalx('serialize()');assert.equal(project.sessionLibrary.sessions.length,2);evalx('loadProject('+JSON.stringify(project)+')');await tick();assert.equal(evalx('sessions.length'),2);assert.equal($('baselineConfirm').checked,false);assert.ok(evalx('journal.length')>=2);
if(process.env.TUNELAB_LOG_FIXTURE){const raw=fs.readFileSync(process.env.TUNELAB_LOG_FIXTURE,'utf8');await evalx('importSession('+JSON.stringify(raw)+',"Earlier Hondata compatibility log.csv")');await tick();assert.equal(evalx('sessions.length'),3);assert.ok(evalx('review.data.length')>20000);assert.ok($('logChart').querySelector('svg'));}
const ids=[...w.document.querySelectorAll('[id]')].map(x=>x.id);assert.equal(new Set(ids).size,ids.length,'runtime IDs are unique');assert.ok(!$('status').classList.contains('error'),$('status').textContent);console.log('Session DOM integration PASS: filters, linked cursor, duplicate detection, roles, contextual sources, selective undo, page themes, raw-log save/reopen, optional historical log');
})().catch(e=>{console.error(e);process.exitCode=1;});
