// chrome.tabs.setZoom applies actual browser zoom in a disposable profile.
// A tiny local test extension is loaded only in that profile; no user browser
// settings or installed extensions are changed.
const {chromium}=require(process.env.TUNELAB_PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{pathToFileURL}=require('node:url');
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'tunelab-v9-')),out=process.env.TUNELAB_BROWSER_OUTPUT||scratch,ext=path.join(scratch,'zoom-extension');fs.mkdirSync(ext,{recursive:true});fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(ext,'manifest.json'),JSON.stringify({manifest_version:3,name:'TuneLab disposable zoom test',version:'1.0',permissions:['tabs'],background:{service_worker:'worker.js'}}));fs.writeFileSync(path.join(ext,'worker.js'),'chrome.runtime.onInstalled.addListener(()=>{});');
(async()=>{const context=await chromium.launchPersistentContext(path.join(scratch,'profile'),{...(process.env.TUNELAB_BROWSER_EXECUTABLE?{executablePath:process.env.TUNELAB_BROWSER_EXECUTABLE}:process.platform==='win32'?{executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}:{}),headless:true,args:['--disable-extensions-except='+ext,'--load-extension='+ext],viewport:{width:2200,height:1000},acceptDownloads:true});try{
 const errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));const page=await context.newPage(),url=pathToFileURL(path.resolve(__dirname,'../index.html')).href;await page.goto(url);await page.waitForSelector('#toggleNavigation');const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker'),id=await worker.evaluate(async url=>(await chrome.tabs.query({})).find(t=>t.url===url).id,url);
 async function zoom(factor){await worker.evaluate(async({id,factor})=>{await chrome.tabs.setZoom(id,factor);}, {id,factor});await page.waitForFunction(({width,factor})=>Math.abs(innerWidth-width/factor)<2,{width:(await page.viewportSize()).width,factor});assert.ok(Math.abs(await worker.evaluate(id=>chrome.tabs.getZoom(id),id)-factor)<1e-9);}
 async function checkWidths(name){const size=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(size.scroll<=size.width+2,`${name}: page overflow ${size.scroll}/${size.width}`);}
 const matrix=[];for(const viewport of [{width:2200,height:1000},{width:2200,height:600},{width:900,height:900}]){await page.setViewportSize(viewport);for(const factor of [1,1.25,1.5,1.75,2]){await zoom(factor);for(const tab of ['boost','afm','logs','gears','changes','project','library','history','compare','settings','strategy']){await page.evaluate(tab=>goPage(tab),tab);await checkWidths(`${viewport.width}x${viewport.height} ${factor*100}% ${tab}`);}
  const visible=await page.locator('aside').isVisible();if(visible){const state=await page.locator('aside').evaluate(n=>({overflow:getComputedStyle(n).overflowY,height:n.clientHeight,scroll:n.scrollHeight}));assert.equal(state.overflow,'auto');if(state.scroll>state.height){const aside=page.locator('aside');await aside.hover();await page.mouse.wheel(0,1600);await page.waitForFunction(()=>document.querySelector('aside').scrollTop>0);const settings=page.locator('nav [data-tab="settings"]');await settings.focus();await page.keyboard.press('Enter');const focus=await page.evaluate(()=>document.activeElement.id);assert.equal(focus,'pageTitle');await page.locator('aside').evaluate(n=>n.scrollTop=n.scrollHeight);assert.ok(await page.locator('#demo').isVisible());}else assert.ok(state.height<=await page.evaluate(()=>innerHeight));}else assert.ok(await page.locator('#workspaceSelect').isVisible());
  matrix.push({viewport,factor,cssViewport:await page.evaluate(()=>({width:innerWidth,height:innerHeight})),sidebarVisible:visible});
 }}
 await page.setViewportSize({width:2200,height:600});await zoom(1.5);await page.evaluate(()=>goPage('boost'));await page.screenshot({path:path.join(out,'v0.9-native-zoom-sidebar.png')});
 await page.locator('#toggleNavigation').click();await page.reload();assert.ok(await page.locator('body').evaluate(n=>n.classList.contains('compact-navigation')));await page.locator('#toggleNavigation').click();await page.reload();assert.ok(!await page.locator('body').evaluate(n=>n.classList.contains('compact-navigation')));
 await page.locator('#previewBoost').click();const before=await page.evaluate(()=>JSON.stringify(state.mpr.proposal.values));await page.locator('#proposedGrid').scrollIntoViewIfNeeded();await page.locator('[data-table-zoom="proposedGrid"]').selectOption('2');assert.equal(await page.evaluate(()=>JSON.stringify(state.mpr.proposal.values)),before);await checkWidths('table zoom at native 150%');
 const card=page.locator('#boost .panel-grid>.panel').first();await card.locator('[data-grid-span]').click();await card.locator('[data-grid-right]').click();await page.setViewportSize({width:900,height:900});await zoom(1.5);await page.waitForFunction(()=>document.querySelector('#boost .panel-grid').dataset.columns==='1');const column=await card.evaluate(n=>getComputedStyle(n).gridColumnStart);assert.equal(column,'1','saved right side must not create an implicit narrow column');
 await page.setViewportSize({width:2200,height:1000});await zoom(1);await page.waitForFunction(()=>document.querySelector('#boost .panel-grid').dataset.columns==='2');assert.equal(await card.evaluate(n=>getComputedStyle(n).gridColumnStart),'2');await card.locator('[data-grid-left]').click();const next=page.locator('#boost .panel-grid>.panel').nth(1);await next.locator('[data-grid-span]').click();await next.locator('[data-grid-right]').click();await card.evaluate(n=>n.style.height='430px');await next.evaluate(n=>n.style.height='270px');const left=await card.boundingBox(),right=await next.boundingBox();assert.ok(right.x>left.x);assert.ok(Math.abs(right.y-left.y)<2,'mixed-height panels retain side-by-side row');
 await card.locator('[data-max-panel]').click();const expanded=await card.boundingBox();assert.ok(expanded.x<30&&expanded.y<30);assert.ok(expanded.width>(await page.evaluate(()=>innerWidth))*.9,'expanded card uses viewport');await card.locator('[data-collapse-panel]').click();await page.locator('#resetWorkspaceGrid').focus();await page.keyboard.press('Enter');assert.equal(await card.getAttribute('data-span'),'2');assert.ok(!await card.evaluate(n=>n.classList.contains('panel-collapsed')||n.classList.contains('panel-maximized')));assert.equal(await card.evaluate(n=>n.style.height),'');assert.equal(await card.locator('[data-collapse-panel]').innerText(),'Collapse');assert.equal(await card.locator('[data-max-panel]').innerText(),'Expand');
 await page.evaluate(()=>goPage('settings'));const help=page.locator('#settings .help-button').first();await help.focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'closeHelp');await page.keyboard.press('Escape');assert.ok(await help.evaluate(n=>document.activeElement===n));await zoom(2);await page.evaluate(()=>showHelp('Zoom help check','Long help text. '.repeat(300)));const dialog=page.locator('#helpDialog');await checkWidths('help dialog at 200%');const dh=await dialog.boundingBox();assert.ok(dh.height<=await page.evaluate(()=>innerHeight));await page.locator('#closeHelp').click();
 await page.evaluate(()=>goPage('logs'));const [child]=await Promise.all([context.waitForEvent('page'),page.locator('#detachWorkspace').click()]);await child.waitForFunction(()=>document.querySelector('#windowState')?.textContent.includes('Viewing'));assert.equal(await child.locator('.page:visible').count(),1);await child.locator('#editThisWindow').click();await child.waitForFunction(()=>document.querySelector('#windowState')?.textContent.includes('Editing here'));const childId=await worker.evaluate(async url=>(await chrome.tabs.query({})).find(t=>t.url===url).id,child.url());for(const factor of [1,1.25,1.5,1.75,2]){await worker.evaluate(async({id,factor})=>chrome.tabs.setZoom(id,factor),{id:childId,factor});await child.waitForTimeout(100);const dim=await child.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(dim.scroll<=dim.width+2,`detached ${factor*100}% overflow`);}await child.screenshot({path:path.join(out,'v0.9-detached-zoom.png')});await child.close();
 fs.writeFileSync(path.join(out,'v0.9-zoom-matrix.json'),JSON.stringify(matrix,null,2));assert.deepEqual(errors,[]);console.log('v0.9 Edge PASS: 15 native browser-zoom/window combinations across 11 workspaces, sidebar wheel/keyboard reachability, compact preference reopen, independent table zoom, narrow/right snapping and mixed heights, complete reset, viewport expansion, help focus and detached zoom');
 }finally{await context.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
