const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const E=require('../engine.js');require('../tables.js');const T=globalThis.TuneLabTables;
const near=(a,b,tol=1e-9)=>assert.ok(Math.abs(a-b)<=tol,`${a} != ${b}`);
const filter=(rule='Any',min=0,max=10000,width=0)=>({rule,min,max,width});
const options={kind:'command',mode:'Add PSI',amount:1,sourceUnits:'bar',outputUnits:'bar',analysis:'ktuner',pa:.98,offset:0,decimals:3,rpmFilter:filter('At or above',3000),axisFilter:filter('At or above',15.8)};
const table={name:'test',rpm:[2500,3000,4500,5500],axis:[-5,10,15.8,22.8],values:[[.7,1.4,2,2.4],[.8,1.5,2.1,2.5],[.9,1.6,2.2,2.6],[1,1.7,2.3,2.7]]};
test('Excel-style rounding, KTuner conversion and inverse',()=>{near(E.round(-.15,1),-.2);near(E.psi(2.599),22.9994762);near(E.toBar(E.psi(2.599),'psi'),2.599);near(E.psi(1,'pa',.98),.290076);});
test('4500 threshold with 2500 blend starts at 2000 and matches smoothstep',()=>{const f=filter('At or above',4500,7000,2500);near(E.weight(2000,f),0);near(E.weight(3000,f),.352);near(E.weight(3500,f),.648);near(E.weight(4000,f),.896);near(E.weight(4500,f),1);});
test('All index rules select correct core peaks and preserve excluded / zero-weight cells',()=>{
 for(const rule of ['Any','At or above','At or below','Between']){const o={...options,axisFilter:filter(rule,15.8,22.8)},result=E.adjust(table,o);const selected=table.values.slice(1).flatMap(r=>r.filter((_,k)=>E.distance(table.axis[k],o.axisFilter)===0).map(v=>E.psi(v)));near(result.selectedPeak,Math.max(...selected));result.values.forEach((row,j)=>row.forEach((v,k)=>{const selected=j>0&&E.distance(table.axis[k],o.axisFilter)===0;if(selected)near(E.psi(v),E.psi(table.values[j][k])+1,.0073);else assert.equal(v,table.values[j][k]);}));}
});
test('Negative selected peak remains negative; empty selection is an explicit error',()=>{const o={...options,axisFilter:filter('At or below',-5)};assert.ok(E.adjust(table,o).selectedPeak<0);assert.throws(()=>E.adjust(table,{...o,axisFilter:filter('At or above',100)}),/No cells selected/);});
test('Zero adjustment preserves every source value exactly, and protection wins over weights',()=>{assert.deepEqual(E.adjust(table,{...options,amount:0}).values,table.values);const p=structuredClone(table);p.protect=p.values.map(r=>r.map(()=>true));assert.deepEqual(E.adjust(p,options).values,p.values);});
test('Reference-PA MPR peak matches target within export quantization',()=>{const r=E.adjust(T.mpr,{...options,kind:'mpr',mode:'Scale to peak',amount:23,rpmFilter:filter('At or above',4500,7000,2500),axisFilter:filter()});near(r.proposedPeak,23,.008);assert.ok(r.changed>0);assert.throws(()=>E.adjust(T.mpr,{...options,kind:'mpr',axisFilter:filter('At or below',.6)}),/brackets are excluded/);});
test('Repeated MPR PA endpoints use last exact column, matching workbook MATCH',()=>{assert.deepEqual(E.bracket(T.mpr.axis,1),[15,15,0]);const r=E.adjust(T.mpr,{...options,kind:'mpr',mode:'Scale to peak',amount:23,pa:1,axisFilter:filter()});near(r.proposedPeak,23,.008);});
test('PSI source and Absolute-bar source produce equivalent physical proposals',()=>{const psiTable={...table,values:table.values.map(r=>r.map(v=>E.psi(v)))};assert.deepEqual(E.adjust(table,options).values,E.adjust(psiTable,{...options,sourceUnits:'psi'}).values);});
function log(trim=4){let rows=['time_ms,AFM Hz,ECT,TPedal,MAP,AFCMD,Trim,Fuel Status,AF,RPM,BP,BP CMD,Gear,WGCMD'];for(let j=0;j<122;j++)rows.push([j*12,5000,185,10,-5,14.7,trim,2,14.7,2500,20,18,3,30].join(','));return E.parseLog(rows.join('\n'));}
const curve=[{hz:0,flow:-452.07},{hz:4900,flow:20},{hz:5000,flow:21.93},{hz:6000,flow:40}];
test('AFM workbook fixture: 121 accepted samples, 4-point baseline, 2% cap → 22.37 g/s',()=>{const a=E.analyzeAfm(curve,log(),log(1),{confirmed:true,validationConfirmed:true});assert.equal(a.baseline.accepted,121);assert.equal(a.cells[2].samples,121);near(a.cells[2].gaussian,4);near(a.cells[2].correction,2);near(a.cells[2].proposed,22.37);near(a.cells[2].trimDelta,-3);assert.equal(a.cells[0].proposed,-452.07);assert.equal(a.cells[3].proposed,40);});
test('Validation never drives correction; confirmation, protection, low support hold source',()=>{const b=log();const a=E.analyzeAfm(curve,b,log(1),{confirmed:true}),v=E.analyzeAfm(curve,b,log(-6),{confirmed:true});assert.deepEqual(a.cells.map(x=>x.proposed),v.cells.map(x=>x.proposed));assert.deepEqual(E.analyzeAfm(curve,b,null).cells.map(x=>x.proposed),curve.map(x=>x.flow));const p=structuredClone(curve);p[2].protect=true;assert.equal(E.analyzeAfm(p,b,null,{confirmed:true}).cells[2].proposed,21.93);assert.equal(E.analyzeAfm(curve,b,null,{confirmed:true,minSamples:200}).cells[2].proposed,21.93);});
test('Missing Fuel Status fails closed; cold / transient / excessive trim samples excluded',()=>{const b=log();const cold=structuredClone(b);cold.data[10][2]=120;cold.data[20][3]=20;cold.data[30][6]=20;const a=E.analyzeAfm(curve,cold,null);assert.equal(a.baseline.reasons.Cold,1);assert.equal(a.baseline.reasons['Pedal transient'],2);assert.equal(a.baseline.reasons['Trim rejected'],1);const missing={...b,headers:b.headers.map(x=>x==='Fuel Status'?'Wrong':x)};assert.throws(()=>E.analyzeAfm(curve,missing,null),/Missing mapped/);});
test('AFM header mapping in a reordered log and Celsius / seconds / fraction units',()=>{const b=log();const f=b.headers.map((_,j)=>b.headers.length-1-j);const r={...b,headers:f.map(j=>b.headers[j]),data:b.data.map(row=>Float64Array.from(f.map(j=>row[j])))};near(E.analyzeAfm(curve,r,null,{confirmed:true}).cells[2].proposed,22.37);const u=log();u.data.forEach(r=>{r[0]/=1000;r[2]=(r[2]-32)*5/9;r[6]/=100;});near(E.analyzeAfm(curve,u,null,{confirmed:true,ectUnit:'C',timeUnit:'s',trimUnit:'fraction'}).cells[2].proposed,22.37);});
test('CSV handles metadata, missing numeric cells, escaped CRLF export and quoted comma',()=>{const text='Export of "example, file"\r\nframe,time_ms,RPM,BP,BP CMD\r\n0,0,3000,20,18\r\n1,12,3100,,19';const a=E.parseLog(text);assert.equal(a.data.length,2);assert.ok(Number.isNaN(a.data[1][3]));assert.equal(E.parseLog(text.replaceAll('\r\n','\\r\\n')).data.length,2);assert.throws(()=>E.parseLog('time_ms,RPM,RPM\n0,1,2'),/Duplicate/);});
test('Table paste: horizontal AFM, optional factory and protection, body-only boost',()=>{assert.deepEqual(E.parseTable(table.values.map(r=>r.join('\t')).join('\n'),table).values,table.values);assert.equal(E.parseAfm('Hz\t4900\t5000\ng/s\t20\t21.93')[1].flow,21.93);assert.equal(E.parseAfm('Hz,g/s,factory,protect\n5000,21.93,22,1')[0].protect,true);assert.throws(()=>E.parseAfm('5000,\n6000,22'),/numeric/);});
test('Two numeric vertical AFM rows are not mistaken for horizontal rows',()=>{const r=E.parseAfm('5000,21.93,22,1\n5100,23,24,0');assert.equal(r[0].protect,true);assert.equal(r[1].hz,5100);assert.equal(r[1].factory,24);});
test('Boost event error uses simultaneous values, not difference of independent maxima',()=>{const b=log();b.data.forEach((r,j)=>{r[3]=95;r[4]=-5;r[10]=j===60?23:20;r[11]=j===61?23:18;});const e=E.logSeries(b).events[0];near(e.peak,23);near(e.cmdAtPeak,18);near(e.peakCommand,23);near(e.overshoot,5);});
if(process.env.TUNELAB_LOG_FIXTURE)test('Private historical CSV compatibility, without applying it to current AFM',()=>{const a=E.parseLog(fs.readFileSync(process.env.TUNELAB_LOG_FIXTURE,'utf8'),'Earlier log');assert.ok(a.data.length>0);assert.ok(E.logSeries(a).rows.length>0);assert.equal(E.analyzeAfm(T.afm,a,null).changed,0);});
