const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm'),path=require('node:path');
const dir=path.resolve(__dirname,'..'),scripts=['tables.js','engine.js','workbench-engine.js','app.js','vehicle-themes.js','workbench.js','session-engine.js','sessions.js','workflow-engine.js','workflows.js','review-engine.js','review.js','demo-engine.js','strategy.js','review-flow-engine.js','review-flow-ui.js','custom-workspace.js','workspaces.js','polish.js','demos.js','review-flow-cleanup.js','logic-summaries.js','performance.js','revision11.js','playback-tracing.js'];
function boot(preference){const dom=new JSDOM(fs.readFileSync(dir+'/index.html','utf8'),{runScripts:'outside-only',url:'http://localhost/',pretendToBeVisual:true}),w=dom.window;w.matchMedia=()=>({matches:true,addEventListener(){}});w.confirm=()=>true;w.prompt=()=>null;w.open=()=>null;w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};if(preference)w.localStorage.setItem('TuneLabNavigationV9',preference);for(const file of scripts)vm.runInContext(fs.readFileSync(dir+'/'+file,'utf8'),dom.getInternalVMContext());return{dom,w,run:s=>vm.runInContext(s,dom.getInternalVMContext()),$:id=>w.document.getElementById(id)};}
(async()=>{const a=boot();let b,c;try{
 a.$('toggleNavigation').click();assert.equal(JSON.parse(a.w.localStorage.getItem('TuneLabNavigationV9')).collapsed,true);b=boot(a.w.localStorage.getItem('TuneLabNavigationV9'));assert.ok(b.w.document.body.classList.contains('compact-navigation'));assert.equal(b.$('toggleNavigation').textContent,'Show menu');b.$('toggleNavigation').click();assert.equal(JSON.parse(b.w.localStorage.getItem('TuneLabNavigationV9')).collapsed,false);c=boot('{"schema":1,"collapsed":"invalid"}');assert.ok(!c.w.document.body.classList.contains('compact-navigation'));
 const grid=a.$('boost').querySelector('.panel-grid'),first=grid.firstElementChild,id=first.dataset.gridId;a.run('goPage("afm")');const other=a.$('afm').querySelector('.panel-grid>.panel');other.style.height='444px';a.run('saveGrid("afm");goPage("boost")');first.querySelector('[data-grid-span]').click();first.querySelector('[data-grid-right]').click();first.querySelector('[data-grid-down]').click();first.style.width='400px';first.style.height='333px';first.classList.add('panel-collapsed','panel-maximized');first.querySelector('[data-collapse-panel]').textContent='Open';first.querySelector('[data-max-panel]').textContent='Restore size';a.run('savePanel(document.querySelector("#boost .panel-grid>.panel[data-grid-id='+id+']"));saveGrid("boost")');
 const otherBefore=a.run('JSON.stringify(panelLayouts.main.afm)');a.run('panelLayouts.detached.boost={order:[],cards:{}}');a.$('resetWorkspaceGrid').click();assert.equal(grid.firstElementChild,first);assert.equal(first.dataset.span,'2');assert.equal(first.dataset.side,'auto');assert.equal(first.style.height,'');assert.equal(first.style.width,'');assert.ok(!first.classList.contains('panel-maximized'));assert.ok(!first.classList.contains('panel-collapsed'));assert.equal(first.querySelector('[data-collapse-panel]').textContent,'Collapse');assert.equal(first.querySelector('[data-max-panel]').textContent,'Expand');assert.equal(other.style.height,'444px');assert.equal(a.run('JSON.stringify(panelLayouts.main.afm)'),otherBefore);assert.equal(a.run('panelLayouts.detached.boost.order.length'),0);assert.equal(a.run('layoutPrefs.panels['+JSON.stringify(first.dataset.panelId)+']'),undefined);
 a.$('workspaceSelect').value='logs';a.$('workspaceSelect').dispatchEvent(new a.w.Event('change'));assert.equal(a.w.document.activeElement,a.$('pageTitle'));assert.equal(a.w.document.querySelector('nav [aria-current="page"]').dataset.tab,'logs');a.run('goPage("boost")');const help=a.w.document.querySelector('#boost .help-button');help.focus();help.click();assert.equal(a.w.document.activeElement,a.$('closeHelp'));a.$('closeHelp').click();assert.equal(a.w.document.activeElement,help);
 const saved=a.run('serialize()');assert.equal(saved.version,10);const old=structuredClone(saved);old.version=8;a.run('loadProject('+JSON.stringify(old)+')');assert.equal(a.run('serialize().version'),10);assert.match(a.$('backupReport').textContent,/v0.8/);assert.ok(a.w.document.body.classList.contains('compact-navigation'),'opening a project must not replace local navigation preference');
 console.log('v0.9 DOM PASS: remembered/invalid navigation preference, complete scoped reset including legacy cache, independent layouts, focus/ARIA/help return and v0.8 migration');
 }catch(e){console.error(e);process.exitCode=1;}finally{await new Promise(r=>setImmediate(r));a.w.close();b?.w.close();c?.w.close();}})();
