const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm'),path=require('node:path');
const dir=path.resolve(__dirname,'..'),dom=new JSDOM(fs.readFileSync(dir+'/index.html','utf8'),{runScripts:'outside-only',url:'http://localhost/',pretendToBeVisual:true}),w=dom.window;
w.matchMedia=()=>({matches:true,addEventListener(){}});w.confirm=()=>true;w.prompt=()=>null;w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.open=()=>null;
for(const file of ['tables.js','engine.js','workbench-engine.js','app.js','vehicle-themes.js','workbench.js','session-engine.js','navigation14.js','sessions.js','workflow-engine.js','workflows.js','review-engine.js','review.js','demo-engine.js','strategy.js','review-flow-engine.js','review-flow-ui.js','custom-workspace.js','workspaces.js','polish.js','demos.js','review-flow-cleanup.js','logic-summaries.js','performance.js','revision11.js','playback-tracing.js','visit-engine.js','revision12.js','hondata-layout12.js','ktuner-layout12.js','revision13.js','revision14.js','revision15.js','tutorial15.js','transfer15.js','hondata-default12.js'])vm.runInContext(fs.readFileSync(dir+'/'+file,'utf8'),dom.getInternalVMContext());
const run=s=>vm.runInContext(s,dom.getInternalVMContext()),$=id=>w.document.getElementById(id),tick=()=>new Promise(r=>setImmediate(r)),change=(id,value)=>{$(id).value=value;$(id).dispatchEvent(new w.Event('change',{bubbles:true}));};
(async()=>{try{
 const card=$('boost').querySelector('.panel-grid>.panel');card.querySelector('[data-grid-span]').click();card.querySelector('[data-grid-right]').click();assert.equal(card.dataset.side,'right');card.querySelector('.panel-handle').dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowLeft',altKey:true,bubbles:true}));assert.equal(card.dataset.side,'left');const sided=run('serialize()');assert.equal(sided.panelLayouts.main.boost.cards[card.dataset.gridId].side,'left');run('loadProject('+JSON.stringify(sided)+')');assert.equal(card.dataset.side,'left');const invalid=structuredClone(sided);invalid.panelLayouts.main.boost.cards[card.dataset.gridId].side='outside';assert.throws(()=>run('loadProject('+JSON.stringify(invalid)+')'),/panel size/);$('resetWorkspaceGrid').click();assert.equal(card.dataset.span,'2');assert.equal(card.dataset.side,'auto');
 $('previewBoost').click();await tick();assert.ok($('sourceGrid').querySelector('.value-shaded'));const range=run('JSON.stringify(visualReview.scales["boost-mpr"].ranges.values)');run('selection={target:"boost",a:[0,0],b:[0,0]};paintSelection()');change('boostOp','add');change('boostEditAmount','100');w.document.querySelector('[data-apply="boost"]').click();await tick();assert.equal(run('JSON.stringify(visualReview.scales["boost-mpr"].ranges.values)'),range);assert.match($('proposedGridShadingLegend').textContent,/1 clipped/);assert.ok($('proposedGrid').querySelector('.selected.value-shaded'));
 change('tableShading','absolute');await tick();const dr=run('visualReview.scales["boost-mpr"].ranges.absolute');assert.equal(dr[0],-dr[1]);change('tableShading','none');await tick();assert.equal($('sourceGrid').querySelectorAll('.value-shaded').length,0);$('resetShading').click();change('tableShading','values');await tick();assert.notEqual(run('JSON.stringify(visualReview.scales["boost-mpr"].ranges.values)'),range);
 const text='time_ms,RPM,BP,BP CMD,TPedal,Gear,WGCMD\n0,3000,18,20,90,3,30\n100,3100,20,20,90,3,30\n200,3200,22,20,90,3,30\n300,3300,21,20,90,3,30';await run('importSession('+JSON.stringify(text)+',"Synthetic review.csv")');await tick();assert.equal(run('reviewRows.length'),4);assert.equal($('logFormatDetails').open,false);assert.match($('logFormatSummary').textContent,/Mapping needs review/);assert.ok($('logFormatHelp').textContent.includes('Provenance'));assert.ok($('profileMapping').querySelector('[data-profile-map="hz"]').getAttribute('aria-describedby'));change('evidenceStart','0.1');change('evidenceEnd','0.2');$('applyEvidenceRange').click();await tick();assert.equal(run('filteredEvidenceRows().length'),2);assert.equal(run('reviewRows.length'),4,'evidence filtering must not alter eligibility');assert.ok($('logChart').querySelector('.evidence-points'));$('resetEvidenceRange').click();assert.equal(run('filteredEvidenceRows().length'),4);
 const bins=run('S.histogram(reviewRows.map(x=>x.bp-x.cmd),20)'),nonempty=bins.findIndex(x=>x.count>0);$('errorHistogram').querySelector('[data-bin="'+nonempty+'"]').onclick();assert.equal(run('evidenceBin.indices.length'),bins[nonempty].count);$('resetEvidenceRange').click();
 run('selection={target:"boost",a:[0,0],b:[1,1]};paintSelection()');assert.match($('boostEvidenceSummary').textContent,/table rectangle selected/);w.document.querySelector('[data-evidence-clear]').click();assert.equal(run('evidenceSelection'),null);
 run('goPage("changes")');$('markRevisionReviewed').click();assert.match($('reviewRevisionStatus').textContent,/Reviewed/);assert.ok($('changeSummary').textContent.includes('protected/nonpositive'));run('state.mpr.proposal.values[0][1]+=.01;renderBoost();renderChanges()');assert.match($('reviewRevisionStatus').textContent,/Changes since/);
 const backup=run('serialize()');assert.equal(backup.version,10);assert.equal(backup.visualReview.mode,'values');const old=structuredClone(backup);old.version=7;delete old.visualReview;delete old.reviewAcknowledgement;run('loadProject('+JSON.stringify(old)+')');assert.equal(run('visualReview.mode'),'values');assert.equal(run('evidenceRange'),null);
 const before=run('JSON.stringify(state)'),bad=structuredClone(backup);bad.visualReview.mode='invalid';assert.throws(()=>run('loadProject('+JSON.stringify(bad)+')'),/visual review/);assert.equal(run('JSON.stringify(state)'),before);run('loadProject('+JSON.stringify(backup)+')');assert.equal(run('reviewAcknowledgement.date'),backup.reviewAcknowledgement.date);
 $('afmManual').click();await tick();assert.equal($('afmPreview').querySelectorAll('tr').length,3);assert.match($('afmEvidenceContext').textContent,/Manual proposal/);assert.match(run('detailedReview().find(x=>x.name==="AFM / MAF").data'),/missing or stale/);
 run('loadSyntheticGear()');await tick();assert.ok($('gearOriginalGrid').querySelector('.value-shaded'));assert.match($('gearsEvidenceSummary').textContent,/linked samples/);
 const ids=[...w.document.querySelectorAll('[id]')].map(n=>n.id);assert.equal(new Set(ids).size,ids.length);console.log('v0.8 DOM PASS: stable/shared shading, clipping/reset/no-shading, range/bin/rectangle evidence, unchanged calculations, review invalidation, v0.7 migration and malformed backup preservation');
 }catch(e){console.error(e);process.exitCode=1;}finally{await tick();w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});


