'use strict';
const E=TuneLabEngine,$=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x)),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(x,n=2)=>Number.isFinite(x)?x.toFixed(n):'—';
let kind='mpr',baseline=null,validation=null,review=null,reviewRows=[],isDemo=false,afmResult=null;
const boostIds=['boostMode','boostAmount','sourceUnits','outputUnits','analysisMode','referencePa','offset','boostPrecision','rpmRule','rpmMin','rpmMax','rpmWidth','axisRule','axisMin','axisMax','axisWidth'];
const defaults={boostMode:'Scale to peak',boostAmount:23,sourceUnits:'bar',outputUnits:'bar',analysisMode:'ktuner',referencePa:.98,offset:0,boostPrecision:3,rpmRule:'At or above',rpmMin:4500,rpmMax:7000,rpmWidth:2500,axisRule:'Any',axisMin:.955,axisMax:1,axisWidth:0};
let state={mpr:{source:clone(TuneLabTables.mpr),controls:clone(defaults),proposal:null,dirty:true},command:{source:clone(TuneLabTables.command),controls:{...defaults,boostMode:'Add PSI',boostAmount:0,rpmMin:3000,rpmWidth:750,axisRule:'At or above',axisMin:15.8,axisMax:28.8,axisWidth:3},proposal:null,dirty:true},afm:clone(TuneLabTables.afm),snapshots:[]};
function message(text,type=''){const n=$('status');n.textContent=text;n.className='status'+(type?' '+type:'');}
function action(fn){return async(...args)=>{try{await fn(...args);}catch(e){message(e.message,'error');console.error(e);}};}
function setDemo(v){isDemo=v;$('demoBadge').hidden=!v;}
function controls(){return Object.fromEntries(boostIds.map(id=>[id,$(id).value]));}
function syncControls(){state[kind].controls=controls();}
function boostOptions(){const v=controls();return{kind,mode:v.boostMode,amount:+v.boostAmount,sourceUnits:v.sourceUnits,outputUnits:v.outputUnits,analysis:v.analysisMode,pa:+v.referencePa,offset:+v.offset,decimals:+v.boostPrecision,rpmFilter:{rule:v.rpmRule,min:+v.rpmMin,max:+v.rpmMax,width:+v.rpmWidth},axisFilter:{rule:v.axisRule,min:+v.axisMin,max:+v.axisMax,width:+v.axisWidth}};}
function switchKind(k,skipSync=false){if(!skipSync)syncControls();kind=k;for(const id of boostIds)$(id).value=state[k].controls[id];document.querySelectorAll('[data-kind]').forEach(b=>b.classList.toggle('active',b.dataset.kind===k));$('boostAxisLabel').textContent=k==='mpr'?'PA axis · bar':'Command index · displayed PSI';$('axisRuleLabel').firstChild.textContent=k==='mpr'?'PA selection':'Command-index selection';renderBoost();}
function metrics(id,items){$(id).innerHTML=items.map(([label,value,sub])=>`<div class="metric"><label>${esc(label)}</label><strong>${esc(value)}</strong><small>${esc(sub??'')}</small></div>`).join('');}
function tableGrid(id,t,source=false,base=null){
 const hd='<tr><th>RPM / index</th>'+t.axis.map(x=>`<th>${fmt(x,kind==='mpr'?3:1)}</th>`).join('')+'</tr>';
 const rows=t.values.map((row,j)=>'<tr><td>'+fmt(t.rpm[j],0)+'</td>'+row.map((v,k)=>{const lock=t.protect?.[j]?.[k],diff=base&&Math.abs(v-base.values[j][k])>1e-9;return`<td class="${source?'editable ':''}${lock?'locked ':''}${diff?'changed':''}" ${source?`data-r="${j}" data-c="${k}" tabindex="0" title="Click or press Enter to protect / unprotect"`:''}>${lock?'× ':''}${fmt(v,source?3:+$('boostPrecision').value)}</td>`;}).join('')+'</tr>').join('');$(id).innerHTML=`<table><thead>${hd}</thead><tbody>${rows}</tbody></table>`;
}
function chart(id,series,xLabel='Hz',yLabel='',height=210){
 const node=$(id),valid=series.flatMap(s=>s.points.filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1])));
 if(!valid.length){node.innerHTML='<div class="chart-empty">No supported data yet</div>';return;}
 let xmin=Infinity,xmax=-Infinity,ymin=Infinity,ymax=-Infinity;valid.forEach(([x,y])=>{xmin=Math.min(xmin,x);xmax=Math.max(xmax,x);ymin=Math.min(ymin,y);ymax=Math.max(ymax,y);});if(xmin===xmax)xmax=xmin+1;if(ymin===ymax){ymin-=1;ymax+=1;}const pad=(ymax-ymin)*.09;ymin-=pad;ymax+=pad;
 const W=900,H=height,L=54,R=18,T=15,B=35,X=x=>L+(x-xmin)/(xmax-xmin)*(W-L-R),Y=y=>H-B-(y-ymin)/(ymax-ymin)*(H-T-B);
 let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(yLabel+' by '+xLabel)}"><rect width="${W}" height="${H}" fill="var(--surface)"/>`;
 for(let j=0;j<=4;j++){const y=ymin+(ymax-ymin)*j/4,x=xmin+(xmax-xmin)*j/4;svg+=`<line x1="${L}" x2="${W-R}" y1="${Y(y)}" y2="${Y(y)}" stroke="#e4eaee"/><text x="${L-9}" y="${Y(y)+4}" text-anchor="end" font-size="10" fill="#89959e">${fmt(y,1)}</text><text x="${X(x)}" y="${H-12}" text-anchor="middle" font-size="10" fill="#89959e">${fmt(x,xLabel==='seconds'?1:0)}</text>`;}
 series.forEach(s=>{const points=s.points.filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1]));const step=Math.max(1,Math.ceil(points.length/1500)),sample=points.filter((_,j)=>j%step===0||j===points.length-1);svg+=`<polyline fill="none" stroke="${s.color}" stroke-width="2" points="${sample.map(([x,y])=>`${X(x)},${Y(y)}`).join(' ')}"/>`;});svg+='</svg>';
 node.innerHTML=svg+`<div class="legend">${series.map(s=>`<span><i style="background:${s.color}"></i>${esc(s.name)}</span>`).join('')}</div>`;
 const tooltip=document.createElement('div');tooltip.className='chart-tooltip';tooltip.hidden=true;node.append(tooltip);
 node.querySelector('svg').addEventListener('mousemove',e=>{const r=e.currentTarget.getBoundingClientRect(),v=xmin+((e.clientX-r.left)/r.width*W-L)/(W-L-R)*(xmax-xmin);const lines=[];series.forEach(s=>{let best=null,d=Infinity;for(const p of s.points){if(Number.isFinite(p[1])&&Math.abs(p[0]-v)<d){best=p;d=Math.abs(p[0]-v);}}if(best)lines.push(`${s.name}: ${fmt(best[1],2)} @ ${fmt(best[0],xLabel==='seconds'?3:0)}`);});tooltip.textContent=lines.join('\n');tooltip.hidden=false;tooltip.style.left=Math.min(Math.max(5,e.clientX-r.left+12),Math.max(5,r.width-240))+'px';tooltip.style.top='20px';});node.querySelector('svg').addEventListener('mouseleave',()=>tooltip.hidden=true);
}
function ramp(){const o=boostOptions(),points=Array.from({length:81},(_,j)=>[j*100,E.weight(j*100,o.rpmFilter)*100]);chart('rampChart',[{name:'RPM adjustment weight · %',color:'#ac623c',points}],'RPM','Adjustment %');let start=o.rpmFilter.rule==='At or above'?o.rpmFilter.min-o.rpmFilter.width:null;$('rpmHint').textContent=start!==null?`Blend starts at ${start.toLocaleString()} RPM and reaches full RPM weight at ${o.rpmFilter.min.toLocaleString()} RPM.`:'The smooth transition extends outside the selected core by the blend width.';}
function renderBoost(){
 const b=state[kind],p=b.proposal;ramp();tableGrid('sourceGrid',b.source,true);if(p)tableGrid('proposedGrid',p,false,b.source);else $('proposedGrid').innerHTML='<p class="hint" style="padding:16px">Calculate a proposal to inspect output.</p>';
 metrics('boostMetrics',[['Source core peak',p?fmt(p.selectedPeak,2)+' PSI':'—','MPR at reference PA'],['Proposed core peak',p?fmt(p.proposedPeak,2)+' PSI':'—',b.dirty?'Stale / not calculated':'Calculated proposal'],['Cells changed',p?String(p.changed):'0','Source stays unchanged'],['Axis reversals',p?String(p.reversals):'—','Review curve before export']]);
 $('proposalState').textContent=b.dirty?'Recalculate before export':`${p?.changed??0} changed · ${$('outputUnits').selectedOptions[0].text}`;$('copyBoost').disabled=$('downloadBoost').disabled=b.dirty||!p;
 const o=boostOptions();function curve(t,units){return t.values.map((r,j)=>{let vals=r.map(x=>E.psi(E.toBar(x,units,o.offset,o.pa),o.analysis,o.pa,o.offset));if(kind==='mpr'){if(o.pa<t.axis[0]||o.pa>t.axis.at(-1))return[t.rpm[j],null];const[lo,hi,m]=E.bracket(t.axis,o.pa);return[t.rpm[j],vals[lo]*(1-m)+vals[hi]*m];}return[t.rpm[j],Math.max(...vals.filter((_,k)=>E.distance(t.axis[k],o.axisFilter)===0))];});}
 chart('boostChart',[{name:'Source',color:'#6e8290',points:curve(b.source,o.sourceUnits)},...(p?[{name:'Proposed',color:'#ac623c',points:curve(p,o.outputUnits)}]:[])],'RPM','PSI');
}
function calculateBoost(){if(state[kind].proposal?.manual&&!confirm('Recalculate and replace manual refinements in this proposal?'))return;if(typeof checkpoint==='function')checkpoint();syncControls();const b=state[kind];b.proposal=E.adjust(b.source,boostOptions());b.dirty=false;renderBoost();message(`${b.source.name}: ${b.proposal.changed} cells changed. Proposed selected peak ${fmt(b.proposal.proposedPeak,2)} PSI. Review before export.`);}
const filterConfig=[['minEct','Minimum ECT · °F',170],['minPedal','Minimum pedal · %',2],['minCmd','Minimum commanded AFR',14],['maxCmd','Maximum commanded AFR',15.2],['observationCap','Observation cap · ±points',7],['rejectTrim','Reject trim above · ±points',15],['pedalDelta','Maximum pedal delta',1],['mapDelta','Maximum MAP delta · native units',.5],['cmdDelta','Maximum command-AFR delta',.15],['maxGap','Maximum sample gap · ms',250]];
$('filterFields').innerHTML=filterConfig.map(([id,label,value])=>`<label>${label}<input id="filter_${id}" type="number" step="any" value="${value}"></label>`).join('');
const afmMapping={time:'time_ms',hz:'AFM Hz',ect:'ECT',pedal:'TPedal',map:'MAP',cmd:'AFCMD',trim:'Trim',fuel:'Fuel Status',af:'AF',rpm:'RPM'},logMapping={time:'time_ms',rpm:'RPM',bp:'BP',cmd:'BP CMD',gear:'Gear',wg:'WGCMD',pedal:'TPedal'};
function mappingFields(id,prefix,m){$(id).innerHTML=Object.entries(m).map(([k,v])=>`<label>${esc(k)}<input id="${prefix}${k}" value="${esc(v)}"></label>`).join('');}mappingFields('afmMapping','map_',afmMapping);mappingFields('logMapping','logmap_',logMapping);
function afmOptions(){return{...Object.fromEntries(filterConfig.map(([id])=>[id,+$('filter_'+id).value])),bandwidth:+$('afmBandwidth').value,strength:+$('afmStrength').value/100,minSamples:+$('afmSamples').value,cap:+$('afmCap').value,radius:+$('afmRadius').value,precision:+$('afmPrecision').value,minHz:+$('afmMinHz').value,maxHz:+$('afmMaxHz').value,ectUnit:$('ectUnit').value,timeUnit:$('timeUnit').value,trimUnit:$('trimUnit').value,confirmed:$('baselineConfirm').checked,validationConfirmed:$('validationConfirm').checked,channels:Object.fromEntries(Object.keys(afmMapping).map(k=>[k,$('map_'+k).value]))};}
let afmDirty=false;
function markAfmDirty(){afmDirty=true;$('copyAfm').disabled=$('downloadAfm').disabled=true;message('AFM controls or evidence changed. Analyze again before exporting.','dirty');}
function renderAfm(){
 const a=afmResult??E.analyzeAfm(state.afm,null,null,afmOptions()),cells=a.cells;
 metrics('afmMetrics',[['Baseline accepted',String(a.baseline.accepted),baseline?.name??'No baseline loaded'],['Validation accepted',String(a.validation.accepted),validation?.name??'No validation loaded'],['Flow cells changed',String(a.changed),afmDirty?'Re-analyze before export':'Capped baseline correction'],['Curve reversals',String(a.reversals),'Positive-flow cells only']]);
 chart('afmChart',[{name:'Current',color:'#6e8290',points:cells.filter(x=>x.flow>0).map(x=>[x.hz,x.flow])},{name:'Proposed',color:'#ac623c',points:cells.filter(x=>x.flow>0).map(x=>[x.hz,x.proposed])}],'Hz','g/s');chart('trimChart',[{name:'Baseline',color:'#6e8290',points:cells.map(x=>[x.hz,x.gaussian])},{name:'Validation',color:'#ac623c',points:cells.map(x=>[x.hz,x.validation.gaussian])}],'Hz','Trim points');
 const heads=['Hz','Current g/s','Protect','Baseline n','Mean pts','SD pts','Gaussian pts','Applied %','Proposed g/s','Val n','Val Gaussian','Val − base pts','vs factory %','Slope change','Status'];
 $('afmGrid').innerHTML='<table><thead><tr>'+heads.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+cells.map((x,j)=>`<tr><td>${fmt(x.hz,0)}</td><td>${fmt(x.flow)}</td><td><input type="checkbox" aria-label="Protect ${x.hz} Hz" data-protect-afm="${j}" ${x.protect?'checked':''}></td><td>${x.samples}</td><td>${fmt(x.mean)}</td><td>${fmt(x.sd)}</td><td>${fmt(x.gaussian)}</td><td>${fmt(x.correction)}%</td><td class="${x.reversal?'warn':x.proposed!==x.flow?'changed':''}">${fmt(x.proposed)}</td><td>${x.validation.samples}</td><td>${fmt(x.validation.gaussian)}</td><td>${fmt(x.trimDelta)}</td><td>${fmt(x.factoryDelta===null?null:x.factoryDelta*100)}</td><td>${fmt(x.slopeChange,5)}</td><td class="status-text">${esc(x.reversal?'Reversal · '+x.status:x.status)}</td></tr>`).join('')+'</tbody></table>';
 function evidence(label,o){return`<div><h2>${label}</h2><p>${o.accepted} accepted · ${o.rejected} excluded</p>${Object.entries(o.reasons).map(([k,v])=>`<div>${esc(k)}: <strong>${v}</strong></div>`).join('')}<p>Enriched / high-pedal AFR: ${o.enriched.count} samples<br>Mean deviation: ${fmt(o.enriched.mean===null?null:o.enriched.mean*100)}%<br>Mean absolute deviation: ${fmt(o.enriched.meanAbs===null?null:o.enriched.meanAbs*100)}%<br>Above ±3%: ${o.enriched.outside}</p></div>`;}$('afmReasons').innerHTML=evidence('Baseline',a.baseline)+evidence('Validation',a.validation);
 $('copyAfm').disabled=$('downloadAfm').disabled=afmDirty||!afmResult;
}
function analyze(){if(afmResult?.cells.some(x=>x.manual)&&!confirm('Analyze again and replace manual airflow refinements?'))return;if(typeof checkpoint==='function')checkpoint();afmResult=E.analyzeAfm(state.afm,baseline,validation,afmOptions());afmDirty=false;renderAfm();message(`AFM analysis: ${afmResult.baseline.accepted.toLocaleString()} accepted baseline samples; ${afmResult.changed} cells changed. Validation never drives the proposal.`);}
async function loadCsv(input,phase){const file=input.files[0];if(!file)return;message('Reading '+file.name+'…');const log=E.parseLog(await file.text(),file.name);if(phase==='baseline'){baseline=log;$('baselineConfirm').checked=false;}else if(phase==='validation'){validation=log;$('validationConfirm').checked=false;}else{review=log;renderReview();}setDemo([baseline,validation,review].some(x=>x?.synthetic));if(phase!=='review'){afmResult=null;markAfmDirty();renderAfm();}message(`${file.name}: ${log.data.length.toLocaleString()} frames, ${log.headers.length} channels. ${phase==='review'?'Time-aligned review ready.':'Verify mapping and confirm calibration match before analysis.'}`);}
function renderReview(){if(!review){metrics('logMetrics',[['Samples','0','Load CSV'],['Events','—','No log loaded'],['Peak actual','—',''],['Peak command','—','']]);chart('logChart',[]);return;}
 const m=Object.fromEntries(Object.keys(logMapping).map(k=>[k,$('logmap_'+k).value]));const result=E.logSeries(review,m,$('logPressure').value,$('logTime').value),lo=+$('reviewMinRpm').value,hi=+$('reviewMaxRpm').value;if(!Number.isFinite(lo)||!Number.isFinite(hi)||lo>hi)throw Error('Check plotted RPM range');
 reviewRows=result.rows.filter(x=>x.rpm>=lo&&x.rpm<=hi);const max=k=>reviewRows.reduce((v,r)=>Math.max(v,r[k]),-Infinity);
 metrics('logMetrics',[['Mapped samples',reviewRows.length.toLocaleString(),review.name],['High-pedal events',String(result.events.length),'Whole-log events; chart uses RPM range'],['Peak actual',fmt(max('bp'))+' PSI','Within plotted RPM range'],['Peak command',fmt(max('cmd'))+' PSI','Independent maximum; inspect same timestamp']]);
 chart('logChart',[{name:'Actual boost',color:'#ac623c',points:reviewRows.map(x=>[x.time,x.bp])},{name:'Boost command',color:'#6e8290',points:reviewRows.map(x=>[x.time,x.cmd])}],'seconds','PSI',350);
 $('frameSlider').max=Math.max(0,reviewRows.length-1);$('frameSlider').value=0;inspectFrame();
 const heads=['Start s','End s','Gear','RPM span','Peak BP','CMD at peak BP','Max CMD','Max BP − CMD','Min WGCMD'];$('eventsGrid').innerHTML='<table><thead><tr>'+heads.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+result.events.map(e=>`<tr>${[fmt(e.start),fmt(e.end),fmt(e.gear,0),`${fmt(e.startRpm,0)}–${fmt(e.endRpm,0)}`,fmt(e.peak),fmt(e.cmdAtPeak),fmt(e.peakCommand),fmt(e.overshoot),fmt(e.minWg)].map(x=>'<td>'+esc(x)+'</td>').join('')}</tr>`).join('')+'</tbody></table>';
 const essential=['RPM','BP','BP CMD','AFM Hz','Trim','Fuel Status','ECT'];$('logQuality').innerHTML=`<p class="hint">${review.data.length.toLocaleString()} imported frames · ${review.rejectedRows} malformed-width rows skipped. Missing numeric cells remain missing; they are never replaced with zero.</p><div class="table-scroll"><table><thead><tr><th>Channel</th><th>Numeric rows</th><th>Missing</th><th>Distinct / status</th></tr></thead><tbody>${essential.map(k=>{const ix=E.index(review,k),values=ix<0?[]:review.data.map(r=>r[ix]).filter(Number.isFinite);return`<tr><td>${esc(k)}</td><td>${values.length.toLocaleString()}</td><td>${(review.data.length-values.length).toLocaleString()}</td><td>${ix<0?'Missing header':new Set(values).size===1?'Constant; inspect context':new Set(values).size.toLocaleString()+' distinct'}</td></tr>`;}).join('')}</tbody></table></div>`;
}
function inspectFrame(){const r=reviewRows[+$('frameSlider').value];$('frameReadout').textContent=r?`${fmt(r.time,3)} s | ${fmt(r.rpm,0)} RPM | gear ${fmt(r.gear,0)}\nBP ${fmt(r.bp)} · CMD ${fmt(r.cmd)} · error ${fmt(r.bp-r.cmd)} PSI · WGCMD ${fmt(r.wg,1)}`:'No samples in the plotted range.';}
function download(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function copy(text){try{await navigator.clipboard.writeText(text);message('Proposed table copied.');}catch{const ta=document.createElement('textarea');ta.value=text;document.body.append(ta);ta.select();const ok=document.execCommand('copy');ta.remove();if(!ok)throw Error('Clipboard unavailable. Use Export TSV.');message('Proposed table copied.');}}
function boostText(bodyOnly){const b=state[kind];if(b.dirty||!b.proposal)throw Error('Recalculate the proposal before exporting');return(bodyOnly?b.proposal.values.map(r=>r.map(v=>fmt(v,+$('boostPrecision').value)).join('\t')):[['RPM',...b.proposal.axis].join('\t'),...b.proposal.values.map((r,j)=>[b.proposal.rpm[j],...r.map(v=>fmt(v,+$('boostPrecision').value))].join('\t'))]).join('\r\n');}
function afmText(){if(afmDirty||!afmResult)throw Error('Analyze before exporting');return[afmResult.cells.map(x=>x.hz).join('\t'),afmResult.cells.map(x=>x.proposed).join('\t')].join('\r\n');}
function inputsState(){return Object.fromEntries([...document.querySelectorAll('input[id]:not([type=file]):not([type=range]),select[id],textarea[id]')].filter(n=>!['boostPaste','afmPaste'].includes(n.id)).map(n=>[n.id,n.type==='checkbox'?n.checked:n.value]));}
function serialize(){syncControls();return{format:'TuneLabProject',version:5,savedAt:new Date().toISOString(),state:clone(state),inputs:inputsState(),logs:{baseline:baseline?.name??null,validation:validation?.name??null,review:review?.name??null},syntheticDemo:isDemo,...(typeof WBserialize==='function'?{workbench:WBserialize()}:{} )};}
function renderSnapshots(){$('snapshots').innerHTML=state.snapshots.length?state.snapshots.map((s,j)=>`<div class="snapshot"><div><strong>${esc(s.name)}</strong><small>${esc(s.date)} · ${s.kind.toUpperCase()} / source & proposal</small></div><button class="secondary" data-restore="${j}">Restore</button></div>`).join(''):'<p class="hint">No snapshots saved yet.</p>';}
function loadProject(p){if(typeof WBreset==='function')WBreset();if(p.format!=='TuneLabProject'||![3,4,5].includes(p.version)||!p.state)throw Error('Expected TuneLab v0.3 / v0.4 / v0.5 project JSON');for(const k of ['mpr','command'])E.validateTable(p.state[k].source);E.analyzeAfm(p.state.afm,null,null,E.AFM_DEFAULTS);if(!Array.isArray(p.state.snapshots))throw Error('Invalid snapshots');state=clone(p.state);if(typeof WBrestore==='function')WBrestore(p.workbench);baseline=validation=review=null;reviewRows=[];afmResult=null;afmDirty=true;for(const[id,v]of Object.entries(p.inputs??{})){const n=$(id);if(!n||n.type==='file')continue;if(n.type==='checkbox')n.checked=!!v;else n.value=String(v);}for(const k of ['mpr','command']){if(p.version===3){state[k].dirty=true;state[k].proposal=null;}}$('baselineConfirm').checked=$('validationConfirm').checked=false;setDemo(false);kind='mpr';for(const id of boostIds)$(id).value=state.mpr.controls[id];renderBoost();renderAfm();renderReview();renderSnapshots();message('Project loaded. Reload matching CSVs and reconfirm before AFM correction. Saved v0.4 boost proposals are retained; confirm they match your current calibration.');}
const descriptions={boost:['Boost tables','Shape the adjustment. Inspect the proposal. Export when ready.'],afm:['AFM scaler','Correct the current curve from matching baseline evidence.'],logs:['Log review','Compare actual and command at the same instant.'],project:['Project & versions','Keep the calibration context with each proposal.']};
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab));[$('pageTitle').textContent,$('pageDesc').textContent]=descriptions[b.dataset.tab];}));document.querySelectorAll('[data-kind]').forEach(b=>b.addEventListener('click',action(()=>switchKind(b.dataset.kind))));
for(const id of boostIds)$(id).addEventListener('change',action(()=>{syncControls();state[kind].dirty=true;renderBoost();message('Boost controls changed. Calculate again before exporting.','dirty');}));
$('previewBoost').addEventListener('click',action(calculateBoost));$('sourceGrid').addEventListener('click',action(e=>{const cell=e.target.closest('[data-r]');if(!cell)return;const t=state[kind].source;if(!t.protect)t.protect=t.values.map(r=>r.map(()=>false));t.protect[+cell.dataset.r][+cell.dataset.c]=!t.protect[+cell.dataset.r][+cell.dataset.c];state[kind].dirty=true;renderBoost();message('Cell protection changed. Recalculate before export.','dirty');}));$('sourceGrid').addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.dataset.r)e.target.click();});
$('importBoost').addEventListener('click',action(()=>{state[kind].source=E.parseTable($('boostPaste').value,state[kind].source);state[kind].proposal=null;state[kind].dirty=true;renderBoost();message('New source loaded. Verify source units and calculate proposal.');}));$('copyBoost').addEventListener('click',action(()=>copy(boostText(true))));$('downloadBoost').addEventListener('click',action(()=>download(`TuneLab-${kind}-${$('outputUnits').value}.tsv`,boostText(false))));
$('baselineFile').addEventListener('change',action(()=>loadCsv($('baselineFile'),'baseline')));$('validationFile').addEventListener('change',action(()=>loadCsv($('validationFile'),'validation')));$('reviewFile').addEventListener('change',action(()=>loadCsv($('reviewFile'),'review')));$('analyzeAfm').addEventListener('click',action(analyze));
document.querySelectorAll('#afm input:not([type=file]),#afm select').forEach(n=>n.addEventListener('change',()=>{if(!['flowUnits','afmPlatform','afmLabels'].includes(n.id))markAfmDirty();}));$('afmGrid').addEventListener('change',action(e=>{if(e.target.dataset.protectAfm!==undefined){state.afm[+e.target.dataset.protectAfm].protect=e.target.checked;markAfmDirty();}}));$('importAfm').addEventListener('click',action(()=>{state.afm=E.parseAfm($('afmPaste').value);afmResult=null;$('baselineConfirm').checked=false;markAfmDirty();renderAfm();message('Current AFM curve loaded. Reconfirm that it matches the baseline calibration.');}));$('copyAfm').addEventListener('click',action(()=>copy(afmText())));$('downloadAfm').addEventListener('click',action(()=>download('TuneLab-AFM-proposed.tsv',afmText())));
$('reviewLog').addEventListener('click',action(renderReview));$('frameSlider').addEventListener('input',inspectFrame);$('saveProject').addEventListener('click',action(()=>download('TuneLab-project.json',JSON.stringify(serialize(),null,2),'application/json')));$('openProject').addEventListener('change',action(async()=>{const f=$('openProject').files[0];if(f)loadProject(JSON.parse(await f.text()));}));
$('snapshot').addEventListener('click',action(()=>{syncControls();state.snapshots.push({name:$('projectName').value+' · '+(state.snapshots.length+1),date:new Date().toLocaleString(),kind,source:clone(state[kind].source),proposal:clone(state[kind].proposal),controls:clone(state[kind].controls)});renderSnapshots();message('Snapshot added. Save project to keep it after closing.');}));$('snapshots').addEventListener('click',action(e=>{const b=e.target.closest('[data-restore]');if(!b)return;const s=state.snapshots[+b.dataset.restore];state[s.kind]={source:clone(s.source),proposal:null,controls:clone(s.controls),dirty:true};switchKind(s.kind,true);message('Snapshot source and controls restored. Calculate again before export.');}));
$('demo').addEventListener('click',action(()=>{
 const headers=['time_ms','AFM Hz','ECT','TPedal','MAP','AFCMD','S.TRIM','Trim','Fuel Status','AF','RPM','BP','BP CMD','Gear','WGCMD'];
 function make(trim){let rows=[headers.join(',')];for(let j=0;j<15000;j++){let t=j*.012,rpm=2500+(j%6000)/6000*4000,hz=4500+(j%6000)/6000*5000,pull=j%6000>4000,pedal=pull?95:10,cmd=pull?12:14.7,bp=pull?21+2*Math.sin(j/400):3;rows.push([j*12,hz,185,pedal,-5,cmd,0,trim,2,cmd,rpm,bp,pull?22:3,3,30].join(','));}const log=E.parseLog(rows.join('\n'),'Synthetic '+(trim===4?'baseline':'validation'));log.synthetic=true;return log;}
 baseline=make(4);validation=make(1);review=baseline;$('baselineConfirm').checked=$('validationConfirm').checked=true;state.afm=clone(TuneLabTables.afm);$('afmSamples').value=100;setDemo(true);analyze();renderReview();message('SYNTHETIC DEMO: generated +4-point baseline / +1-point validation. These are not measurements from your car.');
}));
for(const id of boostIds)$(id).value=state.mpr.controls[id];renderBoost();renderAfm();renderReview();renderSnapshots();
