'use strict';
// Trace the original recorded row, independently of correction eligibility.
const playbackBar11=document.createElement('div');playbackBar11.className='actions playback-global';playbackBar11.innerHTML='<strong>Log Playback</strong><button id="traceFirst11" class="secondary">First</button><button id="tracePrevious11" class="secondary">Previous</button><button id="tracePlay11">Play</button><button id="traceNext11" class="secondary">Next</button><button id="traceLast11" class="secondary">Last</button><label>Speed<select id="traceSpeed11"><option value="0.25">0.25×</option><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option><option value="4">4×</option></select></label><label class="check"><input id="traceShow11" type="checkbox" checked>Table Tracing</label><output id="traceReadout11" role="status"></output>';bar11.append(playbackBar11);
for(const [id,step]of [['traceFirst11','first'],['tracePrevious11',-1],['traceNext11',1],['traceLast11','last']])$(id).onclick=()=>{if(editingHere())stepRaw(step);};
$('tracePlay11').onclick=()=>{if(!editingHere())return;$('rawPlay').onclick();renderTrace11();publishTrace11();};$('traceSpeed11').onchange=()=>{if(!editingHere())return;$('rawSpeed').value=$('traceSpeed11').value;$('rawSpeed').onchange();};$('rawSpeed').addEventListener('change',()=>$('traceSpeed11').value=$('rawSpeed').value);
$('traceShow11').onchange=()=>{if(!editingHere())return;visualReview.showTracking=$('traceShow11').checked;syncTrackingDisplay();renderOverlays();dirtyWindow();scheduleWorkspaceCache();};
function traceCells11(host,cells){if(!host)return;for(const p of cells)host.querySelector('tbody tr:nth-child('+(p.r+1)+') td:nth-child('+(p.c+2)+')')?.classList.add('operating-cell');}
function traceAfm11(host,indices){if(!host)return;for(const j of indices){const table=host.querySelector('table');if(table&&!table.tHead&&/Frequency/i.test(table.rows[0]?.cells[0]?.textContent??'')){for(const row of table.rows)row.cells[j+1]?.classList.add('operating-cell');}else{const row=host.querySelector('tbody tr:nth-child('+(j+1)+')');for(const cell of row?.cells??[])cell.classList.add('operating-cell');}}}
function traceState11(){const item=flowItem(),raw=item?.log.data[rawCursor];if(!raw)return null;const p=item.profile??F.inspect(item.log),get=k=>{const ix=item.log.headers.indexOf(p.mapping[k]);return ix>=0?raw[ix]:NaN;},rpm=get('rpm'),hz=get('hz'),gear=get('gear'),paHeader=p.mapping.pa||'PA',paIx=item.log.headers.indexOf(paHeader),loggedPa=paIx>=0?raw[paIx]:NaN,hasPa=Number.isFinite(loggedPa)&&loggedPa>0&&loggedPa<2,pa=hasPa?loggedPa:+$('referencePa').value,cmdRaw=get('cmd');let cmd=NaN;if(Number.isFinite(cmdRaw)&&['psi','bar','kpa'].includes(p.units.pressure))cmd=W.pressure(cmdRaw,p.units.pressure==='psi'?'ktuner':p.units.pressure,'ktuner',pa);const boost={mpr:V.locations(state.mpr.source,rpm,pa),command:V.locations(state.command.source,rpm,cmd)},afm=[];if(Number.isFinite(hz))try{const[lo,hi,w]=E.bracket(state.afm.map(x=>x.hz),hz);if(1-w>1e-12)afm.push(lo);if(w>1e-12&&!afm.includes(hi))afm.push(hi);}catch{}let gearCells=[];const d=gearCurrent()?displayGear():null;if(d&&Number.isInteger(gear)){const gi=d.gears.findIndex(g=>g.gear===gear),g=d.gears[gi];if(g&&(d.format==='hondata'||gear===+$('selectedGear').value)){const axis=d.format==='hondata'?0:(hasPa?loggedPa:+$('gearPa').value);gearCells=V.locations({rpm:g.rpm,axis:g.axis??[0]},rpm,axis).map(p=>d.format==='hondata'?{r:gi,c:p.r}:p);}}return{item,rpm,hz,gear,pa,hasPa,cmd,boost,afm,gearCells};}
function renderTrace11(){document.querySelectorAll('.operating-cell').forEach(n=>n.classList.remove('operating-cell'));$('tracePlay11').textContent=(rawPlaying||remotePlaying11)?'Pause':'Play';$('tracePlay11').setAttribute('aria-pressed',String(rawPlaying||remotePlaying11));$('traceShow11').checked=visualReview.showTracking!==false;$('traceShow11').disabled=$('traceSpeed11').disabled=!editingHere();const point=traceState11(),enabled=visualReview.showTracking!==false;for(const id of ['traceFirst11','tracePrevious11','tracePlay11','traceNext11','traceLast11'])$(id).disabled=!point||!editingHere();
 if(!point){if($('traceReadout11').textContent!=='Select a log to play and trace recorded samples.')$('traceReadout11').textContent='Select a log to play and trace recorded samples.';return;}const labels=[];if(point.boost.mpr.length)labels.push('MPR');if(point.boost.command.length)labels.push('Command');if(point.afm.length)labels.push('AFM');if(point.gearCells.length)labels.push('Gear Limits');const text=point.item.name+' · Row '+(rawCursor+1)+' · '+((rawPlaying||remotePlaying11)?'Playing':'Paused')+' · '+(enabled?(labels.length?'Tracing '+labels.join(', '):'No mappable table location at this row'):'Tracing hidden')+(point.hasPa?' · Logged PA':' · Atmospheric reference '+fmt(point.pa,3)+' bar')+' · Candidate locations, not ECU influence or tuning eligibility';if($('traceReadout11').textContent!==text)$('traceReadout11').textContent=text;if($('operatingReadout').textContent!==text)$('operatingReadout').textContent=text;if(!enabled)return;
 traceCells11($('sourceGrid'),point.boost[kind]);traceCells11($('proposedGrid'),point.boost[kind]);traceAfm11($('afmPreview'),point.afm);traceAfm11($('afmGrid'),point.afm);traceCells11($('gearGrid'),point.gearCells);
 for(const card of customWorkspace.cards){const panel=[...$('customGrid').children].find(n=>n.dataset.gridId==='custom-'+card.id),host=panel?.querySelector('.custom-table-body');if(card.key in customBoostChoices)traceCells11(host,point.boost[card.key.split('-')[0]]);else if(['host:afmPreview','host:afmGrid'].includes(card.key))traceAfm11(host,point.afm);else if(card.key==='host:gearGrid')traceCells11(host,point.gearCells);}}
renderOverlays=renderTrace11;
let applyingTrace11=false,remotePlaying11=false;
function publishTrace11(){if(applyingTrace11||!editingHere()||!flowItem())return;const m={type:'playbackTrace',projectId:windowProject,sessionId:activeSession,index:rawCursor,playing:rawPlaying,speed:$('rawSpeed').value};if(windowRole==='main')broadcastWindow(m);else sendWindow(m);}
const moveTrace11Base=moveRawCursor;moveRawCursor=function(index){moveTrace11Base(index);publishTrace11();};
const rawTrace11Base=renderRaw;renderRaw=function(){rawTrace11Base();renderTrace11();};
const pauseTrace11Base=pauseRawPlayback;pauseRawPlayback=function(...args){pauseTrace11Base(...args);if(!applyingTrace11)remotePlaying11=false;if($('tracePlay11'))renderTrace11();publishTrace11();};
const inspectTrace11Base=inspectFrame;inspectFrame=function(...args){inspectTrace11Base(...args);const row=reviewRows[selectedFrame];if(row&&flowItem())moveRawCursor(row.sourceIndex);};
const customTrace11Base=renderCustomWorkspace;renderCustomWorkspace=function(){customTrace11Base();renderTrace11();};
const activateTrace11Base=activatePage;activatePage=function(){activateTrace11Base();renderTrace11();};
const gearTrace11Base=renderGear;renderGear=function(){gearTrace11Base();renderTrace11();};
const messageTrace11Base=handleWindowMessage;window.removeEventListener('message',messageTrace11Base);handleWindowMessage=function(e){const m=e.data;if(m?.type!=='playbackTrace')return messageTrace11Base(e);if(!e.viaPort||m.projectId!==windowProject)return;if(windowRole==='main'){const entry=[...windowPeers].find(([token,p])=>p.ref===e.source&&token===m.tuneLabWindow);if(!entry||entry[0]!==windowLease)return;broadcastWindow(m);}else if(e.source!==opener||m.tuneLabWindow!==ownerToken||windowDisconnected)return;const item=sessions.find(s=>s.id===m.sessionId);if(!item||m.sessionId!==activeSession||!Number.isInteger(m.index)||m.index<0||m.index>=item.log.data.length||typeof m.playing!=='boolean'||!['0.25','0.5','1','2','4'].includes(m.speed))return;applyingTrace11=true;try{pauseTrace11Base();remotePlaying11=m.playing;$('rawSpeed').value=$('traceSpeed11').value=m.speed;moveTrace11Base(m.index);renderTrace11();}finally{applyingTrace11=false;}};window.addEventListener('message',handleWindowMessage);
const controlsTrace11Base=windowControls;windowControls=function(...args){controlsTrace11Base(...args);if(!editingHere()&&rawPlaying)pauseTrace11Base('Paused after editing handoff.');renderTrace11();};
$('rawPlay').addEventListener('click',()=>{renderTrace11();publishTrace11();});document.addEventListener('change',e=>{if(e.target.dataset.reviewDisplay==='showTracking')renderTrace11();});renderTrace11();
