'use strict';
// Interface preferences only; native channels, pressure units and calculations are unchanged.
let revision17={schema:1,sections:{}};
let chartDragging17=false,chartContextUntil17=0;
function panLimits17(a,b,shift){const times=rawRows.filter(r=>!rawSourceRange||r.sourceIndex>=rawSourceRange[0]&&r.sourceIndex<=rawSourceRange[1]).map(r=>r.time).filter(Number.isFinite);if(!times.length)return[a,b];let min=Infinity,max=-Infinity;for(const t of times){min=Math.min(min,t);max=Math.max(max,t);}const span=b-a;if(span>=max-min)return[min,max];const start=Math.max(min,Math.min(max-span,a+shift));return[start,start+span];}
function panChart17(a,b,shift,boost,preview=false){const [start,end]=panLimits17(a,b,shift);if(preview){$('rawStart').value=start;$('rawEnd').value=end;if(boost){$('logStart').value=start;$('logEnd').value=end;drawLogChart();}renderRaw();}else zoomRange15(start,end,boost);}
const css17=document.createElement('style');css17.textContent='.page-controls17{display:inline-flex;flex-wrap:wrap;gap:8px;align-items:center;margin:0 0 0 12px}.page-controls17 button{padding:6px 8px}.page-controls17 span{font-size:12px;color:var(--muted)}.chart-nav17{display:flex;flex-wrap:wrap;gap:6px;align-items:center;margin:6px 0}.chart-nav17 span{font-size:12px;color:var(--muted)}.mode-help17{padding:8px;border-left:3px solid var(--accent)}';document.head.append(css17);
function detailsKey17(page,d){if(d.dataset.section17)return d.dataset.section17;const panel=d.closest('[data-panel-id],[data-grid-id]'),base=panel?.dataset.panelId??panel?.dataset.gridId??page.id,label=d.querySelector(':scope>summary')?.textContent.trim()??'section';const peers=[...page.querySelectorAll('details')].filter(x=>x!==d&&x.dataset.section17?.startsWith(base+'|'+label+'|'));return d.dataset.section17=base+'|'+label+'|'+peers.length;}
function saveSections17(page){const prefs=revision17.sections[windowRole]??={};prefs[page.id]=Object.fromEntries([...page.querySelectorAll('details')].map(d=>[detailsKey17(page,d),d.open]));}
function restoreSections17(page){for(const d of page.querySelectorAll('details')){const value=revision17.sections[windowRole]?.[page.id]?.[detailsKey17(page,d)];if(typeof value==='boolean')d.open=value;}}
function revealSection17(node){const page=node.closest('.page');for(let n=node.parentElement;n&&n!==page;n=n.parentElement){if(n.tagName==='DETAILS')n.open=true;if(n.classList.contains('panel-collapsed')){n.classList.remove('panel-collapsed');const b=n.querySelector(':scope>.panel-tools [data-collapse-panel]');if(b)b.textContent='Collapse';if(n.dataset.panelId)savePanel(n);}}if(page){saveSections17(page);saveGrid(page.id);}}
function allSections17(page,open){for(const panel of page.querySelectorAll('.panel')){const button=panel.querySelector(':scope>.panel-tools [data-collapse-panel]');if(!button)continue;panel.classList.toggle('panel-collapsed',!open);button.textContent=open?'Collapse':'Open';savePanel(panel);}for(const d of page.querySelectorAll('details'))d.open=open;saveSections17(page);saveGrid(page.id);dirtyWindow();if(typeof scheduleWorkspaceCache==='function')scheduleWorkspaceCache();}
for(const page of document.querySelectorAll('.page')){const tools=document.createElement('div');tools.className='page-controls17';for(const [label,open]of [['Collapse All',false],['Expand All',true]]){const b=document.createElement('button');b.className='secondary';b.textContent=label;b.dataset.sectionAction17=String(open);b.onclick=()=>allSections17(page,open);tools.append(b);}tools.title='Sections on this page only; the datalog player stays separate';page.querySelector('.logic-summary strong').after(tools);page.addEventListener('toggle',e=>{if(e.target.tagName==='DETAILS'&&!windowApplying){saveSections17(page);if(typeof scheduleWorkspaceCache==='function')scheduleWorkspaceCache();}},true);}
const serialize17Base=serialize;serialize=function(){for(const p of document.querySelectorAll('.page'))saveSections17(p);return{...serialize17Base(),uiRelease:'0.17',revision17:clone(revision17)};};
const load17Base=loadProject;loadProject=function(p){const r=p.revision17??{schema:1,sections:{}};if(r.schema!==1||!r.sections||typeof r.sections!=='object'||Array.isArray(r.sections))throw Error('Invalid v0.17 section preferences');for(const [role,pages]of Object.entries(r.sections)){if(!['main','detached'].includes(role)||!pages||typeof pages!=='object'||Array.isArray(pages))throw Error('Invalid section window');for(const [page,states]of Object.entries(pages))if(!$(page)?.classList.contains('page')||!states||typeof states!=='object'||Array.isArray(states)||Object.values(states).some(v=>typeof v!=='boolean'))throw Error('Invalid section state');}load17Base(p);revision17=clone(r);for(const page of document.querySelectorAll('.page'))restoreSections17(page);refreshSetupSummaries();};
const page17Base=goPage;goPage=function(id){page17Base(id);restoreSections17($(id));refreshSetupSummaries();};
const reset17Base=$('resetWorkspaceGrid').onclick;$('resetWorkspaceGrid').onclick=()=>{reset17Base();delete revision17.sections[windowRole]?.[currentPage()];};
// One glossary across modes. Only interface text is translated, never identifiers or file/channel names.
const glossary17=[[/\blogging\b/gi,m=>m[0]===m[0].toUpperCase()?'Datalogging':'datalogging'],[/\blogs\b/gi,m=>m[0]===m[0].toUpperCase()?'Datalogs':'datalogs'],[/\blog\b/gi,m=>m[0]===m[0].toUpperCase()?'Datalog':'datalog'],[/\brecordings\b/gi,m=>m[0]===m[0].toUpperCase()?'Datalogs':'datalogs'],[/\brecording\b/gi,m=>m[0]===m[0].toUpperCase()?'Datalog':'datalog'],[/\bprovenance\b/gi,'channel source'],[/\beligibility exclusions\b/gi,'excluded samples'],[/\btuning eligibility\b/gi,'samples included for tuning'],[/\bevidence context\b/gi,'datalog and tuning setup'],[/\bsupporting evidence\b/gi,'supporting datalog data'],[/\bevidence range\b/gi,'review range'],[/\bevidence selections\b/gi,'sample selections'],[/\bshared bins\b/gi,'matching operating ranges'],[/\bmissing evidence\b/gi,'Baseline Datalog Needed'],[/\bstale evidence\b/gi,'Datalog Setup Changed'],[/\bevidence filters\b/gi,'sample filters'],[/\bevidence filter\b/gi,'sample filter'],[/\bevidence bookmarks\b/gi,'datalog bookmarks'],[/\bevidence bookmark\b/gi,'datalog bookmark'],[/\bevidence roles\b/gi,'datalog roles'],[/\bevidence configuration\b/gi,'datalog setup'],[/\brevision signature\b/gi,'changes since review'],[/\beligibility\b/gi,'sample inclusion'],[/\braw plots\b/gi,'datalog charts']];
function tuneText17(text){if(!/\b(logs?|logging|recordings?|provenance|eligibility|evidence|shared bins|revision signature)\b/i.test(text))return text;const protectedTerms=[...sessions.flatMap(s=>[s.name,s.notes,s.calibration]),...evidenceBookmarks.map(b=>b.note),customWorkspace.name,$('projectName').value,...revision11.layouts.map(x=>x.name),...sessions.flatMap(s=>s.log?.headers??[])].filter(Boolean).sort((a,b)=>b.length-a.length);protectedTerms.push(...(text.match(/[^:\n<>]*\.(?:csv|txt|kdlg|json|xlsx)\b/gi)??[]));const keep=[];for(const term of new Set(protectedTerms))if(text.includes(term)){const token='\uE000'+keep.length+'\uE001';keep.push(term);text=text.split(term).join(token);}for(const [pattern,replacement]of glossary17)text=text.replace(pattern,replacement);return text.replace(/\uE000(\d+)\uE001/g,(_,i)=>keep[+i]);}
function translateNode17(node){if(node.nodeType===Node.TEXT_NODE){const parent=node.parentElement;if(!parent||parent.closest('script,style,textarea,pre,code,[data-native17],#sourceGrid,#proposedGrid,#afmPreview,#afmGrid,#gearGrid,.custom-table-body,#rawReadout,#frameReadout,#rawChannelPickers,#rawTimeChannel,#logMapping'))return;const text=tuneText17(node.nodeValue);if(text!==node.nodeValue)node.nodeValue=text;}else if(node.nodeType===Node.ELEMENT_NODE){if(node.matches('script,style,textarea,pre,code,[data-native17],#sourceGrid,#proposedGrid,#afmPreview,#afmGrid,#gearGrid,.custom-table-body,#rawReadout,#frameReadout'))return;for(const attr of ['title','aria-label','placeholder'])if(node.hasAttribute(attr)){const old=node.getAttribute(attr),value=tuneText17(old);if(old!==value)node.setAttribute(attr,value);}for(const child of node.childNodes)translateNode17(child);}}
translateNode17(document.body);
const termsObserver17=new MutationObserver(records=>{for(const r of records){if(r.type==='characterData')translateNode17(r.target);else if(r.type==='attributes')translateNode17(r.target);else for(const node of r.addedNodes)translateNode17(node);}});termsObserver17.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['title','aria-label','placeholder']});
const setup17Base=setupFor;setupFor=function(page){const original=setup17Base(page),mode=$('experience').value;if(page==='logs'){const item=flowItem();original.text='Datalog: '+(item?.name??'none selected')+' · Purpose: '+(item?.purpose??'unassigned')+'. Charts: '+(chosenRawChannels().join(', ')||'none selected')+'. Window: '+($('rawStart').value||'start')+'–'+($('rawEnd').value||'end')+' s. '+(rawPlaying?'Playing at '+$('rawSpeed').value+'×.':'Paused.')+(rawSourceRange?' Bookmarked rows '+(rawSourceRange[0]+1)+'–'+(rawSourceRange[1]+1)+'.':'')+' Chart zoom does not change tuning filters.';}const guide={boost:'Confirm the source table and pressure units, calculate the proposed adjustment, then compare before copying it back.',afm:'Confirm the installed AFM curve matches the baseline datalog. Review fuel trims and sample coverage before calculating a correction.',logs:'Select the channels, find the operating range you want to inspect, and compare readings at the selected sample.',gears:'Check the selected gear and native pressure units before changing boost limits.',changes:'Compare each proposed table with its source. Review flagged changes before marking the current proposals reviewed.',strategy:'Choose your tuning goal, follow the datalogging plan, then review the exported datalog.',library:'Choose the intended purpose and baseline or validation role for each datalog.',project:'Save a project backup before making changes or moving to another computer.',settings:'Choose the display mode and units. Save a project backup to keep these preferences with your tables.',history:'Review related table edits together, and use Go to Change to inspect their location.',compare:'Check absolute versus gauge pressure and the atmospheric reference before comparing unit representations.',custom:'Add the tables you want to monitor, then arrange this workspace to suit your review.'};const item=flowItem();let context='';if(page==='boost')context='Supporting datalog: '+(item?.name??'none selected')+'. Table adjustments use the source table and controls below. ';else if(page==='afm')context='Baseline datalog: '+(sessions.find(x=>x.id===$('baselineSession').value)?.name??'none selected')+'. ';else if(page==='changes')context='Supporting datalog: '+(item?.name??'none selected')+'. ';return{text:tuneText17(context+original.text+(mode==='guided'&&guide[page]?' Next: '+guide[page]:'')),rules:mode==='advanced'?tuneText17(original.rules):''};};
for(const box of document.querySelectorAll('.logic-summary')){box.querySelector('strong').textContent='Current Tuning Setup';box.querySelector('details>summary').textContent='Calculation Details and Sample Filters';}
const modeHelp17=document.createElement('p');modeHelp17.className='mode-help17';$('experience').closest('label').after(modeHelp17);function modeDescription17(){const mode=$('experience').value;modeHelp17.textContent=mode==='guided'?'Guided: tuning terms with explanations and the next review step.':mode==='advanced'?'Advanced: the same tuning terms with calculation settings, sample filters and diagnostics.':'Standard: concise tuning terms and the current review setup.';refreshSetupSummaries();}const appearance17Base=applyAppearance;applyAppearance=function(){appearance17Base();modeDescription17();};$('experience').addEventListener('change',modeDescription17);modeDescription17();
// Name changes retain saved workspace IDs and legacy navigation/search compatibility.
for(const entry of Object.values(descriptions))for(let i=0;i<entry.length;i++)entry[i]=tuneText17(entry[i]);descriptions.logs[0]='Datalog Review';descriptions.library[0]='Datalog Library';descriptions.strategy[0]='Datalogging Instructions';applyTypography11();
document.querySelector('.brand small').textContent='LOCAL WORKSPACE · v0.17';document.querySelector('footer').textContent='TuneLab v0.17 · Local Files Only';
