'use strict';
const RF=TuneLabReviewFlow;let evidenceBookmarks=[],rawCursor=0,rawRows=[],rawSourceRange=null;
const reviewFlowPanel=document.createElement('div');reviewFlowPanel.className='panel';reviewFlowPanel.innerHTML=`<h2>Purpose and channel readiness</h2><p>Purpose is your question. A preset selects samples. Baseline / validation roles and calibration matches remain explicit.</p><output id="readinessStatus"></output><ul id="readinessIssues"></ul><p id="purposeSuggestion"></p><div class="actions"><button id="applyPurposeSetup">Apply suggested review setup</button><button id="flowPlan" class="secondary">Driving and review checklist</button><button id="flowMapping" class="secondary">Review channel mapping</button></div>`;$('logs').prepend(reviewFlowPanel);
const rawPanel=document.createElement('div');rawPanel.className='panel';rawPanel.id='rawReviewPanel';rawPanel.innerHTML=`<h2>Selected channels · synchronized inspection</h2><p>Each channel has its own native-value axis. These plots show raw context, not automatically eligible tuning evidence. Large recordings use an extrema-preserving display reduction; the slider and readout inspect every original sample.</p><div class="formrow"><label>Timestamp channel<select id="rawTimeChannel"></select></label><label>Timestamp units<select id="rawTimeUnit"><option value="">Choose units</option><option value="s">Seconds</option><option value="ms">Milliseconds</option></select></label></div><div class="formrow" id="rawChannelPickers"></div><div class="formrow"><label>Chart zoom start · seconds<input id="rawStart" type="number" step="any"></label><label>Chart zoom end · seconds<input id="rawEnd" type="number" step="any"></label><button id="resetRawRange" class="secondary">Show whole recording</button></div><div id="rawPlots"></div><label>Inspect original sample<input id="rawSlider" type="range" min="0" max="0" value="0"></label><div class="formrow"><button id="rawFirst" class="secondary">Start</button><button id="rawPrevious" class="secondary">Previous sample</button><button id="rawPlay">Play</button><button id="rawNext" class="secondary">Next sample</button><button id="rawLast" class="secondary">End</button><label>Playback speed<select id="rawSpeed"><option value="0.25">0.25×</option><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option><option value="4">4×</option></select></label></div><p id="rawPlaybackStatus" role="status">Paused. Playback follows recorded timestamps in the visible range. It pauses at timestamp resets; no interpolation across gaps.</p><pre id="rawReadout"></pre><h3>Save an evidence bookmark</h3><p>Chart zoom only changes what is visible. A bookmark records an explicit range and observation; it does not change AFM calculations or boost eligibility.</p><div class="formrow"><label>First original data row<input id="bookmarkFirst" type="number" min="1" value="1"></label><label>Last original data row<input id="bookmarkLast" type="number" min="1" value="1"></label></div><label>Observation<textarea id="bookmarkNote" rows="2" placeholder="What you saw, revision and remaining uncertainty"></textarea></label><button id="saveEvidenceBookmark">Save bookmark</button><div id="evidenceBookmarkList"></div>`;reviewFlowPanel.after(rawPanel);
for(let j=0;j<4;j++){const label=document.createElement('label');label.innerHTML=`Channel ${j+1}<select id="rawChannel${j}"><option value="">None</option></select>`;$('rawChannelPickers').append(label);}
const validationPanel=document.createElement('div');validationPanel.className='panel';validationPanel.id='validationReviewPanel';validationPanel.innerHTML=`<h2>Matched-range validation comparison</h2><p>Compare independently eligible samples in shared Hz or RPM bins. Different coverage is shown explicitly; this does not prove a change caused an outcome.</p><div class="formrow"><label>Baseline recording<select id="compareBaseline"></select></label><label>Post-change recording<select id="compareValidation"></select></label><label>Question<select id="comparePurpose"><option value="afm">AFM trim by frequency</option><option value="boost">Boost error by RPM</option></select></label><label>Minimum samples per shared bin<input id="compareMinSamples" type="number" min="1" value="5"></label></div><label class="check"><input id="compareConditions" type="checkbox">I checked applied revisions, fuel, hardware, gear and comparable operating conditions</label><button id="compareMatched">Compare eligible ranges</button><output id="matchedSummary"></output><div id="matchedGrid" class="table-scroll"></div>`;rawPanel.after(validationPanel);
function flowItem(){return sessions.find(x=>x.id===activeSession);}
function renderReadiness(){const item=flowItem(),purpose=item?.purpose??'unknown',r=RF.readiness(item,purpose),plan=RF.purposes[purpose];$('readinessStatus').textContent=r.status+' · '+(purposeNames[purpose]??'Raw context');$('readinessIssues').innerHTML=r.issues.map(x=>`<li>${esc(x)}</li>`).join('');$('purposeSuggestion').textContent=plan?`Suggested preset: ${plan.preset}; minimum RPM ${plan.minRpm}. Applying this resets the plot range; evidence roles and confirmations stay as chosen.`:'Choose an intended purpose in Log library; raw inspection is available after timestamp units are specified.';$('applyPurposeSetup').disabled=!item||!plan;}
function configureRaw(){pauseRawPlayback();const item=flowItem();if(!item){rawRows=[];$('rawPlots').textContent='Select a log to inspect.';renderReadiness();return;}const p=item.profile??F.inspect(item.log),options='<option value="">None</option>'+item.log.headers.map(h=>`<option value="${esc(h)}">${esc(h)}</option>`).join('');$('rawTimeChannel').innerHTML=options;$('rawTimeChannel').value=p.mapping.time??'';$('rawTimeUnit').value=p.units.time??'';const keys=item.purpose==='startup'?['rpm','ect']:item.purpose==='afm'?['hz','trim','ect','pedal']:['rpm','bp','cmd','pedal'];for(let j=0;j<4;j++){$('rawChannel'+j).innerHTML=options;$('rawChannel'+j).value=p.mapping[keys[j]]??(j===2&&item.purpose==='startup'?item.log.headers.find(h=>/battery.*v|voltage/i.test(h))??'':'');}rawCursor=0;rawSourceRange=null;$('rawStart').value=$('rawEnd').value='';$('bookmarkFirst').value=1;$('bookmarkLast').value=item.log.data.length;renderRaw();renderReadiness();}
function chosenRawChannels(){return[...new Set([0,1,2,3].map(j=>$('rawChannel'+j).value).filter(Boolean))];}
function renderRaw(){const item=flowItem();if(!item)return;try{rawRows=RF.rows(item.log,$('rawTimeChannel').value,$('rawTimeUnit').value);let visible=rawSourceRange?rawRows.filter(r=>r.sourceIndex>=rawSourceRange[0]&&r.sourceIndex<=rawSourceRange[1]):rawRows;const a=$('rawStart').value,b=$('rawEnd').value;if(a!==''||b!=='')visible=RF.range(visible,a===''?-Number.MAX_VALUE:+a,b===''?Number.MAX_VALUE:+b);const channels=chosenRawChannels();$('rawSlider').max=Math.max(0,item.log.data.length-1);rawCursor=Math.min(rawCursor,item.log.data.length-1);$('rawSlider').value=rawCursor;
 $('rawPlots').innerHTML=channels.map((h,j)=>{const ix=item.log.headers.indexOf(h),values=visible.map(r=>r.values[ix]),stats=RF.summary(values);if(!stats.count||!visible.length)return`<p>${esc(h)}: no numeric samples in this view.</p>`;const lo=stats.min,hi=stats.max===lo?lo+1:stats.max,timeStats=RF.summary(visible.map(r=>r.time)),x0=timeStats.min,x1=timeStats.max===x0?x0+1:timeStats.max,X=t=>50+(t-x0)/(x1-x0)*800,Y=v=>150-(v-lo)/(hi-lo)*120;let d='';for(const part of RF.plotSegments(visible,ix)){for(let k=0;k<part.length;k++)d+=(k?'L':'M')+X(part[k].time).toFixed(2)+' '+Y(part[k].values[ix]).toFixed(2)+' ';}const cursor=item.log.data[rawCursor],tix=item.log.headers.indexOf($('rawTimeChannel').value),ct=cursor[tix]/($('rawTimeUnit').value==='ms'?1000:1);return`<div class="chart" data-raw-channel="${j}"><strong>${esc(h)}</strong> · native values ${fmt(stats.min,3)}–${fmt(stats.max,3)}<svg data-x0="${x0}" data-x1="${x1}" viewBox="0 0 900 180" role="img" aria-label="${esc(h)} versus time"><path d="${d}" fill="none" stroke="var(--accent)" stroke-width="1.5"/>${ct>=x0&&ct<=x1?`<line class="raw-cursor" x1="${X(ct)}" x2="${X(ct)}" y1="20" y2="155" stroke="var(--text)" stroke-dasharray="4 3"/>`:''}<text x="50" y="175" fill="var(--muted)">${fmt(x0)} s</text><text x="760" y="175" fill="var(--muted)">${fmt(x1)} s</text></svg></div>`;}).join('')||'<p>Choose channels to plot.</p>';
 $('rawReadout').textContent=(rawSourceRange?'Bookmarked rows '+(rawSourceRange[0]+1)+'–'+(rawSourceRange[1]+1)+'; Show whole recording clears this restriction.\n':'')+'Original data row '+(rawCursor+1)+'\n'+item.log.headers.map((h,j)=>h+': '+fmt(item.log.data[rawCursor][j],4)).join(' · ');
 for(const plot of $('rawPlots').querySelectorAll('svg'))plot.onclick=e=>{pauseRawPlayback();const rect=plot.getBoundingClientRect(),fraction=Math.max(0,Math.min(1,((e.clientX-rect.left)/rect.width*900-50)/800)),times=RF.summary(visible.map(r=>r.time)),target=times.min+fraction*(times.max-times.min);moveRawCursor(visible.reduce((best,r)=>Math.abs(r.time-target)<Math.abs(best.time-target)?r:best,visible[0]).sourceIndex);};
 }catch(e){rawRows=[];$('rawPlots').textContent=e.message;$('rawReadout').textContent='Original raw values remain in the log; choose time units to synchronize plots.';}}
for(const id of ['rawTimeChannel','rawTimeUnit','rawChannel0','rawChannel1','rawChannel2','rawChannel3','rawStart','rawEnd'])$(id).onchange=()=>{pauseRawPlayback();renderRaw();};$('rawSlider').oninput=()=>{pauseRawPlayback();moveRawCursor(+$('rawSlider').value);};$('resetRawRange').onclick=()=>{pauseRawPlayback();rawSourceRange=null;$('rawStart').value=$('rawEnd').value='';renderRaw();};
let rawPlaybackTimer=null,rawPlaying=false;
function pauseRawPlayback(note='Paused.'){clearTimeout(rawPlaybackTimer);rawPlaybackTimer=null;rawPlaying=false;if($('rawPlay')){$('rawPlay').textContent='Play';$('rawPlay').setAttribute('aria-pressed','false');$('rawPlaybackStatus').textContent=note;}}
function playbackRows(){let rows=rawSourceRange?rawRows.filter(r=>r.sourceIndex>=rawSourceRange[0]&&r.sourceIndex<=rawSourceRange[1]):rawRows;const a=$('rawStart').value,b=$('rawEnd').value;return RF.range(rows,a===''?-Number.MAX_VALUE:+a,b===''?Number.MAX_VALUE:+b);}
function moveRawCursor(index){const item=flowItem();if(!item)return;rawCursor=index;$('rawSlider').value=index;const tix=item.log.headers.indexOf($('rawTimeChannel').value),time=item.log.data[index][tix]/($('rawTimeUnit').value==='ms'?1000:1);for(const svg of $('rawPlots').querySelectorAll('svg')){svg.querySelector('.raw-cursor')?.remove();const a=+svg.dataset.x0,b=+svg.dataset.x1;if(Number.isFinite(time)&&time>=a&&time<=b){const line=document.createElementNS('http://www.w3.org/2000/svg','line'),x=50+(time-a)/(b-a)*800;for(const [k,v]of Object.entries({class:'raw-cursor',x1:x,x2:x,y1:20,y2:155,stroke:'var(--text)','stroke-dasharray':'4 3'}))line.setAttribute(k,v);svg.append(line);}}$('rawReadout').textContent='Original data row '+(index+1)+'\n'+item.log.headers.map((h,j)=>h+': '+fmt(item.log.data[index][j],4)).join(' · ');selectedFrame=reviewRows.findIndex(r=>r.sourceIndex===index);$('frameSlider').value=Math.max(0,selectedFrame);renderOverlays();}
function stepRaw(direction){pauseRawPlayback();try{const rows=playbackRows();if(!rows.length)return;let j=rows.findIndex(r=>r.sourceIndex===rawCursor);j=direction==='first'?0:direction==='last'?rows.length-1:Math.max(0,Math.min(rows.length-1,(j<0?0:j)+direction));moveRawCursor(rows[j].sourceIndex);}catch(e){pauseRawPlayback(e.message);}}
$('rawFirst').onclick=()=>stepRaw('first');$('rawLast').onclick=()=>stepRaw('last');$('rawPrevious').onclick=()=>stepRaw(-1);$('rawNext').onclick=()=>stepRaw(1);$('rawSpeed').onchange=()=>pauseRawPlayback('Speed changed. Press Play to continue.');
$('rawPlay').onclick=()=>{if(rawPlaying){pauseRawPlayback();return;}try{const rows=playbackRows();if(!rows.length)throw Error('Choose a log, timestamp units and a nonempty visible range.');let j=rows.findIndex(r=>r.sourceIndex===rawCursor);if(j<0||j===rows.length-1)j=0;moveRawCursor(rows[j].sourceIndex);const started=performance.now(),firstTime=rows[j].time,speed=+$('rawSpeed').value;rawPlaying=true;$('rawPlay').textContent='Pause';$('rawPlay').setAttribute('aria-pressed','true');$('rawPlaybackStatus').textContent='Playing '+speed+'× · visible range · recorded timing';const tick=()=>{if(!rawPlaying)return;const target=firstTime+(performance.now()-started)/1000*speed;let next=j;while(next+1<rows.length&&rows[next+1].time>rows[next].time&&rows[next+1].time<=target)next++;if(next!==j){j=next;moveRawCursor(rows[j].sourceIndex);}if(j===rows.length-1){pauseRawPlayback('End of visible range.');return;}if(rows[j+1].time<=rows[j].time){pauseRawPlayback('Timestamp reset. Step to the next sample, then press Play.');return;}rawPlaybackTimer=setTimeout(tick,100);};tick();}catch(e){pauseRawPlayback(e.message);}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseRawPlayback('Paused while the window is hidden.');});
$('applyPurposeSetup').onclick=action(()=>{const item=flowItem(),plan=RF.purposes[item?.purpose];if(!plan)throw Error('Choose a logging purpose first.');$('logPreset').value=plan.preset;$('reviewMinRpm').value=plan.minRpm;$('logStart').value=$('logEnd').value='';$('logEvent').value='all';configureRaw();if(RF.readiness(item,'boost').missing?.length===0)renderReview();message('Purpose setup applied. Baseline / validation roles and calibration confirmations remain explicit.');});
$('flowPlan').onclick=()=>reviewPlanButton.click();$('flowMapping').onclick=()=>goPage('library');
function refreshMatched(){for(const id of ['compareBaseline','compareValidation']){const n=$(id),old=n.value;n.innerHTML='<option value="">Choose recording</option>'+sessions.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} · ${esc(x.calibration||'revision unrecorded')}</option>`).join('');n.value=sessions.some(x=>x.id===old)?old:'';}$('compareConditions').checked=false;$('matchedSummary').textContent='Choose two recordings, review their mappings and confirm comparable conditions.';$('matchedGrid').innerHTML='';}
$('compareMatched').onclick=action(()=>{if(!$('compareConditions').checked)throw Error('Check revisions and comparable conditions before comparing.');const result=RF.compare(sessions.find(x=>x.id===$('compareBaseline').value),sessions.find(x=>x.id===$('compareValidation').value),$('comparePurpose').value,{minSamples:+$('compareMinSamples').value,afm:afmOptions()});$('matchedSummary').textContent=`${result.overlap} shared supported bins · ${result.baselineSamples} baseline / ${result.validationSamples} validation samples. ${result.metric}. Delta is validation mean minus baseline mean, not a predicted outcome.`;$('matchedGrid').innerHTML='<table><thead><tr><th>'+result.axis+'</th><th>Baseline n / mean</th><th>Validation n / mean</th><th>Delta</th></tr></thead><tbody>'+result.bins.map(b=>`<tr><td>${b.bin}–${b.end}</td><td>${b.baseline.count} / ${fmt(b.baseline.mean,3)}</td><td>${b.validation.count} / ${fmt(b.validation.mean,3)}</td><td>${b.supported?fmt(b.delta,3):'Insufficient shared coverage'}</td></tr>`).join('')+'</tbody></table>';});
function renderBookmarks(){$('evidenceBookmarkList').innerHTML=evidenceBookmarks.map(b=>`<article><strong>${esc(sessions.find(x=>x.id===b.sessionId)?.name??'Removed log')}</strong> · original rows ${b.first+1}–${b.last+1} · revision ${esc(b.calibration||'unrecorded')} · ${esc(purposeNames[b.purpose]??'Unspecified')}<p>${esc(b.note)}</p><button data-open-bookmark="${esc(b.id)}">Reopen range</button><button class="secondary" data-delete-bookmark="${esc(b.id)}">Delete bookmark</button></article>`).join('')||'<p>No evidence bookmarks saved.</p>';}
$('saveEvidenceBookmark').onclick=action(async()=>{const item=flowItem();if(!item||!rawRows.length)throw Error('Choose a log and timestamp units first.');const bookmark={id:workspaceToken(),sessionId:item.id,first:+$('bookmarkFirst').value-1,last:+$('bookmarkLast').value-1,note:$('bookmarkNote').value,channels:chosenRawChannels(),timeHeader:$('rawTimeChannel').value,timeUnit:$('rawTimeUnit').value,purpose:item.purpose??'unknown',calibration:item.calibration??'',date:new Date().toISOString()};RF.bookmarks([bookmark],sessions);evidenceBookmarks.push(bookmark);renderBookmarks();await persistSessionStore();message('Evidence bookmark saved with original sample identities. Download project JSON to keep it portably.');});
$('evidenceBookmarkList').onclick=action(async e=>{const button=e.target.closest('[data-open-bookmark],[data-delete-bookmark]');if(!button)return;const id=button.dataset.openBookmark??button.dataset.deleteBookmark,b=evidenceBookmarks.find(x=>x.id===id);if(button.dataset.deleteBookmark){evidenceBookmarks=evidenceBookmarks.filter(x=>x.id!==id);renderBookmarks();await persistSessionStore();return;}if(!sessions.some(x=>x.id===b.sessionId))throw Error('This log was removed; the saved observation remains.');setActive(b.sessionId);$('rawTimeChannel').value=b.timeHeader;$('rawTimeUnit').value=b.timeUnit;for(let j=0;j<4;j++)$('rawChannel'+j).value=b.channels[j]??'';const item=flowItem(),ix=item.log.headers.indexOf(b.timeHeader),factor=b.timeUnit==='ms'?1000:1;const times=RF.summary(item.log.data.slice(b.first,b.last+1).map(row=>row[ix]/factor));$('rawStart').value=times.min;$('rawEnd').value=times.max;$('bookmarkFirst').value=b.first+1;$('bookmarkLast').value=b.last+1;rawCursor=b.first;rawSourceRange=[b.first,b.last];renderRaw();goPage('logs');rawPanel.scrollIntoView?.({block:'start'});});
const activeFlowBase=setActive;setActive=function(id){activeFlowBase(id);configureRaw();refreshMatched();renderBookmarks();};
const serialFlowBase=serialize;serialize=function(){return{...serialFlowBase(),reviewFlow:{schema:1,bookmarks:clone(evidenceBookmarks),view:flowItem()?{sessionId:activeSession,timeHeader:$('rawTimeChannel').value,timeUnit:$('rawTimeUnit').value,channels:chosenRawChannels(),start:$('rawStart').value,end:$('rawEnd').value,cursor:rawCursor,sourceRange:rawSourceRange}:null}};};
const loadFlowBase=loadProject;loadProject=function(p){const payload=p.reviewFlow??{schema:1,bookmarks:[]};if(payload.schema!==1)throw Error('Unsupported evidence review schema');const records=(p.sessionLibrary?.sessions??[]).map(x=>({...x,log:E.parseLog(x.text,x.name)})),next=RF.bookmarks(payload.bookmarks,records),view=payload.view,record=records.find(x=>x.id===view?.sessionId);if(view&&(!record||!Array.isArray(view.channels)||view.channels.some(h=>!record.log.headers.includes(h))||!['','s','ms'].includes(view.timeUnit)||typeof view.timeHeader!=='string'||(view.timeHeader&&!record.log.headers.includes(view.timeHeader))||!Number.isInteger(view.cursor)||view.cursor<0||view.cursor>=record.log.data.length||(view.sourceRange!==undefined&&view.sourceRange!==null&&(!Array.isArray(view.sourceRange)||view.sourceRange.length!==2||!view.sourceRange.every(Number.isInteger)||view.sourceRange[0]<0||view.sourceRange[1]<view.sourceRange[0]||view.sourceRange[1]>=record.log.data.length))||![view.start,view.end].every(x=>typeof x==='string'&&(x===''||Number.isFinite(+x)))))throw Error('Invalid raw review view');loadFlowBase(p);evidenceBookmarks=next;configureRaw();if(view&&view.sessionId===activeSession){$('rawTimeChannel').value=view.timeHeader;$('rawTimeUnit').value=view.timeUnit;for(let j=0;j<4;j++)$('rawChannel'+j).value=view.channels[j]??'';$('rawStart').value=view.start;$('rawEnd').value=view.end;rawCursor=view.cursor;rawSourceRange=view.sourceRange??null;renderRaw();}refreshMatched();renderBookmarks();};
document.addEventListener('change',e=>{if(e.target.dataset.sessionMeta||e.target.dataset.profileMap!==undefined||e.target.id==='saveLogProfile'){renderReadiness();refreshMatched();}});
renderReadiness();refreshMatched();renderBookmarks();

const payloadFlowBase=sessionPayload;sessionPayload=function(){return{...payloadFlowBase(),evidenceBookmarks:clone(evidenceBookmarks)};};
const restoreFlowBase=restoreSessions;restoreSessions=function(payload){restoreFlowBase(payload);evidenceBookmarks=RF.bookmarks(payload?.evidenceBookmarks??[],sessions);renderBookmarks();};

for(const id of ['compareBaseline','compareValidation','comparePurpose','compareMinSamples','compareConditions'])$(id).onchange=()=>{if(id!=='compareConditions')$('compareConditions').checked=false;$('matchedSummary').textContent='Comparison inputs changed. Check conditions and compare again.';$('matchedGrid').innerHTML='';};
