'use strict';
const V=TuneLabReview;
// Show a short per-file status first; detailed provenance remains available.
profilePanel.querySelector('h2').textContent='Log format';
const formatSummary=document.createElement('p');formatSummary.id='logFormatSummary';formatSummary.setAttribute('role','status');profilePanel.querySelector('h2').after(formatSummary);
const profileDetails=document.createElement('details');profileDetails.id='logFormatDetails';profileDetails.innerHTML='<summary>Review units and channel mapping</summary>';
for(const node of [...profilePanel.children])if(!['H2'].includes(node.tagName)&&node!==formatSummary)profileDetails.append(node);profilePanel.append(profileDetails);
const formatHelp=document.createElement('details');formatHelp.id='logFormatHelp';formatHelp.innerHTML='<summary>Help: how to review this export</summary><p>A channel is a column in your CSV, such as engine speed or actual boost. Mapping tells TuneLab which column to use for each measurement. Provenance records the file, units and mapping choices behind the analysis; it does not change the original CSV.</p><ol><li>Choose the active log in the top bar. Check the platform in the exporting software; header suggestions can be uncertain.</li><li>Open Review units and channel mapping. Match the requested measurements to the CSV headers and choose the units the export actually uses. Leave unavailable or uncertain channels unmapped.</li><li>Check the original export, then tick the confirmation and save. This confirms your mapping review, not that the log matches a calibration or validates a proposal.</li></ol><p>Boost review needs timestamp, RPM, actual boost and commanded boost; loaded-operation presets also need pedal. AFM additionally needs frequency, coolant, pedal, MAP, commanded AFR, trim and a reviewed fuel-status convention. Missing AFM channels can leave boost review usable.</p><p>Pressure above surrounding air and pressure relative to a standard reference are different. Verify that distinction in the exporting software. Separate baseline/validation calibration confirmations remain in AFM.</p>';
profilePanel.append(formatHelp);
const profileHelpText={profileTime:'Milliseconds are 1/1000 of a second. Use the unit recorded by the export, not the apparent duration.',profilePressure:'Applies to actual and commanded boost together. Absolute pressure includes atmosphere; verify the exported pressure reference.',profileEct:'Coolant temperature units used by warm-engine AFM filtering.',profileTrim:'Percentage points: 4 means 4%. Fraction: 0.04 means 4%. Choose the export convention.',profileMapUnit:'MAP means manifold absolute pressure. This unit normalizes the AFM stability filter; it is separate from boost display units.',logPlatform:'Records exporting software. Selecting a name does not verify channel meanings.'};
for(const[id,text]of Object.entries(profileHelpText)){const hint=document.createElement('small');hint.id=id+'Help';hint.className='profile-help';hint.textContent=text;$(id).closest('label').append(hint);$(id).setAttribute('aria-describedby',hint.id);}
$('profilePressure').querySelector('[value="psi"]').textContent='PSI · standard reference';
const channelHelp={time:['Timestamp','Elapsed log time; choose seconds or milliseconds above.'],rpm:['Engine speed','Engine speed in RPM.'],bp:['Actual boost','Measured boost pressure, using the selected pressure convention.'],cmd:['Commanded boost','Requested boost pressure, using the same pressure convention.'],pedal:['Accelerator pedal','Pedal percentage; throttle voltage is not an interchangeable measurement.'],gear:['Gear','Recorded gear number; leave unmapped if unavailable.'],wg:['Wastegate command','Optional recorded command for context; verify the export meaning.'],hz:['Airflow sensor frequency','Frequency in Hz; sensor voltage is not interchangeable.'],ect:['Coolant temperature','Used by AFM warm-engine filtering.'],map:['Manifold absolute pressure','MAP for AFM stability; choose its units separately.'],trim:['Fuel trim','Reviewed trim channel and percentage/fraction convention. Separate trims are not combined automatically.'],fuel:['Fuel status','AFM currently expects reviewed closed-loop status value 2. Other conventions need separate support.'],af:['Measured AFR','Air/fuel ratio; lambda is not automatically converted.'],cmdAf:['Commanded AFR','Commanded air/fuel ratio used by AFM eligibility, distinct from commanded boost.']};
const showLogProfileReviewBase=showLogProfile;showLogProfile=function(){showLogProfileReviewBase();const item=sessions.find(x=>x.id===activeSession);profileDetails.hidden=!item;$('profileReport').textContent='';if(!item){formatSummary.textContent='Choose an active historical log to review its format.';return;}const p=profileFor(item),mapped=Object.values(p.mapping).filter(Boolean).length;formatSummary.textContent=`${item.name} · ${p.platform==='unknown'?'Export platform unconfirmed':p.platform==='hondata'?'Hondata':'KTuner'} · ${p.confirmed?'Mapping reviewed':'Mapping needs review'} · ${mapped} mapped channels${item.log.rejectedRows?' · '+item.log.rejectedRows.toLocaleString()+' rows rejected; inspect export structure':''}. Raw CSV retained.`;
$('profileMapping').querySelectorAll('[data-profile-map]').forEach(select=>{const[labelText,text]=channelHelp[select.dataset.profileMap]??[select.dataset.profileMap,'Verify this channel in the original export.'];const label=select.closest('label');if(label.firstChild?.nodeType===3)label.firstChild.textContent=labelText;const hint=document.createElement('small');hint.id='profileChannelHelp-'+select.dataset.profileMap;hint.className='profile-help';hint.textContent=text;label.append(hint);select.setAttribute('aria-describedby',hint.id);});};
showLogProfile();

const afmLinkCache={};
let visualReview=V.settings(),reviewAcknowledgement=null,evidenceRange=null,evidenceBin=null,evidenceSelection=null;

const shadingPanel=document.createElement('div');shadingPanel.className='panel';shadingPanel.innerHTML=`<h2>Table shading and tracking</h2><div class="formrow"><label class="check"><input type="checkbox" data-review-display="showTracking" checked>Show cursor tracking</label><label class="check"><input type="checkbox" data-review-display="showCoverage" checked>Show coverage counts</label></div><p class="hint">Blue outlines show the selected log frame’s candidate operating location. Dotted underlines and · numbers show linked-sample counts. Counts describe coverage, not confidence or a confirmed calibration match. These switches change display only.</p><div class="formrow"><label>Display<select id="tableShading"><option value="values">Values · shared original/proposed scale</option><option value="absolute">Change · absolute difference</option><option value="percent">Change · percentage</option><option value="none">No shading</option></select></label><label>Palette<select id="shadingPalette"><option value="accessible">Blue / amber · colorblind friendly</option><option value="warm">Warm gradient · blue / red changes</option><option value="tealTraffic">Teal blue → green → yellow → orange → red</option><option value="violetGold">Violet → gold</option><option value="ocean">Ocean · pale aqua → deep blue</option><option value="ember">Ember · cream → orange → burgundy</option></select></label><button id="resetShading" class="secondary">Reset shading scales</button></div><p class="hint">Colors describe numbers, not severity. Difference scales are centered on zero. Scales stay fixed while editing; values outside them are clipped and counted in the legend. Selection, × protection and review alerts have separate indicators. Percentages require a positive original value.</p>`;$('settings').append(shadingPanel);
for(const id of ['sourceGrid','proposedGrid','afmPreview','gearGrid']){const legend=document.createElement('p');legend.id=id+'ShadingLegend';legend.className='shading-legend';$(id).after(legend);}
const gearOriginalView=document.createElement('div');gearOriginalView.innerHTML='<h3>Original gear values · current display units</h3><div id="gearOriginalGrid" class="table-scroll"></div><p id="gearOriginalGridShadingLegend" class="shading-legend"></p>';$('gearGrid').before(gearOriginalView);
for(const page of ['boost','afm','gears']){const panel=document.createElement('div');panel.className='panel';panel.innerHTML=`<h2>Linked historical evidence</h2><div class="formrow"><label class="check"><input type="checkbox" data-review-display="showTracking" checked>Show cursor tracking</label><label class="check"><input type="checkbox" data-review-display="showCoverage" checked>Show coverage counts</label></div><p id="${page}EvidenceContext"></p><div class="actions"><button data-evidence-clear class="secondary">Clear table selection</button><button data-evidence-reset class="secondary">Reset evidence filters</button><button data-evidence-log class="secondary">Open log review</button></div><div id="${page}EvidenceSummary" class="evidence-summary" role="status"></div><details><summary>Inspect contributing samples</summary><div id="${page}EvidenceSamples" class="table-scroll"></div></details>`;($(page).querySelector('.workspace')??$(page)).append(panel);}
const rangeTools=document.createElement('div');rangeTools.className='evidence-tools';rangeTools.innerHTML=`<h3>Evidence selection</h3><div class="formrow"><label>Range axis<select id="evidenceAxis"><option value="time">Time · seconds</option><option value="rpm">RPM</option><option value="hz">AFM frequency · Hz</option></select></label><label>Range start<input id="evidenceStart" type="number" step="any"></label><label>Range end<input id="evidenceEnd" type="number" step="any"></label><button id="applyEvidenceRange" class="secondary">Apply evidence range</button><button id="resetEvidenceRange" class="secondary">Reset evidence filters</button></div><p id="evidenceFilterStatus" role="status"></p><p class="hint">Shift-drag the boost chart to select a time/RPM range. Histogram selection includes every matching sample. Plot zoom changes visibility only; evidence filters affect linked coverage and highlighted points without changing proposal calculations.</p>`;$('logChart').before(rangeTools);
const reviewPanel=document.createElement('div');reviewPanel.id='releaseReview';reviewPanel.className='panel';reviewPanel.innerHTML='<h2>Review this revision</h2><p id="reviewRevisionStatus" role="status"></p><button id="markRevisionReviewed">Mark this revision reviewed</button><p class="hint">This records your inspection of the current proposals and evidence context. It does not apply tables to a vehicle or validate an outcome. Later edits, log/mapping changes and calibration confirmation changes require another review.</p>';$('changes').prepend(reviewPanel);
for(const id of ['copyBoost','copyAfm','copyGear']){const button=document.createElement('button');button.className='secondary';button.textContent='Review changes';button.onclick=()=>goPage('changes');$(id).before(button);}
function shadeModels(){
 const b=state[kind],o=b.controls,pa=+o.referencePa,off=+o.offset,base=b.source.values.map(row=>row.map(v=>E.toBar(v,o.sourceUnits,off,pa))),proposal=b.proposal?.values.map(row=>row.map(v=>E.toBar(v,o.outputUnits,off,pa)))??base,models=[{key:'boost-'+kind,unit:'absolute bar',identity:[b.source.rpm,b.source.axis,base],base,proposal,grids:[['sourceGrid',base,false],['proposedGrid',proposal,true]]}];
 const cells=afmResult?.cells??state.afm.map(x=>({...x,proposed:x.flow})),u=$('flowUnits').value,ab=[cells.map(x=>W.flow(x.flow,'gs',u))],ap=[cells.map(x=>W.flow(x.proposed,'gs',u))];models.push({key:'airflow',unit:$('flowUnits').selectedOptions[0].text,identity:[cells.map(x=>x.hz),ab,u],base:ab,proposal:ap,grids:[['afmPreview',ap,true]]});
 const g=gearCurrent();if(g){const d=displayGear(),hon=d.format==='hondata',gear=+$('selectedGear').value,x=d.gears.find(x=>x.gear===gear),values=t=>hon?t.gears.map(x=>x.values.map(v=>v[0])):t.gears.find(x=>x.gear===gear)?.values;
 let original=null;try{const src=wb.gearOriginal;if(src){const converted=src.format===d.format?W.validateGear({...clone(src),units:d.units,gears:src.gears.map(x=>({...clone(x),values:x.values.map(row=>row.map((v,c)=>W.pressure(v,src.units,d.units,x.axis?.[c]??+$('gearPa').value,+$('offset').value)))}))}):W.translateGear(src,d.format,+$('gearPa').value,$('gearAxis').value.split(',').map(Number),$('gearStrategy').value,d.units,+$('offset').value);if(JSON.stringify(converted.gears.map(x=>[x.gear,x.rpm,x.axis]))===JSON.stringify(d.gears.map(x=>[x.gear,x.rpm,x.axis])))original=values(converted);}}catch{}
 const current=values(d),headers=hon?['Gear / RPM',...d.gears[0].rpm]:['RPM / atmosphere',...x.axis],labels=hon?d.gears.map(x=>x.gear):x.rpm;$('gearOriginalGrid').innerHTML=original?'<table><thead><tr>'+headers.map(v=>'<th>'+esc(v)+'</th>').join('')+'</tr></thead><tbody>'+original.map((row,r)=>'<tr><th>'+esc(labels[r])+'</th>'+row.map(v=>'<td>'+fmt(v,3)+'</td>').join('')+'</tr>').join('')+'</tbody></table>':'<p>Matching original coordinates unavailable; differences are not inferred.</p>';
 models.push({key:'gear',unit:unitNames[d.units],identity:[headers,labels,original,d.units,gear,+$('gearPa').value,$('gearStrategy').value],base:original,proposal:current,grids:[['gearOriginalGrid',original,false],['gearGrid',current,true]]});
 }else $('gearOriginalGrid').innerHTML='';return models;
}
function syncTrackingDisplay(){document.querySelectorAll("[data-review-display]").forEach(n=>n.checked=visualReview[n.dataset.reviewDisplay]!==false);}
const trackingOverlayBase=renderOverlays;renderOverlays=function(){trackingOverlayBase();if(visualReview.showTracking===false)document.querySelectorAll(".operating-cell").forEach(n=>n.classList.remove("operating-cell"));};
document.addEventListener("change",e=>{const key=e.target.dataset.reviewDisplay;if(!key)return;visualReview[key]=e.target.checked;syncTrackingDisplay();renderOverlays();renderLinkedEvidence();paintShading();});
function paintShading(){syncTrackingDisplay();
 if(!$('tableShading'))return;for(const model of shadeModels()){
  const key=JSON.stringify(model.identity);if(visualReview.scales[model.key]?.key!==key)visualReview.scales[model.key]={key,ranges:{}};const cache=visualReview.scales[model.key].ranges,mode=visualReview.mode;
  const changes=matrix=>matrix?.map((row,r)=>row.map((v,c)=>model.base?V.delta(model.base[r]?.[c],v,mode==='percent'):null));
  if(mode!=='none'&&!Object.hasOwn(cache,mode)){const nums=mode==='values'?[...(model.base?.flat()??[]),...model.proposal.flat()]:changes(model.proposal).flat();cache[mode]=V.extent(nums,mode!=='values');}
  const range=cache[mode];for(const[id,matrix,isProposal]of model.grids){let clipped=0,missing=0;const host=$(id),legend=$(id+'ShadingLegend');if(!host)continue;
   // Airflow preview includes original and proposed rows in the same scale.
   if(id==='afmPreview'&&matrix){const table=host.querySelector('tbody');if(table&&!table.querySelector('.original-flow-row')){const row=document.createElement('tr');row.className='original-flow-row';row.innerHTML='<th>Original airflow</th>'+model.base[0].map(v=>'<td>'+fmt(v,3)+'</td>').join('');table.insertBefore(row,table.lastElementChild);}}
   const rows=id==='afmPreview'?[host.querySelector('tr.original-flow-row'),host.querySelector('[data-edit="airflow"]')?.parentElement]:[...host.querySelectorAll('tbody tr')];
   for(let r=0;r<rows.length;r++){const row=rows[r];if(!row)continue;for(const[c,cell]of [...row.cells].slice(1).entries()){const originalRow=id==='afmPreview'&&r===0,rr=id==='afmPreview'?0:r,current=originalRow?model.base?.[0]?.[c]:matrix?.[rr]?.[c],value=mode==='values'?current:originalRow||!isProposal?(mode==='percent'&&!(model.base?.[rr]?.[c]>1e-6)?null:0):model.base?V.delta(model.base[rr]?.[c],current,mode==='percent'):null;
    cell.classList.remove('value-shaded');cell.style.removeProperty('--shade-bg');cell.style.removeProperty('--shade-fg');cell.removeAttribute('data-shade-value');if(mode==='none')continue;
    if(!Number.isFinite(value)||(mode!=='values'&&!model.base)){missing++;continue;}if(range&&(value<range[0]||value>range[1]))clipped++;const color=V.color(value,range,visualReview.palette,mode!=='values');if(color){cell.classList.add('value-shaded');cell.style.setProperty('--shade-bg',color.background);cell.style.setProperty('--shade-fg',color.foreground);cell.dataset.shadeValue=value;}
   }}
   if(legend)legend.textContent=mode==='none'?'Shading off.':`${mode==='values'?'Shared original/proposed scale':mode==='percent'?'Δ percentage of positive original '+model.unit+' · zero centered':'Δ '+model.unit+' · zero centered'}: ${range?fmt(range[0],3)+' to '+fmt(range[1],3):'No eligible values'}${mode==='values'?' '+model.unit:''} · ${clipped} clipped · ${missing} unavailable. Scale fixed until reset or source/unit change. ${visualReview.showCoverage===false?'Coverage markers hidden.':'Dotted underline · count marks linked samples.'}`;if(legend&&mode!=='none'&&range){const swatch=document.createElement('span');swatch.className='shading-swatch';swatch.setAttribute('role','img');swatch.setAttribute('aria-label','Low to high color scale'+(mode!=='values'?'; neutral midpoint is zero':''));swatch.style.background='linear-gradient(90deg,'+Array.from({length:9},(_,j)=>range[0]+(range[1]-range[0])*j/8).map(v=>V.color(v,range,visualReview.palette,mode!=='values').background).join(',')+')';legend.prepend(swatch);}
  }
 }
}
function rectangle(target){const s=evidenceSelection;if(!s||s.target!==target)return null;const b=s.b??s.a;return{r0:Math.min(s.a[0],b[0]),r1:Math.max(s.a[0],b[0]),c0:Math.min(s.a[1],b[1]),c1:Math.max(s.a[1],b[1])};}
function filteredEvidenceRows(){let rows=reviewRows;if(evidenceRange){if(evidenceRange.axis==='hz'){const profile=sessions.find(x=>x.id===activeSession)?.profile,ix=review?E.index(review,profile?.mapping.hz||$('map_hz').value):-1;rows=rows.filter(r=>{const v=ix>=0?review.data[r.sourceIndex][ix]:NaN;return Number.isFinite(v)&&v>=evidenceRange.start&&v<=evidenceRange.end;});}else rows=V.rangeRows(rows,evidenceRange.start,evidenceRange.end,evidenceRange.axis);}if(evidenceBin){const ids=new Set(evidenceBin.indices);rows=rows.filter(r=>ids.has(r.sourceIndex));}return rows;}
function boostEvidence(k=kind){const b=state[k],rows=filteredEvidenceRows(),profile=sessions.find(x=>x.id===activeSession)?.profile,paHeader=profile?.mapping?.pa||'PA',ix=review?E.index(review,paHeader):-1;let fallback=0;const axis=row=>{if(k==='command')return row.cmd;const v=ix>=0?review.data[row.sourceIndex][ix]:NaN;if(Number.isFinite(v)&&v>0&&v<2)return v;fallback++;return+b.controls.referencePa;};const links=V.boostLinks(b.source,rows,axis);return{links,rows,fallback};}
function afmEvidence(){const cells=afmResult?.cells??state.afm,samples=afmResult?.baseline?.samples??[],options=afmResult?.reviewOptions??afmOptions(),key=JSON.stringify([cells.map(x=>x.hz),options.bandwidth,options.radius]);if(afmLinkCache.samples!==samples||afmLinkCache.key!==key){afmLinkCache.samples=samples;afmLinkCache.key=key;afmLinkCache.links=V.afmLinks(cells,samples,options.bandwidth,options.radius);}return{links:afmLinkCache.links,cells,options};}
function evidenceContextSignature(){return JSON.stringify({active:activeSession,roles:[baseline?.name,validation?.name],profiles:sessions.map(x=>[x.id,x.profile,x.calibration]),filters:getLogOptions(),event:$('logEvent').value,confirm:[$('baselineConfirm').checked,$('validationConfirm').checked],afm:afmOptions()});}
function revisionSignature(){return JSON.stringify({mpr:state.mpr,command:state.command,afm:state.afm,afmCells:afmResult?.cells,afmDirty,gear:gearCurrent(),gearOriginal:wb.gearOriginal,gearView:[$('gearPa').value,$('gearStrategy').value,$('gearAxis').value,$('gearDisplay').value],evidence:evidenceContextSignature(),evidenceRange,evidenceBin:evidenceBin?.indices??null,rules:[...$('warningSettings').querySelectorAll('input')].map(n=>[n.id,n.value])});}
function afmEvidenceSignature(){return JSON.stringify({source:state.afm,roles:[$('baselineSession').value,$('validationSession').value],logs:[baseline?.name,validation?.name],profiles:sessions.map(x=>[x.id,x.profile]),options:afmOptions()});}
const analyzeReviewBase=analyze;analyze=function(){const before=afmResult;analyzeReviewBase();if(afmResult&&afmResult!==before){afmResult.reviewOptions={bandwidth:+$('afmBandwidth').value,radius:+$('afmRadius').value};afmResult.reviewEvidenceSignature=afmEvidenceSignature();}paintShading();renderLinkedEvidence();};
function renderLinkedEvidence(){
 if(!$('boostEvidenceSummary'))return;
 document.querySelectorAll('.evidence-cell').forEach(n=>{n.classList.remove('evidence-cell');n.removeAttribute('data-evidence-count');});
 const rows=filteredEvidenceRows(),boost=boostEvidence(),links=V.selectedLinks(boost.links,rectangle('boost')),valid=links.filter(x=>x.cells.length),counts=new Map();for(const x of valid)for(const p of x.cells)counts.set(p.r+':'+p.c,(counts.get(p.r+':'+p.c)??0)+1);
 for(const[key,n]of counts){const[r,c]=key.split(':');for(const id of ['sourceGrid','proposedGrid']){const cell=$(id).querySelector(`tbody tr:nth-child(${+r+1}) td:nth-child(${+c+2})`);if(cell&&visualReview.showCoverage!==false){cell.classList.add('evidence-cell');cell.dataset.evidenceCount=n;}}}
 const item=sessions.find(x=>x.id===activeSession);$('boostEvidenceContext').textContent=`${item?.name??'No active log'} · ${item?.calibration||'Calibration unrecorded'} · ${kind.toUpperCase()} operating-location coverage. Logged command is used as a candidate Command index; this does not prove ECU table influence.`;
 const total=state[kind].source.values.flat().length;$('boostEvidenceSummary').textContent=`${valid.length} linked samples / ${rows.length} filtered eligible samples · ${counts.size} of ${total} cells visited · ${total-counts.size} cells without linked evidence${rectangle('boost')?' · table rectangle selected':''}. ${boost.fallback} samples use the selected atmospheric reference rather than logged PA. ${rows.length-boost.links.filter(x=>x.cells.length).length} outside table axes. Counts describe coverage, not confidence.`;
 sampleTable('boostEvidenceSamples',valid.map(x=>x.row),false);
 const afm=afmEvidence(),afmLinks=V.selectedLinks(afm.links,rectangle('airflow')),timeIx=baseline?E.index(baseline,sessions.find(x=>x.id===$('baselineSession').value)?.profile?.mapping.time||$('map_time').value):-1,hzIx=baseline?E.index(baseline,sessions.find(x=>x.id===$('baselineSession').value)?.profile?.mapping.hz||$('map_hz').value):-1;
 const selectedAfm=afmLinks.filter(x=>{if(!x.cells.length)return false;if(!evidenceRange)return true;const profile=sessions.find(s=>s.id===$('baselineSession').value)?.profile,raw=baseline?.data[x.sample.sourceIndex];const value=evidenceRange.axis==='hz'?x.sample.hz:evidenceRange.axis==='time'?(raw?.[timeIx]/((profile?.units.time??$('timeUnit').value)==='s'?1:1000)):raw?.[E.index(baseline,profile?.mapping.rpm||$('map_rpm').value)];return Number.isFinite(value)&&value>=evidenceRange.start&&value<=evidenceRange.end;});
 const support=new Map(),kernel=new Map();for(const x of selectedAfm)for(const p of x.cells){if(p.support)support.set(p.c,(support.get(p.c)??0)+1);if(p.kernel)kernel.set(p.c,(kernel.get(p.c)??0)+1);}
 $('afmPreview').querySelectorAll('[data-edit="airflow"]').forEach(cell=>{const n=support.get(+cell.dataset.ec)??0;if(n&&visualReview.showCoverage!==false){cell.classList.add('evidence-cell');cell.dataset.evidenceCount=n;}});
 const stale=afmDirty||!afmResult?.reviewEvidenceSignature||afmResult.reviewEvidenceSignature!==afmEvidenceSignature();$('afmEvidenceContext').textContent=`${baseline?.name??'No baseline'} · ${afmResult?.manualOnly?'Manual proposal; no correction evidence applied':stale?'Missing or stale analysis provenance; analyze matching evidence again':'Baseline analysis evidence'} · local support ±${afm.options.bandwidth} Hz; kernel uses 50 Hz bin centers within ±${afm.options.bandwidth*afm.options.radius} Hz. Validation never drives correction.`;
 $('afmEvidenceSummary').textContent=`${selectedAfm.length} unique eligible baseline samples linked · ${support.size} frequencies with local support / ${afm.cells.length} · ${kernel.size} frequencies with kernel contributors. ${afm.cells.length-support.size} frequencies without local support in this selection. ${rectangle('airflow')?'Table frequency selection active. ':''}${evidenceBin?'Boost histogram filter applies only to active-log boost coverage, not AFM baseline. ':''}Displayed filters do not recalculate corrections. Sample counts are not confidence.`;
 sampleTable('afmEvidenceSamples',selectedAfm.map(x=>({sourceIndex:x.sample.sourceIndex,time:baseline?.data[x.sample.sourceIndex]?.[timeIx]/((sessions.find(s=>s.id===$('baselineSession').value)?.profile?.units.time??$('timeUnit').value)==='s'?1:1000),hz:x.sample.hz,trim:x.sample.trim,support:x.cells.some(p=>p.support),kernel:x.cells.some(p=>p.kernel)})),true);
 renderGearEvidence(rows);$('evidenceFilterStatus').textContent=`${evidenceRange?`${evidenceRange.axis}: ${fmt(evidenceRange.start,3)}–${fmt(evidenceRange.end,3)}`:'No evidence range'} · ${evidenceBin?'histogram bin: '+evidenceBin.indices.length+' contributors':'no histogram filter'} · ${rows.length} active-log samples after evidence filters. Plot zoom remains separate.`;
 highlightLogEvidence(rows);updateReviewStatus();
}
function sampleTable(id,rows,afm){const head=afm?['Parsed data row','Time s','Hz','Capped trim %','Local support','Kernel contributor']:['Parsed data row','Time s','RPM','Gear','Actual PSI','Command PSI'];$(id).innerHTML=rows.length?'<p>First '+Math.min(100,rows.length)+' of '+rows.length+' unique samples shown. All samples contribute to counts.</p><table><thead><tr>'+head.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.slice(0,100).map(r=>'<tr>'+[r.sourceIndex+1,fmt(r.time,3),afm?fmt(r.hz,2):fmt(r.rpm,0),afm?fmt(r.trim,3):fmt(r.gear,0),afm?(r.support?'Yes':'No'):fmt(r.bp,3),afm?(r.kernel?'Yes':'No'):fmt(r.cmd,3)].map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table>':'<p>No linked samples. Check selection, eligible filters, mappings and source axes.</p>';}
function renderGearEvidence(rows){const g=gearCurrent();if(!g){$('gearsEvidenceContext').textContent='Import gear tables to inspect operating-location evidence.';$('gearsEvidenceSummary').textContent='No gear table.';$('gearsEvidenceSamples').innerHTML='';return;}const d=displayGear(),hon=d.format==='hondata',gear=+$('selectedGear').value,counts=new Map(),linked=[];for(const row of rows){const gi=d.gears.findIndex(x=>x.gear===row.gear);if(gi<0||!hon&&row.gear!==gear)continue;const t=d.gears[gi],profile=sessions.find(x=>x.id===activeSession)?.profile,paIx=review?E.index(review,profile?.mapping.pa||'PA'):-1,raw=paIx>=0?review.data[row.sourceIndex][paIx]:NaN,pa=Number.isFinite(raw)&&raw>0&&raw<2?raw:+$('gearPa').value;const cells=V.locations({rpm:t.rpm,axis:hon?[0]:t.axis},row.rpm,hon?0:pa).map(p=>hon?{r:gi,c:p.r}:p),rect=rectangle('gear');if(!cells.length||rect&&!cells.some(p=>p.r>=rect.r0&&p.r<=rect.r1&&p.c>=rect.c0&&p.c<=rect.c1))continue;linked.push(row);for(const p of cells)counts.set(p.r+':'+p.c,(counts.get(p.r+':'+p.c)??0)+1);}
 for(const[key,n]of counts){const[r,c]=key.split(':');const cell=$('gearGrid').querySelector(`[data-er="${r}"][data-ec="${c}"]`);if(cell&&visualReview.showCoverage!==false){cell.classList.add('evidence-cell');cell.dataset.evidenceCount=n;}}
 $('gearsEvidenceContext').textContent='Active-log gear and RPM locate candidate limits. Missing atmospheric pressure uses the selected gear reference. Derived formats retain their conversion assumptions.';$('gearsEvidenceSummary').textContent=`${linked.length} linked samples / ${rows.length} filtered samples · ${counts.size} visited cells. Operating location does not establish that the gear limit controlled the ECU.`;sampleTable('gearsEvidenceSamples',linked,false);
}
function highlightLogEvidence(rows){const svg=$('logChart').querySelector('svg');if(!svg)return;svg.querySelector('.evidence-points')?.remove();if(!evidenceRange&&!evidenceBin&&!rectangle('boost'))return;const b=plotBounds(),group=document.createElementNS('http://www.w3.org/2000/svg','g');group.setAttribute('class','evidence-points');group.setAttribute('clip-path','url(#logClip)');const linked=new Set(V.selectedLinks(boostEvidence().links,rectangle('boost')).filter(x=>x.cells.length).map(x=>x.row.sourceIndex)),visible=rows.filter(r=>chartRows.includes(r)&&(!rectangle('boost')||linked.has(r.sourceIndex))),step=Math.max(1,Math.ceil(visible.length/800));for(const r of visible.filter((_,j)=>j%step===0)){const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');for(const[k,v]of Object.entries({cx:60+(r[b.x]-b.xmin)/(b.xmax-b.xmin)*870,cy:310-(r.bp-b.ymin)/(b.ymax-b.ymin)*290,r:3,fill:'none',stroke:'var(--text)','stroke-width':1.5}))dot.setAttribute(k,v);group.append(dot);}svg.append(group);}
function updateReviewStatus(){const current=revisionSignature();$('reviewRevisionStatus').textContent=reviewAcknowledgement?.signature===current?`Reviewed ${reviewAcknowledgement.date}. This records inspection; outcome remains unvalidated.`:reviewAcknowledgement?'Changes since your last review. Inspect this revision before export.':'This revision has not been marked reviewed.';}
const reviewDataOriginal=reviewData;
function detailedReview(){const data=reviewDataOriginal();let index=0;for(const k of ['mpr','command']){const b=state[k];if(!b.proposal)continue;const entry=data[index++],ev=boostEvidence(k),counts=new Map();for(const x of ev.links)for(const p of x.cells)counts.set(p.r+':'+p.c,(counts.get(p.r+':'+p.c)??0)+1);let changed=0,covered=0;const protectedCount=b.source.protect?.flat().filter(Boolean).length??0;b.source.values.forEach((row,r)=>row.forEach((v,c)=>{const a=E.toBar(v,b.controls.sourceUnits,+b.controls.offset,+b.controls.referencePa),p=E.toBar(b.proposal.values[r][c],b.controls.outputUnits,+b.controls.offset,+b.controls.referencePa);if(Math.abs(p-a)>1e-9){changed++;if(counts.has(r+':'+c))covered++;}}));entry.reviewEvidence={changed,covered,withoutCoverage:changed-covered,eligible:ev.rows.length,protected:protectedCount,manual:b.proposal.manual?'Manual refinements present; see edit history':'Calculated proposal',context:'Operating-location coverage only; calibration match and outcome unvalidated',log:review?.name??null,calibration:sessions.find(x=>x.id===activeSession)?.calibration??'',atmosphericFallback:ev.fallback};entry.data=`${covered} of ${changed} changed cells have operating-location samples in the active evidence filters; ${changed-covered} have no linked coverage. Calibration match is not established automatically.`;}
 if(afmResult){const entry=data[index++],changed=afmResult.cells.filter(x=>Math.abs(x.proposed-x.flow)>1e-9),stale=afmDirty||!afmResult.reviewEvidenceSignature||afmResult.reviewEvidenceSignature!==afmEvidenceSignature(),covered=changed.filter(x=>(x.samples??0)>=(+ $('afmSamples').value)).length;entry.reviewEvidence={changed:changed.length,covered:stale?0:covered,withoutCoverage:stale?changed.length:changed.length-covered,protected:afmResult.cells.filter(x=>x.protect||x.flow<=0).length,manual:afmResult.cells.some(x=>x.manual)?'Manual refinements present':'Calculated proposal',staleEvidence:stale,baseline:baseline?.name??null,validation:validation?.name??null,baselineConfirmed:$('baselineConfirm').checked,validationConfirmed:$('validationConfirm').checked,context:'Full-analysis local support; display range does not alter correction or validation'};entry.data=stale?'Analysis evidence missing or stale. Reanalyze after confirming the installed calibration; saved/manual proposals do not reconstruct analysis evidence.':`${covered} of ${changed.length} changed frequencies meet the configured full-analysis sample threshold. ${changed.length-covered} do not. Validation is ${validation&&$('validationConfirm').checked?'assigned and calibration-confirmed; inspect validation coverage':'missing or calibration-unconfirmed'}.`;}
 return data;
}
reviewData=detailedReview;
const renderChangesReviewBase=renderChanges;renderChanges=function(){renderChangesReviewBase();const data=detailedReview();$('changeSummary').querySelectorAll('.review-card').forEach((card,j)=>{const entry=data[j];if(!entry)return;const detail=document.createElement('div');detail.className='revision-detail';detail.innerHTML='<h3>Evidence and preserved work</h3><p>'+esc(entry.data)+'</p>'+(entry.reviewEvidence?'<p>'+esc(entry.reviewEvidence.manual)+' · '+entry.reviewEvidence.protected+' protected/nonpositive cells retained. '+(entry.reviewEvidence.staleEvidence?'Evidence stale.':'')+'</p>':'<p>Gear review is at the selected atmospheric reference; inspect other native columns separately.</p>');card.append(detail);});updateReviewStatus();};
$('markRevisionReviewed').onclick=()=>{if(!reviewData().length){message('Calculate or manually edit a proposal before reviewing.','dirty');return;}reviewAcknowledgement={date:new Date().toISOString(),signature:revisionSignature()};updateReviewStatus();};
$('exportReport').addEventListener('click',action(e=>{e.stopImmediatePropagation();download('TuneLab-v0.8-change-review.json',JSON.stringify({version:8,date:new Date().toISOString(),project:$('projectName').value,reviewed:reviewAcknowledgement?.signature===revisionSignature(),reviewedAt:reviewAcknowledgement?.date??null,evidenceFilter:{range:evidenceRange,histogram:evidenceBin?{count:evidenceBin.indices.length}:null},reviewRules:'User review preferences; coverage counts are not confidence or engine safety',reports:detailedReview()},null,2),'application/json');}),true);
function resetEvidence(){evidenceRange=evidenceBin=null;$('evidenceStart').value=$('evidenceEnd').value='';renderLinkedEvidence();drawLogAnalytics();}
$('applyEvidenceRange').onclick=action(()=>{if(!$('evidenceStart').value.trim()||!$('evidenceEnd').value.trim())throw Error('Enter both evidence range bounds');const start=+$('evidenceStart').value,end=+$('evidenceEnd').value;V.rangeRows([],start,end);evidenceRange={axis:$('evidenceAxis').value,start,end};renderLinkedEvidence();});$('resetEvidenceRange').onclick=resetEvidence;
document.addEventListener('click',e=>{const n=e.target.closest('[data-evidence-clear],[data-evidence-reset],[data-evidence-log]');if(!n)return;if(n.hasAttribute('data-evidence-clear')){selection={target:null,a:null,b:null};evidenceSelection=null;paintSelection();}if(n.hasAttribute('data-evidence-reset'))resetEvidence();if(n.hasAttribute('data-evidence-log'))goPage('logs');});
const paintSelectionReviewBase=paintSelection;paintSelection=function(){paintSelectionReviewBase();evidenceSelection=selection.a?clone(selection):null;renderLinkedEvidence();};
const analyticsReviewBase=drawLogAnalytics;drawLogAnalytics=function(){analyticsReviewBase();const bins=S.histogram(reviewRows.map(x=>x.bp-x.cmd),20);$('errorHistogram').querySelectorAll('[data-bin]').forEach(n=>{n.tabIndex=0;n.setAttribute('role','button');n.setAttribute('aria-label','Select all '+bins[+n.dataset.bin].count+' samples in error bin');n.onclick=()=>{const contributors=V.binRows(reviewRows,bins,+n.dataset.bin);evidenceBin={indices:contributors.map(r=>r.sourceIndex)};renderLinkedEvidence();$('errorHistogram').querySelectorAll('[data-bin]').forEach(bar=>{bar.style.stroke=bar===n?'var(--text)':'';bar.style.strokeWidth=bar===n?'2':'';});};n.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();n.onclick();}};});};
const drawLogReviewBase=drawLogChart;drawLogChart=function(){drawLogReviewBase();highlightLogEvidence(filteredEvidenceRows());const svg=$('logChart').querySelector('svg');if(!svg)return;svg.addEventListener('pointerdown',e=>{if(!e.shiftKey)return;e.preventDefault();e.stopImmediatePropagation();const b=plotBounds(),rect=svg.getBoundingClientRect(),value=x=>Math.max(b.xmin,Math.min(b.xmax,b.xmin+((x-rect.left)/(rect.width||950)*950-60)/870*(b.xmax-b.xmin))),start=value(e.clientX);const up=event=>{document.removeEventListener('pointerup',up);document.removeEventListener('pointercancel',cancel);const end=value(event.clientX);evidenceRange={axis:b.x,start:Math.min(start,end),end:Math.max(start,end)};$('evidenceAxis').value=b.x;$('evidenceStart').value=evidenceRange.start;$('evidenceEnd').value=evidenceRange.end;renderLinkedEvidence();};const cancel=()=>{document.removeEventListener('pointerup',up);document.removeEventListener('pointercancel',cancel);};document.addEventListener('pointerup',up);document.addEventListener('pointercancel',cancel);},true);};
const switchKindReviewBase=switchKind;switchKind=function(k,skipSync=false){if(k!==kind){evidenceSelection=null;selection={target:null,a:null,b:null};}switchKindReviewBase(k,skipSync);};
const setActiveReviewBase=setActive;setActive=function(id){evidenceRange=evidenceBin=null;$('evidenceStart').value=$('evidenceEnd').value='';evidenceSelection=null;selection={target:null,a:null,b:null};setActiveReviewBase(id);renderLinkedEvidence();};
for(const[name,fn]of [['boost',renderBoost],['afm',renderAfm],['gear',renderGear],['review',renderReview]]){const wrapped=()=>{fn();paintShading();renderLinkedEvidence();if(name==='afm')installAfmEvidenceRange();};if(name==='boost')renderBoost=wrapped;else if(name==='afm')renderAfm=wrapped;else if(name==='gear')renderGear=wrapped;else renderReview=wrapped;}
function installAfmEvidenceRange(){const hz=(afmResult?.cells??state.afm).filter(x=>x.flow>0).map(x=>x.hz);if(!hz.length)return;const lo=Math.min(...hz),hi=Math.max(...hz);for(const id of ['afmChart','afmDeltaChart']){const svg=$(id).querySelector('svg');if(!svg||svg.dataset.evidenceRangeInstalled)continue;svg.dataset.evidenceRangeInstalled='true';svg.addEventListener('pointerdown',e=>{if(!e.shiftKey)return;e.preventDefault();e.stopImmediatePropagation();const rect=svg.getBoundingClientRect(),value=x=>Math.max(lo,Math.min(hi,lo+((x-rect.left)/(rect.width||900)*900-54)/828*(hi-lo))),start=value(e.clientX);const up=event=>{document.removeEventListener('pointerup',up);evidenceRange={axis:'hz',start:Math.min(start,value(event.clientX)),end:Math.max(start,value(event.clientX))};$('evidenceAxis').value='hz';$('evidenceStart').value=evidenceRange.start;$('evidenceEnd').value=evidenceRange.end;renderLinkedEvidence();};document.addEventListener('pointerup',up,{once:true});},true);}}
const afmDeltaReviewBase=drawAfmDeltas;drawAfmDeltas=function(){afmDeltaReviewBase();installAfmEvidenceRange();};
const serializeReviewBase=serialize;serialize=function(){return{...serializeReviewBase(),visualReview:clone(visualReview),reviewAcknowledgement:clone(reviewAcknowledgement)};};
const loadReviewBase=loadProject;loadProject=function(p){const next=V.settings(p.visualReview),ack=p.reviewAcknowledgement;if(ack!==undefined&&ack!==null&&(typeof ack.signature!=='string'||typeof ack.date!=='string'||!Number.isFinite(Date.parse(ack.date))))throw Error('Invalid revision review record');loadReviewBase(p);visualReview=next;reviewAcknowledgement=ack??null;evidenceRange=evidenceBin=evidenceSelection=null;selection={target:null,a:null,b:null};$('evidenceStart').value=$('evidenceEnd').value='';$('tableShading').value=next.mode;$('shadingPalette').value=next.palette;paintShading();renderLinkedEvidence();};
for(const id of ['tableShading','shadingPalette'])$(id).onchange=()=>{visualReview.mode=$('tableShading').value;visualReview.palette=$('shadingPalette').value;paintShading();};$('resetShading').onclick=()=>{visualReview.scales={};paintShading();};
document.addEventListener('change',e=>{if(['logPreset','logEvent','logPressure','logTime','reviewMinRpm','reviewMaxRpm','logPedal','logDelta'].includes(e.target.id)||e.target.id.startsWith('logmap_'))evidenceBin=null;},true);
document.addEventListener('change',()=>queueMicrotask(()=>{paintShading();renderLinkedEvidence();if(currentPage()==='changes')renderChanges();}));
paintShading();renderLinkedEvidence();installAfmEvidenceRange();
