'use strict';
// UI release versions and the compatible project format are independent.
let revision11={schema:1,order:[],typography:{app:{family:'system',weight:'400',caps:'title'},pages:{}},layouts:[]};
const nav11=document.querySelector('nav'),defaultOrder11=["logs","afm","gears","boost","compare","changes","custom","settings","history","library","strategy","project"];
const families11={system:'system-ui, sans-serif',sans:'Arial, sans-serif',mono:'Consolas, monospace'};
function applyOrder11(){for(const id of new Set([...revision11.order,...defaultOrder11])){const n=nav11.querySelector('[data-tab="'+id+'"]');if(n)nav11.append(n);}const active=$('workspaceSelect').value;$('workspaceSelect').innerHTML=[...nav11.querySelectorAll('[data-tab]')].map(n=>'<option value="'+n.dataset.tab+'">'+esc(n.textContent.trim())+'</option>').join('');$('workspaceSelect').value=active;}
function moveNavigation11(id,target,after=false){if(!editingHere())return;const a=nav11.querySelector('[data-tab="'+id+'"]'),b=nav11.querySelector('[data-tab="'+target+'"]');if(!a||!b||a===b)return;after?b.after(a):b.before(a);revision11.order=[...nav11.querySelectorAll('[data-tab]')].map(n=>n.dataset.tab);applyOrder11();dirtyWindow();scheduleWorkspaceCache();a.focus();}
for(const n of nav11.querySelectorAll('[data-tab]')){n.draggable=true;n.title='Drag to reorder. Alt + Up/Down moves this menu item.';n.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/tunelab-navigation',n.dataset.tab);});n.addEventListener('dragover',e=>e.preventDefault());n.addEventListener('drop',e=>{e.preventDefault();moveNavigation11(e.dataTransfer.getData('text/tunelab-navigation'),n.dataset.tab,e.clientY>n.getBoundingClientRect().top+n.offsetHeight/2);});n.addEventListener('keydown',e=>{if(e.altKey&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const other=e.key==='ArrowUp'?n.previousElementSibling:n.nextElementSibling;if(other)moveNavigation11(n.dataset.tab,other.dataset.tab,e.key==='ArrowDown');}});}
const bar11=document.createElement('div');bar11.className='panel actions revision-toolbar';bar11.innerHTML='<button id="updateAllProposals">Update All Proposals</button><button id="openProposalStatus" class="secondary">Proposal Status</button><button id="resetNavigation11" class="secondary">Reset Menu Order</button><output id="batchResult11" role="status"></output>';document.querySelector('header').after(bar11);
$('resetNavigation11').onclick=()=>{if(!editingHere())return;revision11.order=[...defaultOrder11];applyOrder11();dirtyWindow();scheduleWorkspaceCache();};
const status11=document.createElement('div');status11.className='panel';status11.innerHTML='<h2>Proposal Status</h2><p>Current means calculated for the saved inputs. Review checks and validation still apply before export.</p><div id="proposalStatus11"></div>';$('changes').prepend(status11);
function proposalRows11(){return ['mpr','command'].map(k=>{const b=state[k];return{name:k==='mpr'?'MPR':'Boost Command',status:b.proposal?(b.dirty?'Stale':'Current'):'Not Calculated',reason:b.proposal?.manual?'Manual refinements retained; update individually to replace.':b.dirty?'Source or controls changed; update required.':'Review units, protected cells and proposed differences.'};}).concat([{name:'AFM',status:!baseline?'Missing Evidence':!$('baselineConfirm').checked?'Calibration Unconfirmed':afmDirty?'Stale':afmResult?'Current':'Not Calculated',reason:afmResult?.cells.some(c=>c.manual)?'Manual airflow refinements retained.':'Matching baseline and reviewed mapping/units are required; validation never drives correction.'},{name:'Gear Limits',status:gearCurrent()?'Imported Table':'No Saved Table',reason:'Gear limits are imported or manually edited; no automatic proposal or factory values are supplied.'}]);}
function renderProposalStatus11(){ $('proposalStatus11').innerHTML='<table><thead><tr><th>Table</th><th>Status</th><th>Next Step</th></tr></thead><tbody>'+proposalRows11().map(r=>'<tr><th>'+r.name+'</th><td>'+r.status+'</td><td>'+r.reason+'</td></tr>').join('')+'</tbody></table>';}
function afmBlock11(){if(!baseline)return 'Select a baseline log.';if(!$('baselineConfirm').checked)return 'Confirm the installed baseline calibration.';const item=sessions.find(s=>s.id===$('baselineSession').value);const ready=RF.readiness(item,'afm');return ready.status==='Ready to review'?null:ready.issues.join(' ');}
const statusRows11Base=proposalRows11;proposalRows11=function(){const rows=statusRows11Base(),afm=rows.find(r=>r.name==='AFM'),block=afmBlock11();if(block){afm.status=baseline?'Prerequisites Needed':'Missing Evidence';afm.reason=block;}else if(afmResult&&!afmDirty&&afmResult.reviewEvidenceSignature!==afmEvidenceSignature()){afm.status='Stale Evidence';afm.reason='Evidence settings changed; analyze again before review.';}return rows;};
$('openProposalStatus').onclick=()=>{goPage('changes');renderProposalStatus11();status11.scrollIntoView({block:'start'});};
function updateAll11(){if(!editingHere())throw Error('Choose Edit in This Window before updating proposals.');clearTimeout(autoTimer);const prior=kind,reports=[];syncControls();try{for(const k of ['mpr','command']){const b=state[k];if(b.proposal?.manual){reports.push((k==='mpr'?'MPR':'Command')+': skipped — manual refinements preserved');continue;}try{switchKind(k,true);calculateBoost();reports.push((k==='mpr'?'MPR':'Command')+': updated');}catch(e){reports.push(k+': blocked — '+e.message);}}if(afmResult?.cells.some(c=>c.manual))reports.push('AFM: skipped — manual refinements preserved');else if(!baseline||!$('baselineConfirm').checked)reports.push('AFM: blocked — select a matching baseline and confirm its calibration');else if(!sessions.find(s=>s.id===$('baselineSession').value)?.profile?.confirmed)reports.push('AFM: blocked — review and confirm the baseline mapping/units');else{try{analyze();reports.push('AFM: updated; inspect support and validation');}catch(e){reports.push('AFM: blocked — '+e.message);}}reports.push('Gear limits: retained — imported/manual table');}finally{switchKind(prior,true);renderProposalStatus11();}$('batchResult11').textContent=reports.join(' · ');message('Proposal updates completed. Review the per-table results before export.');dirtyWindow();scheduleWorkspaceCache();return reports;}
$('updateAllProposals').onclick=action(updateAll11);
const typography11=document.createElement('div');typography11.className='formrow';typography11.innerHTML='<label>Font Family<select id="fontFamily11"><option value="system">System</option><option value="sans">Arial</option><option value="mono">Consolas</option></select></label><label>Font Weight<select id="fontWeight11"><option value="400">Regular</option><option value="600">Semibold</option><option value="700">Bold</option></select></label><label>Heading Capitalization<select id="headingCaps11"><option value="title">Title Case</option><option value="original">Original</option><option value="upper">Uppercase</option></select></label><button id="applyTypography11">Apply Typography</button><button id="resetTypography11" class="secondary">Inherit App Typography</button><p>Uses the appearance scope and selected page above. Heading case does not change table channels, units or user names. Table sizes use the existing sizing controls.</p>';$('appearanceSettings').append(typography11);
const headingOriginal11=new WeakMap();
function titleCase11(text){return text.replace(/\b[a-z][a-z]*\b/g,w=>w[0].toUpperCase()+w.slice(1));}
function applyTypography11(){for(const page of document.querySelectorAll('.page')){const p={...revision11.typography.app,...revision11.typography.pages[page.id]};page.style.fontFamily=families11[p.family];page.style.fontWeight=p.weight;for(const h of page.querySelectorAll('h2,h3')){if(h.closest('#custom'))continue;let original=headingOriginal11.get(h);if(!original||original.last!==h.textContent)original={text:h.textContent};const text=p.caps==='upper'?original.text.toUpperCase():p.caps==='title'?titleCase11(original.text):original.text;if(h.textContent!==text)h.textContent=text;headingOriginal11.set(h,{text:original.text,last:text});}}const p={...revision11.typography.app,...revision11.typography.pages[currentPage()]};if(currentPage()!=='custom')setText11($('pageTitle'),p.caps==='upper'?descriptions[currentPage()][0].toUpperCase():p.caps==='title'?titleCase11(descriptions[currentPage()][0]):descriptions[currentPage()][0]);for(const n of nav11.querySelectorAll('[data-tab]'))if(n.dataset.tab!=='custom')setText11(n.querySelector('span'),revision11.typography.app.caps==='upper'?descriptions[n.dataset.tab][0].toUpperCase():revision11.typography.app.caps==='original'?descriptions[n.dataset.tab][0]:titleCase11(descriptions[n.dataset.tab][0]));for(const o of $('workspaceSelect').options){const n=[...nav11.querySelectorAll('[data-tab]')].find(n=>n.dataset.tab===o.value);if(n)setText11(o,n.textContent.trim());}document.querySelector('header').style.fontFamily=families11[revision11.typography.app.family];nav11.style.fontFamily=families11[revision11.typography.app.family];}
function loadTypography11(){const p=currentPage()==='settings'&&$('appearanceScope').value==='app'?revision11.typography.app:{...revision11.typography.app,...revision11.typography.pages[appearanceTarget()]};$('fontFamily11').value=p.family;$('fontWeight11').value=p.weight;$('headingCaps11').value=p.caps;applyTypography11();}
$('applyTypography11').onclick=()=>{if(!editingHere())return;const p={family:$('fontFamily11').value,weight:$('fontWeight11').value,caps:$('headingCaps11').value};if($('appearanceScope').value==='page')revision11.typography.pages[appearanceTarget()]=p;else revision11.typography.app=p;loadTypography11();dirtyWindow();scheduleWorkspaceCache();};
$('resetTypography11').onclick=()=>{if(!editingHere())return;delete revision11.typography.pages[appearanceTarget()];loadTypography11();dirtyWindow();scheduleWorkspaceCache();};for(const id of ['appearanceScope','appearancePage'])$(id).addEventListener('change',loadTypography11);
const templates11=document.createElement('div');templates11.className='panel';templates11.innerHTML='<h2>Saved Workspace Layouts</h2><p>Save menu order, panel positions and your custom table views. Applying a layout does not replace calibration values, evidence or proposal edits. Main and detached layouts remain separate.</p><label>Layout Name<input id="layoutName11" maxlength="60" placeholder="AFM Review"></label><button id="saveLayout11">Save Layout</button><label>Saved Layout<select id="layoutChoice11"></select></label><button id="applySavedLayout11">Apply Layout</button><button id="deleteSavedLayout11" class="secondary">Delete Layout</button>';$('settings').append(templates11);
function renderLayouts11(){const selected=$('layoutChoice11').value;$('layoutChoice11').innerHTML=revision11.layouts.map(x=>'<option value="'+esc(x.name)+'">'+esc(x.name)+'</option>').join('');if(revision11.layouts.some(x=>x.name===selected))$('layoutChoice11').value=selected;}
$('saveLayout11').onclick=action(()=>{if(!editingHere())throw Error('Choose Edit in This Window first.');const name=$('layoutName11').value.trim();if(!name)throw Error('Enter a layout name.');for(const grid of gridDefaults.keys())saveGrid(grid.dataset.gridPage);const next={name,order:clone(revision11.order),panels:clone(panelLayouts),custom:clone(customWorkspace)};const i=revision11.layouts.findIndex(x=>x.name===name);if(i>=0)revision11.layouts[i]=next;else{if(revision11.layouts.length>=20)throw Error('Delete a layout before saving more than 20.');revision11.layouts.push(next);}renderLayouts11();$('layoutChoice11').value=name;dirtyWindow();scheduleWorkspaceCache();});
$('applySavedLayout11').onclick=action(()=>{if(!editingHere())throw Error('Choose Edit in This Window first.');const x=revision11.layouts.find(x=>x.name===$('layoutChoice11').value);if(!x)return;panelLayouts=validateGrid(clone(x.panels));customWorkspace=clone(x.custom);revision11.order=clone(x.order);applyOrder11();renderCustomWorkspace();restoreGrid();dirtyWindow();scheduleWorkspaceCache();message('Layout applied. Calibration tables and proposal edits retained.');});
$('deleteSavedLayout11').onclick=()=>{if(!editingHere())return;revision11.layouts=revision11.layouts.filter(x=>x.name!==$('layoutChoice11').value);renderLayouts11();dirtyWindow();scheduleWorkspaceCache();};
function validateRevision11(x){if(!x||x.schema!==1||!Array.isArray(x.order)||new Set(x.order).size!==x.order.length||x.order.some(id=>!defaultOrder11.includes(id))||!x.typography?.app||!x.typography.pages||!Array.isArray(x.layouts)||x.layouts.length>20)throw Error('Invalid v0.11 preferences');for(const p of [x.typography.app,...Object.values(x.typography.pages)])if(!families11[p.family]||!['400','600','700'].includes(p.weight)||!['title','original','upper'].includes(p.caps))throw Error('Invalid typography');for(const l of x.layouts){if(typeof l.name!=='string'||!l.name.trim()||l.name.length>60||!Array.isArray(l.order)||l.order.some(id=>!defaultOrder11.includes(id))||l.custom?.schema!==1||typeof l.custom.name!=='string'||l.custom.name.length>60||!Array.isArray(l.custom.cards)||l.custom.cards.length>100||l.custom.cards.some(c=>typeof c.id!=='string'||!/^[a-zA-Z0-9-]+$/.test(c.id)||typeof c.label!=='string'||c.label.length>200||typeof c.key!=='string'||!(c.key in customBoostChoices)&&!/^host:[a-zA-Z0-9_-]+$/.test(c.key)||!$(c.page)?.classList.contains('page')||c.page==='custom'))throw Error('Invalid saved layout');validateGrid(l.panels);}return clone(x);}
const revisionValidation11Base=validateRevision11;validateRevision11=function(x){if(!x?.typography?.pages||typeof x.typography.pages!=='object'||Array.isArray(x.typography.pages)||Object.keys(x.typography.pages).some(id=>!defaultOrder11.includes(id))||!Array.isArray(x.layouts)||new Set(x.layouts.map(l=>l.name)).size!==x.layouts.length||x.layouts.some(l=>!Array.isArray(l.order)||new Set(l.order).size!==l.order.length||!Array.isArray(l.custom?.cards)||new Set(l.custom.cards.map(c=>c.id)).size!==l.custom.cards.length))throw Error('Invalid v0.11 preference references');return revisionValidation11Base(x);};
const serialize11Base=serialize;serialize=function(){return{...serialize11Base(),uiRelease:'0.11',revision11:clone(revision11)};};
const load11Base=loadProject;loadProject=function(p){const next=validateRevision11(p.revision11??{schema:1,order:[],typography:{app:{family:'system',weight:'400',caps:'title'},pages:{}},layouts:[]});load11Base(p);revision11=next;applyOrder11();loadTypography11();renderLayouts11();renderGear();renderProposalStatus11();};
const activate11Base=activatePage;activatePage=function(){activate11Base();if(currentPage()==='gears')renderGear();loadTypography11();if(currentPage()==='changes')renderProposalStatus11();};
document.querySelector('footer').textContent='TuneLab v0.11 · Workbook-derived calculation engine · Local Files Only';document.querySelector('.brand small').textContent='LOCAL WORKSPACE · v0.11';
const changeReview11Base=renderChanges;renderChanges=function(){changeReview11Base();renderProposalStatus11();};
const style11=document.createElement('style');style11.textContent='.revision-toolbar{position:sticky;top:0;z-index:15;max-height:45vh;overflow:auto;background:var(--panel,#20232b);flex-wrap:wrap}.revision-toolbar output{flex:1;min-width:220px;font-size:12px}.page table{font-family:inherit;font-weight:inherit}.playback-global{width:100%;flex-wrap:wrap;gap:.4rem}.playback-global output{flex-basis:100%}nav [draggable=true]{cursor:grab}';document.head.append(style11);
applyOrder11();loadTypography11();renderLayouts11();renderProposalStatus11();

function setText11(node,text){if(node.textContent!==text)node.textContent=text;}
// Original navigation listeners captured the earlier activation function.
nav11.addEventListener('click',e=>{if(['boost','afm','logs','gears','changes','project'].includes(e.target.closest('[data-tab]')?.dataset.tab))activatePage();});
const summaryTypography11Base=refreshSetupSummaries;refreshSetupSummaries=function(){summaryTypography11Base();applyTypography11();};
