(function(root,factory){const api=factory(typeof module==='object'?require('./engine.js'):root.TuneLabEngine);if(typeof module==='object'&&module.exports)module.exports=api;else root.TuneLabReview=api;})(globalThis,(E)=>{
'use strict';
const finite=Number.isFinite;
function delta(a,b,percent=false){return !finite(a)||!finite(b)?null:percent?(a>1e-6?(b/a-1)*100:null):b-a;}
function extent(values,symmetric=false){let lo=Infinity,hi=-Infinity;for(const v of values)if(finite(v)){lo=Math.min(lo,v);hi=Math.max(hi,v);}if(lo===Infinity)return null;if(symmetric){const m=Math.max(Math.abs(lo),Math.abs(hi),1e-6);return[-m,m];}return[lo,hi];}
function color(value,range,palette='accessible',diverging=false){if(!finite(value)||!range)return null;const f=range[1]===range[0]?.5:Math.max(0,Math.min(1,(value-range[0])/(range[1]-range[0]))),stops=diverging?(palette==='warm'?[[83,111,143],[244,244,240],[177,67,57]]:[[67,104,157],[244,244,240],[181,107,26]]):(palette==='warm'?[[248,240,206],[217,102,54],[147,32,43]]:[[227,243,244],[79,159,178],[46,64,123]]),part=f<=.5?0:1,t=part===0?f*2:(f-.5)*2,rgb=stops[part].map((v,j)=>Math.round(v*(1-t)+stops[part+1][j]*t)),linear=rgb.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}),l=.2126*linear[0]+.7152*linear[1]+.0722*linear[2];return{background:`rgb(${rgb.join(',')})`,foreground:l>.179?'#111111':'#ffffff'};}
function settings(input){if(input===undefined)return{schema:1,mode:'values',palette:'accessible',scales:{}};if(!input||input.schema!==1||!['none','values','absolute','percent'].includes(input.mode)||!['accessible','warm'].includes(input.palette)||!input.scales||typeof input.scales!=='object'||Array.isArray(input.scales))throw Error('Invalid visual review settings');const out={schema:1,mode:input.mode,palette:input.palette,scales:{}};for(const[k,s]of Object.entries(input.scales)){if(!['boost-mpr','boost-command','airflow','gear'].includes(k)||!s||typeof s.key!=='string'||s.key.length>1000000||!s.ranges)throw Error('Invalid shading scale');for(const r of Object.values(s.ranges))if(r!==null&&(!Array.isArray(r)||r.length!==2||!r.every(finite)||r[0]>r[1]))throw Error('Invalid shading range');out.scales[k]=JSON.parse(JSON.stringify(s));}return out;}
// Positive interpolation weights only. At an exact breakpoint neighbouring
// cells with zero weight are not represented as evidence contributors.
function locations(table,rpm,axis){if(!finite(rpm)||!finite(axis))return[];try{const[rl,rh,rw]=E.bracket(table.rpm,rpm),[cl,ch,cw]=E.bracket(table.axis,axis),weights=new Map();for(const[r,a]of [[rl,1-rw],[rh,rw]])for(const[c,b]of [[cl,1-cw],[ch,cw]])if(a*b>1e-12)weights.set(r+':'+c,(weights.get(r+':'+c)??0)+a*b);return[...weights].map(([key,weight])=>{const[r,c]=key.split(':').map(Number);return{r,c,weight};});}catch{return[];}}
function boostLinks(table,rows,axisFor){return rows.map(row=>({row,cells:locations(table,row.rpm,axisFor(row))}));}
function afmLinks(table,samples,bandwidth,radius){return samples.map(sample=>({sample,cells:table.flatMap((cell,c)=>{const support=Math.abs(cell.hz-sample.hz)<=bandwidth,kernel=Math.abs(cell.hz-(Math.floor(sample.hz/50)*50+25))<=bandwidth*radius;return support||kernel?[{r:0,c,support,kernel}]:[];})}));}
function selectedLinks(links,rectangle){if(!rectangle)return links;return links.filter(x=>x.cells.some(p=>p.r>=rectangle.r0&&p.r<=rectangle.r1&&p.c>=rectangle.c0&&p.c<=rectangle.c1));}
function rangeRows(rows,start,end,key='time'){if(![start,end].every(finite)||start>end)throw Error('Evidence range start must not exceed end');return rows.filter(r=>finite(r[key])&&r[key]>=start&&r[key]<=end);}
function binRows(rows,bins,index){const b=bins[index];if(!b)return[];return rows.filter(r=>{const v=r.bp-r.cmd;return v>=b.min&&(index===bins.length-1?v<=b.max:v<b.max);});}
return{delta,extent,color,settings,locations,boostLinks,afmLinks,selectedLinks,rangeRows,binRows};
});
