'use strict';
let revision14={schema:1,height:null,approvals:{}};
const style14=document.createElement('style');style14.textContent=`.sessionbar{padding:8px!important}.revision-toolbar{padding:8px!important;gap:6px!important}.playback-global{padding:4px 0!important;gap:6px!important}.playback-global label{margin:0!important}#commandStatus13{padding:9px 12px;border:2px solid var(--accent);border-radius:6px;font-size:14px!important;background:var(--surface);font-weight:600}#status{border-left:5px solid var(--accent);padding:12px;font-weight:600}.position-row14{flex:0 0 100%;width:100%;display:block}.position-row14 input{width:100%}.log-resize14{width:100%;height:14px;cursor:ns-resize;padding:0;font-size:10px;touch-action:none}#logBox14{width:100%;min-height:0;max-height:260px;overflow:auto}.search14{width:min(700px,90vw);max-height:85vh;background:var(--surface);color:var(--text);border:2px solid var(--accent);border-radius:10px}.search14 input{width:100%}.search14 button{display:block;width:100%;text-align:left;margin:6px 0}.located14{outline:3px solid var(--accent)!important;outline-offset:3px}.drop14{padding:8px;border:1px dashed var(--accent);border-radius:5px}.drop14.drag14{outline:3px solid var(--accent)}.point14{display:block;padding:6px;border-left:3px solid var(--accent);font-variant-numeric:tabular-nums}.review-record14{padding:8px;border:1px solid var(--line);margin:8px 0}`;document.head.append(style14);
// A smaller default; explicit resizing is bounded only by the essential control rows.
const logBox14=document.createElement('div');logBox14.id='logBox14';playbackBar11.before(logBox14);logBox14.append(playbackBar11,tools12);
const positionLabel14=$('tracePosition12').closest('label');positionLabel14.className='position-row14';tools12.prepend(positionLabel14);
const resize14=document.createElement('button');resize14.className='log-resize14 secondary';resize14.textContent='↕ Resize Log Panel';resize14.setAttribute('aria-label','Resize Log Panel; arrow keys adjust height');logBox14.after(resize14);
function sizeLog14(height){revision14.height=height===null?null:Math.max(170,Math.min(800,height));logBox14.style.height=revision14.height===null?'':revision14.height+'px';logBox14.style.maxHeight=revision14.height===null?'260px':revision14.height+'px';}
resize14.onpointerdown=e=>{e.preventDefault();resize14.setPointerCapture(e.pointerId);const start=e.clientY,h=logBox14.getBoundingClientRect().height;const move=ev=>sizeLog14(h+ev.clientY-start),end=()=>{resize14.removeEventListener('pointermove',move);resize14.removeEventListener('pointerup',end);resize14.removeEventListener('pointercancel',end);dirtyWindow();scheduleWorkspaceCache();};resize14.addEventListener('pointermove',move);resize14.addEventListener('pointerup',end);resize14.addEventListener('pointercancel',end);};
resize14.onkeydown=e=>{if(['ArrowUp','ArrowDown','Home'].includes(e.key)){e.preventDefault();sizeLog14(e.key==='Home'?null:logBox14.getBoundingClientRect().height+(e.key==='ArrowUp'?-20:20));dirtyWindow();scheduleWorkspaceCache();}};
const status14Base=commandStatusUpdate13;commandStatusUpdate13=function(){status14Base();const ctx=traceContext12();const prefix=!ctx?'ⓘ No Recording':!ctx.unit?'⚠ Needs Setup':'ⓘ Command Trace';const text=commandStatus13.textContent;commandStatus13.textContent=prefix+' — '+text;};
// One-shot navigation preserves both the recording cursor and table selection.
function installTraceButtons14(){for(const host of document.querySelectorAll('#sourceGrid,#proposedGrid,#afmPreview,#afmGrid,#gearGrid,.custom-table-body')){if(host.previousElementSibling?.dataset.traceHost14===host.id&&host.id)continue;if(host.dataset.traceButton14)continue;host.dataset.traceButton14='true';const b=document.createElement('button');b.className='secondary';b.textContent='Go to Trace';b.dataset.traceHost14=host.id;b.onclick=()=>{if(visualReview.showTracking===false){message('Enable Table Tracing beside Log Playback first.','dirty');return;}const cells=[...host.querySelectorAll('.operating-cell')];if(!cells.length){message('No trace location in this table at the current row. Check Tracing Options and Help for channels, units and axes.','dirty');return;}for(const d of host.closest('.panel')?.querySelectorAll('details')??[])if(d.contains(host))d.open=true;const bounds=host.getBoundingClientRect(),visible=cells.every(c=>{const r=c.getBoundingClientRect();return r.left>=Math.max(0,bounds.left)&&r.right<=Math.min(innerWidth,bounds.right)&&r.top>=Math.max(0,bounds.top)&&r.bottom<=Math.min(innerHeight,bounds.bottom);});if(!visible)cells.slice().sort((a,b)=>(+b.dataset.traceWeight14||0)-(+a.dataset.traceWeight14||0))[0].scrollIntoView({block:'center',inline:'center',behavior:'instant'});message('Located '+cells.length+' current candidate cell(s). Log position and zoom retained.');};host.before(b);}}
const trace14Base=renderTrace11;renderTrace11=function(){trace14Base();installTraceButtons14();pointReadouts14();};renderOverlays=renderTrace11;
function nearest14(rows,key,value){return rows.reduce((a,r)=>Math.abs(r[key]-value)<Math.abs(a[key]-value)?r:a,rows[0]);}
function pointReadouts14(){const item=flowItem();if(!item)return;for(const plot of $('rawPlots').querySelectorAll('[data-raw-channel]')){let out=plot.querySelector('.point14');if(!out){out=document.createElement('output');out.className='point14';plot.append(out);}const h=chosenRawChannels()[+plot.dataset.rawChannel],ix=item.log.headers.indexOf(h);const show=(row,hover=false)=>{const value=item.log.data[row]?.[ix];out.textContent=(hover?'Inspecting':'Playback')+' · Row '+(row+1)+' · '+h+': '+(Number.isFinite(value)?fmt(value,4):'Unavailable')+' · native channel units';};show(rawCursor);const svg=plot.querySelector('svg');svg.onpointermove=e=>{const x=plotX14(svg,e,50,850,20,155);if(x===null)return;const t=+svg.dataset.x0+(x-50)/800*(+svg.dataset.x1-+svg.dataset.x0),rows=rawRows.filter(r=>r.time>=+svg.dataset.x0&&r.time<=+svg.dataset.x1);if(rows.length)show(nearest14(rows,'time',t).sourceIndex,true);};svg.onpointerleave=()=>show(rawCursor);}
const host=$('logChart'),svg=host.querySelector('svg');if(svg&&chartRows.length){let out=host.querySelector('.point14');if(!out){out=document.createElement('output');out.className='point14';host.append(out);}const show=(r,hover=false)=>{out.textContent=!r?'No selected sample':(hover?'Inspecting':'Playback')+' · Row '+(r.sourceIndex+1)+' · '+fmt(r.time,3)+' s'+($('showActual').checked?' · Actual '+fmt(r.bp,3)+' PSI':'')+($('showCommand').checked?' · Command '+fmt(r.cmd,3)+' PSI':'');};show(reviewRows[selectedFrame]);svg.onpointermove=e=>{const x=plotX14(svg,e,60,930,20,310),b=plotBounds();if(x!==null)show(nearest14(chartRows,b.x,b.xmin+(x-60)/870*(b.xmax-b.xmin)),true);};svg.onpointerleave=()=>show(reviewRows[selectedFrame]);}}
const raw14Base=renderRaw;renderRaw=function(){raw14Base();pointReadouts14();};const chart14Base=drawLogChart;drawLogChart=function(){chart14Base();pointReadouts14();};
// Search indexes labels lazily when opened. Choosing a result never executes it.
const searchButton14=document.createElement('button');searchButton14.id='searchApp14';searchButton14.className='secondary';searchButton14.textContent='Search App · Ctrl+K';bar11.prepend(searchButton14);
const search14=document.createElement('dialog');search14.className='search14';search14.innerHTML='<h2>Search App</h2><label>Find a Field, Table, or Function<input id="searchQuery14" type="search" autocomplete="off"></label><div id="searchResults14"></div><button id="closeSearch14" class="secondary">Close</button>';document.body.append(search14);let index14=[];
function label14(n){if(!n)return '';return(n.labels?.[0]?.textContent??n.getAttribute('aria-label')??n.querySelector?.('h2,h3')?.textContent??n.textContent??'').replace(/\s+/g,' ').trim().slice(0,150);}
function buildIndex14(){index14=[];for(const n of document.querySelectorAll('.page input:not([type=hidden]),.page select,.page button,.page textarea,.page h2,.page h3,.page table,.revision-toolbar button,.revision-toolbar input,.revision-toolbar select')){if(n.closest('dialog')||n.type==='file')continue;const page=n.closest('.page')?.id,path=page?document.querySelector('nav [data-tab="'+page+'"]')?.textContent.trim()??page:'Global Controls',label=label14(n)||label14(n.closest('.panel')??n.parentElement);if(label)index14.push({n,page,path,label});}for(const n of document.querySelectorAll('nav [data-tab]'))index14.push({n,page:n.dataset.tab,path:'Workspace',label:n.textContent.trim()});for(const [kind,label]of [['mpr','MPR · TC Maximum Pressure Ratio · Original and Proposed Tables'],['command','Boost Command · TC Boost Command · Original and Proposed Tables']])index14.push({n:$('sourceGrid'),page:'boost',kind,path:'Boost Tables',label});}
function locate14(entry){if(search14.open)search14.close();if(entry.page)goPage(entry.page);if(entry.kind)switchKind(entry.kind);if(detachedPage&&entry.page&&detachedPage!==entry.page){message('Opened '+entry.path+' in the main window.');return;}for(let n=entry.n.parentElement;n;n=n.parentElement){if(n.tagName==='DETAILS')n.open=true;if(n.classList.contains('page'))n.classList.add('showoptions');}if(entry.n.offsetParent===null){message('This control is unavailable. Open '+entry.path+' and complete its log or proposal setup.','dirty');return;}entry.n.scrollIntoView({block:'center',inline:'nearest'});entry.n.tabIndex=entry.n.tabIndex<0?-1:entry.n.tabIndex;entry.n.focus({preventScroll:true});entry.n.classList.add('located14');setTimeout(()=>entry.n.classList.remove('located14'),2500);}
function results14(){const q=$('searchQuery14').value.toLowerCase().trim(),terms=q.split(/\s+/);const matches=index14.filter(x=>terms.every(t=>(x.label+' '+x.path+' '+x.n.id).toLowerCase().includes(t))).slice(0,30);$('searchResults14').replaceChildren();for(const x of matches){const b=document.createElement('button');b.className='secondary';b.textContent=x.label+' — '+x.path;b.onclick=()=>locate14(x);$('searchResults14').append(b);}if(!matches.length)$('searchResults14').textContent='No matches. Try a table name, channel, or setting.';}
searchButton14.onclick=()=>{buildIndex14();search14.showModal();$('searchQuery14').value='';results14();$('searchQuery14').focus();};$('searchQuery14').oninput=results14;$('closeSearch14').onclick=()=>search14.close();search14.onkeydown=e=>{const buttons=[...$('searchResults14').querySelectorAll('button')];if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const i=buttons.indexOf(document.activeElement);buttons[Math.max(0,Math.min(buttons.length-1,i+(e.key==='ArrowDown'?1:-1)))]?.focus();}if(e.key==='Enter'&&document.activeElement===$('searchQuery14')){e.preventDefault();buttons[0]?.click();}};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();searchButton14.click();}});
// Reuse the import path, retaining raw text, duplicate checks, purpose and lease rules.
$('sessionFiles').accept='.csv,.txt';$('sessionFiles').closest('label').firstChild.textContent='Import CSV / TXT Datalogs';
async function importFiles14(files,output){if(!editingHere()){output.textContent='Import unavailable: choose Edit in This Window first.';return;}const reports=[];for(const f of files){try{if(!/\.(csv|txt)$/i.test(f.name))throw Error('Use an exported CSV or delimited TXT datalog; native KDLG is unsupported.');const text=await f.text(),duplicate=sessions.some(x=>x.text===text);await importSession(text,f.name);reports.push(f.name+': '+(duplicate?'duplicate selected':'imported'));}catch(e){reports.push(f.name+': '+e.message);}}output.textContent=reports.join(' · ');dirtyWindow();scheduleWorkspaceCache();}
for(const parent of [logBox14,$('library')]){const drop=document.createElement('div');drop.className='drop14';drop.textContent='Drop CSV / TXT Datalogs Here · or use Import CSV / TXT Datalogs';const out=document.createElement('output');out.setAttribute('role','status');drop.append(out);if(parent===logBox14)resize14.after(drop);else parent.append(drop);drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag14');};drop.ondragleave=()=>drop.classList.remove('drag14');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag14');importFiles14([...e.dataTransfer.files],out);};}
document.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('Files'))e.preventDefault();});document.addEventListener('drop',e=>{if(e.dataTransfer?.files.length){e.preventDefault();if(!e.target.closest('.drop14'))message('Drop files into the CSV / TXT Datalogs area beside playback or in Log Library.','dirty');}});
// Approval belongs to exact history content, separate from current proposal acknowledgement.
function signature14(entry){return JSON.stringify({before:entry.before,after:entry.after,disabled:entry.disabled});}
function approve14(entry){revision14.approvals[entry.id]={signature:signature14(entry),date:new Date().toISOString()};}
const changeDialog14=document.createElement('dialog');changeDialog14.className='search14';document.body.append(changeDialog14);
function goChange14(entry){goPage(entry.page);if(entry.page==='boost')switchKind(entry.kind);let delta=null;try{delta=entryDelta(entry);}catch{}changeDialog14.replaceChildren();const title=document.createElement('h2');title.textContent='Recorded Change · '+entry.table;changeDialog14.append(title);const note=document.createElement('p');note.textContent='Read-only history. These are this revision’s recorded values; the live table may have later edits. Navigating never restores a revision.';changeDialog14.append(note);if(delta?.length){for(const d of delta){const b=document.createElement('button');b.className='secondary';b.textContent=d.coordinate+': '+fmt(d.before,5)+' → '+fmt(d.after,5)+' · Locate Current Cell';b.onclick=()=>{changeDialog14.close();goPage(entry.page);if(entry.page==='boost')switchKind(entry.kind);const host=entry.page==='afm'?$('afmPreview'):entry.page==='gears'?$('gearGrid'):$('proposedGrid');const cell=host.querySelector('[data-er="'+d.r+'"][data-ec="'+d.c+'"]')??host.querySelector('tbody tr:nth-child('+(d.r+1)+') td:nth-child('+(d.c+2)+')');if(cell){cell.scrollIntoView({block:'center',inline:'center'});cell.classList.add('located14');setTimeout(()=>cell.classList.remove('located14'),2500);}else message('The recorded coordinate is unavailable in the current layout. Review its saved before / after values in Edit History.','dirty');};changeDialog14.append(b);}}else{const keys=Object.keys(entry.after.controls??{}).filter(k=>JSON.stringify(entry.before.controls?.[k])!==JSON.stringify(entry.after.controls[k]));for(const key of keys){const b=document.createElement('button');b.className='secondary';b.textContent=(label14($(key))||key)+': '+String(entry.before.controls?.[key])+' → '+String(entry.after.controls[key]);b.onclick=()=>{changeDialog14.close();const n=$(key);if(n)locate14({n,page:n.closest('.page')?.id,path:entry.page});};changeDialog14.append(b);}const pre=document.createElement('pre');pre.style.whiteSpace='pre-wrap';pre.textContent=JSON.stringify({before:entry.before.frame,after:entry.after.frame,beforeAirflow:entry.before.afmSource,afterAirflow:entry.after.afmSource},null,2);changeDialog14.append(pre);}const close=document.createElement('button');close.textContent='Close';close.onclick=()=>changeDialog14.close();changeDialog14.append(close);changeDialog14.showModal();}
function renderApprovals14(){for(const entry of journal){const article=$('history-'+entry.id);if(!article)continue;article.querySelector('.review-record14')?.remove();const record=revision14.approvals[entry.id],approved=record?.signature===signature14(entry),row=document.createElement('div');row.className='review-record14';const state=document.createElement('span');state.textContent=approved?'Approved · '+record.date:'Needs Review';const b=document.createElement('button');b.textContent=approved?'Clear Approval':'Approve Revision';b.disabled=!editingHere();b.onclick=()=>{if(!editingHere())return;if(approved)delete revision14.approvals[entry.id];else approve14(entry);renderApprovals14();dirtyWindow();scheduleWorkspaceCache();};const go=document.createElement('button');go.className='secondary';go.textContent='Go to Change';go.onclick=()=>goChange14(entry);row.append(state,b,go);article.append(row);}}
const history14Base=renderHistory;renderHistory=function(){history14Base();renderApprovals14();};
const approvals14=document.createElement('div');approvals14.className='panel';approvals14.innerHTML='<h2>Revision Approvals</h2><p>Approve the recorded Edit History operations in this project. New operations require their own approval. Approval does not apply a proposal or validate a tune.</p><button id="approveAll14">Approve All Revisions</button><button id="clearApprovals14" class="secondary">Clear All Revision Approvals</button><button id="openHistory14" class="secondary">Review Individual Revisions</button><output id="approvalStatus14"></output>';$('changes').prepend(approvals14);
$('approveAll14').onclick=()=>{if(!editingHere())return;for(const entry of journal)approve14(entry);$('approvalStatus14').textContent=journal.length+' recorded revisions approved. Later revisions are excluded.';renderHistory();dirtyWindow();scheduleWorkspaceCache();};$('clearApprovals14').onclick=()=>{if(!editingHere())return;revision14.approvals={};renderHistory();$('approvalStatus14').textContent='Revision approvals cleared; edits retained.';dirtyWindow();scheduleWorkspaceCache();};$('openHistory14').onclick=()=>goPage('history');
const serialize14Base=serialize;serialize=function(){return{...serialize14Base(),uiRelease:'0.14',revision14:clone(revision14)};};const load14Base=loadProject;loadProject=function(p){const next=p.revision14??{schema:1,height:null,approvals:{}};if(next.schema!==1||(next.height!==null&&(!Number.isFinite(next.height)||next.height<170||next.height>800))||!next.approvals||typeof next.approvals!=='object'||Array.isArray(next.approvals)||Object.values(next.approvals).some(x=>!x||typeof x.signature!=='string'||typeof x.date!=='string'))throw Error('Invalid v0.14 preferences or approvals');load14Base(p);revision14=clone(next);sizeLog14(next.height);renderHistory();};
document.querySelector('.brand small').textContent='LOCAL WORKSPACE · v0.14';document.querySelector('footer').textContent='TuneLab v0.14 · Local Files Only';renderTrace11();renderHistory();

const controls14Base=windowControls;windowControls=function(...args){controls14Base(...args);$('approveAll14').disabled=$('clearApprovals14').disabled=!editingHere();renderApprovals14();};

const traceCells14Base=traceCells11;traceCells11=function(host,cells){traceCells14Base(host,cells);for(const p of cells)host?.querySelector('tbody tr:nth-child('+(p.r+1)+') td:nth-child('+(p.c+2)+')')?.setAttribute('data-trace-weight14',String(p.weight??0));};
