'use strict';
const style13=document.createElement('style');style13.textContent=`main{max-width:none}.playback-global label{min-width:150px}#commandStatus13{flex-basis:100%;font-size:12px}.needs-units13{outline:2px solid var(--accent)}#rawReadout{white-space:normal;display:flex;flex-wrap:wrap;gap:8px}.raw-value13{padding:6px 9px;border:1px solid var(--line);border-radius:5px}.raw-row13{flex-basis:100%}.panel-grid[data-wide13="true"]{grid-template-columns:repeat(4,minmax(0,1fr))}`;document.head.append(style13);
// Reuse the existing selector and its reviewed selection path.
const activeLabel13=$('activeLog').closest('label');activeLabel13.firstChild.textContent='Active Log';playbackBar11.querySelector('strong').after(activeLabel13);
activeLabel13.after($('traceCommandUnit12').closest('label'));const commandStatus13=document.createElement('output');commandStatus13.id='commandStatus13';commandStatus13.setAttribute('role','status');$('traceReadout11').before(commandStatus13);
const active13Base=setActive;setActive=function(id){if(id!==activeSession){pauseRawPlayback('Paused to select a recording.');rawCursor=0;rawSourceRange=null;configItem12=null;visitCache12=null;}active13Base(id);loadPrefs12();renderTrace11();};
const unit13Base=commandUnit12;commandUnit12=function(item){const h=item.profile?.mapping.cmd??'',header=/\(bar\)/i.test(h)?'bar':/\(kpa\)/i.test(h)?'kpa':/\(psi\)/i.test(h)?'psi':null;return revision12.commandUnits[item.id]||header||unit13Base(item);};
// Make the unit problem observable even when advanced tracing details are closed.
function commandStatusUpdate13(){$('activeLog').disabled=!editingHere();$('traceCommandUnit12').disabled=!editingHere();const ctx=traceContext12(),p=ctx?.point(rawCursor),n=$('traceCommandUnit12');n.classList.toggle('needs-units13',!!ctx&&!ctx.unit);const label=ctx?.p.mapping.cmd||'unmapped';setText11(commandStatus13,!ctx?'Select an Active Log to trace tables.':!ctx.unit?'Command tracing needs pressure units for “'+label+'”. Choose Command Pressure Units beside playback; no units are guessed.':!p.boost.command.length?'Command: '+label+' · '+ctx.unit+' · no in-range location at this row. Open Tracing Options and Help for details.':'Command: '+label+' · '+ctx.unit+' · '+p.boost.command.length+' candidate cells.');}
let rangeItem13=null,ranges13=[];
function rowRanges13(item){if(rangeItem13===item)return ranges13;rangeItem13=item;ranges13=item.log.headers.map((h,j)=>{let lo=Infinity,hi=-Infinity;for(const row of item.log.data){const v=row[j];if(Number.isFinite(v)){lo=Math.min(lo,v);hi=Math.max(hi,v);}}return Number.isFinite(lo)?[lo,hi]:null;});return ranges13;}
const shadeLabel13=document.createElement('label');shadeLabel13.className='check';shadeLabel13.innerHTML='<input id="rawShading13" type="checkbox" checked>Color Original Data Row';$('rawReadout').before(shadeLabel13);const rangeNote13=document.createElement('p');rangeNote13.className='hint';rangeNote13.textContent='Color uses each channel’s minimum and maximum across the whole original recording, with Settings → Table Shading and Tracking → Palette. Hover for its range. Colors describe values, not warnings. Constant channels use the midpoint; missing values remain uncolored.';shadeLabel13.after(rangeNote13);
function paintRaw13(){const item=flowItem(),row=item?.log.data[rawCursor];if(!row)return;const ranges=rowRanges13(item),html=(rawSourceRange?'<span class="raw-row13">Bookmarked rows '+(rawSourceRange[0]+1)+'–'+(rawSourceRange[1]+1)+'; Show whole recording clears this restriction.</span>':'')+'<span class="raw-row13">Original data row '+(rawCursor+1)+'</span>'+item.log.headers.map((h,j)=>{const v=row[j],r=ranges[j],c=$('rawShading13').checked&&Number.isFinite(v)&&r?V.color(r[0]===r[1]?.5:v,r[0]===r[1]?[0,1]:r,visualReview.palette,false):null;return'<span class="raw-value13" title="'+esc(r?'Whole recording: '+fmt(r[0],4)+' to '+fmt(r[1],4)+' · original channel units':'No numeric readings')+'"'+(c?' style="background:'+c.background+';color:'+c.foreground+'"':'')+'>'+esc(h)+': '+(Number.isFinite(v)?fmt(v,4):'Unavailable')+'</span>';}).join('');if($('rawReadout').innerHTML!==html)$('rawReadout').innerHTML=html;}
$('rawShading13').onchange=()=>{paintRaw13();dirtyWindow();scheduleWorkspaceCache();};
const trace13Base=renderTrace11;renderTrace11=function(){trace13Base();commandStatusUpdate13();paintRaw13();};renderOverlays=renderTrace11;
const shading13Base=paintShading;paintShading=function(){shading13Base();paintRaw13();};
// Remove controls generated for sections that have since moved to another page.
function cleanOptions13(){for(const page of document.querySelectorAll('.page')){const b=page.querySelector('.options-toggle');if(!b)continue;const sections=[...page.querySelectorAll('.advanced-only')];if(!sections.length){b.remove();continue;}const names=sections.map(n=>n.querySelector('summary,h2,h3')?.textContent.trim()||'additional controls').join(', ');b.hidden=$('experience').value==='advanced';b.textContent=(page.classList.contains('showoptions')?'Hide ':'Show ')+names;b.setAttribute('aria-expanded',String(page.classList.contains('showoptions')));b.onclick=()=>{page.classList.toggle('showoptions');cleanOptions13();};}}
const appearance13Base=applyAppearance;applyAppearance=function(){appearance13Base();cleanOptions13();};cleanOptions13();
function columns13(card){return getComputedStyle(card.parentElement).gridTemplateColumns.split(' ').filter(Boolean).length;}
function place13(card){const count=columns13(card),span=Number(card.dataset.span);if(count===4&&card.dataset.column13){const c=Math.max(1,Math.min(5-span,+card.dataset.column13));card.style.gridColumn=c+' / span '+span;}else card.style.gridColumn='';}
const updateSpan13Base=updateSpan;updateSpan=function(card){updateSpan13Base(card);if(columns13(card)===4)for(const side of ['left','right'])card.querySelector('[data-grid-'+side+']').disabled=false;place13(card);};
const snap13Base=snapCard;snapCard=function(card,side){if(columns13(card)!==4)return snap13Base(card,side);const span=+card.dataset.span,current=+(card.dataset.column13||1);card.dataset.column13=String(Math.max(1,Math.min(5-span,current+(side==='left'?-span:span))));card.dataset.side='auto';card.style.width='';updateSpan(card);saveGrid(card.closest('[data-grid-page]').dataset.gridPage);};
const saveGrid13Base=saveGrid;saveGrid=function(page){saveGrid13Base(page);const p=panelLayouts[windowRole][page];for(const card of $(page).querySelectorAll('.panel-grid>.panel'))if(card.dataset.column13&&p.cards[card.dataset.gridId])p.cards[card.dataset.gridId].column13=+card.dataset.column13;};
const restoreGrid13Base=restoreGrid;restoreGrid=function(page=null){restoreGrid13Base(page);for(const grid of gridDefaults.keys()){if(page&&grid.dataset.gridPage!==page)continue;for(const card of grid.children){const c=panelLayouts[windowRole][grid.dataset.gridPage]?.cards?.[card.dataset.gridId]?.column13;if(c)card.dataset.column13=c;else delete card.dataset.column13;updateSpan(card);}}};
const validateGrid13Base=validateGrid;validateGrid=function(input){const result=validateGrid13Base(input);for(const role of ['main','detached'])for(const p of Object.values(result[role]))for(const c of Object.values(p.cards))if(c.column13!==undefined&&(!Number.isInteger(c.column13)||c.column13<1||c.column13>4))throw Error('Invalid panel column');return result;};
const drag13Base=startPanelDrag;startPanelDrag=function(e,card){if(columns13(card)!==4)return drag13Base(e,card);if(e.button!==0||card.classList.contains('panel-maximized'))return;e.preventDefault();const handle=e.currentTarget,grid=card.parentElement;handle.setPointerCapture(e.pointerId);let col=null,target=null;const ghost=document.createElement('div');ghost.className='grid-drop-slot';ghost.style.position='fixed';ghost.style.display='none';document.body.append(ghost);card.classList.add('dragging');const move=ev=>{const b=grid.getBoundingClientRect();col=ev.clientX<b.left||ev.clientX>b.right||ev.clientY<b.top||ev.clientY>b.bottom?null:Math.min(5-(+card.dataset.span),1+Math.floor((ev.clientX-b.left)/b.width*4));target=[...grid.children].find(n=>{const r=n.getBoundingClientRect();return n!==card&&ev.clientY>=r.top&&ev.clientY<=r.bottom;});ghost.style.display=col?'block':'none';if(col){const r=target?.getBoundingClientRect()??card.getBoundingClientRect();Object.assign(ghost.style,{left:(b.left+(col-1)*b.width/4)+'px',top:r.top+'px',width:(b.width/4*(+card.dataset.span)-18)+'px',height:Math.min(r.height,180)+'px'});ghost.textContent='Snap to column '+col+((+card.dataset.span)===2?'–'+(col+1):'');}};const finish=ev=>{if(ev.type!=='pointercancel'&&col){if(target){const r=target.getBoundingClientRect();if(ev.clientY>r.top+r.height/2)target.after(card);else target.before(card);}card.dataset.column13=col;card.dataset.side='auto';card.style.width='';updateSpan(card);saveGrid(grid.dataset.gridPage);}ghost.remove();card.classList.remove('dragging');handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',finish);handle.removeEventListener('pointercancel',finish);};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',finish);handle.addEventListener('pointercancel',finish);};
for(const card of document.querySelectorAll('.panel-grid>.panel')){const h=card.querySelector('.panel-handle'),old=h.onkeydown;h.onkeydown=e=>{if(columns13(card)===4&&e.altKey&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();snapCard(card,e.key==='ArrowLeft'?'left':'right');}else old?.(e);};}
const resize13=typeof ResizeObserver==='function'?new ResizeObserver(entries=>{for(const e of entries){const wide=String(e.contentRect.width>=1800);if(e.target.dataset.wide13!==wide)e.target.dataset.wide13=wide;for(const c of e.target.children)updateSpan(c);}}):{observe(){}};for(const grid of gridDefaults.keys())resize13.observe(grid);
const serial13Base=serialize;serialize=function(){return{...serial13Base(),uiRelease:'0.13',revision13:{schema:1,rawShading:$('rawShading13').checked}};};const load13Base=loadProject;loadProject=function(p){if(p.revision13!==undefined&&(p.revision13.schema!==1||typeof p.revision13.rawShading!=='boolean'))throw Error('Invalid v0.13 preferences');load13Base(p);$('rawShading13').checked=p.revision13?.rawShading??true;paintRaw13();cleanOptions13();};
document.querySelector('.brand small').textContent='LOCAL WORKSPACE · v0.13';document.querySelector('footer').textContent='TuneLab v0.13 · Local Files Only';renderTrace11();

const install13Base=installGridCard;installGridCard=function(card,page){install13Base(card,page);const h=card.querySelector('.panel-handle'),old=h.onkeydown;h.onkeydown=e=>{if(columns13(card)===4&&e.altKey&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();snapCard(card,e.key==='ArrowLeft'?'left':'right');}else old?.(e);};};
