'use strict';
let revision15={schema:1,collapsed:false,breaks:[],historyMode:'groups',customZoom:{}};
const css15=document.createElement('style');css15.textContent='.playback-hidden15{display:none!important}.chart-range15{fill:var(--accent);opacity:.22;pointer-events:none}.chart-actions15[hidden]{display:none}.chart-actions15{display:flex;gap:6px;flex-wrap:wrap;margin:6px 0}.history-group15{padding:12px;border:1px solid var(--line);margin:10px 0}.zoom-note15{font-size:12px;color:var(--muted)}';document.head.append(css15);
const playerControls15=document.createElement('div');playerControls15.className='actions';playerControls15.innerHTML='<button id="collapsePlayer15" class="secondary">Collapse Log Playback</button><button id="popPlayer15" class="secondary">Pop Out Log Playback</button>';logBox14.before(playerControls15);
function collapsePlayer15(value,persist=true){revision15.collapsed=value;for(const n of [logBox14,resize14,resize14.nextElementSibling])n?.classList.toggle('playback-hidden15',value);$('collapsePlayer15').textContent=value?'Expand Log Playback':'Collapse Log Playback';$('collapsePlayer15').setAttribute('aria-expanded',String(!value));if(!persist)return;dirtyWindow();if(typeof scheduleWorkspaceCache==='function')scheduleWorkspaceCache();}
$('collapsePlayer15').onclick=()=>collapsePlayer15(!revision15.collapsed);
// Group adjacent operations without deleting or changing the audit journal.
function reviewGroups15(){const groups=[];let current=null;for(const entry of journal){const prior=current?.entries.at(-1),gap=prior?Date.parse(entry.date)-Date.parse(prior.date):Infinity;if(!current||revision15.breaks.includes(prior.id)||entry.page!==prior.page||entry.kind!==prior.kind||!Number.isFinite(gap)||gap<0||gap>300000){current={entries:[],page:entry.page,kind:entry.kind};groups.push(current);}current.entries.push(entry);}return groups;}
function approved15(e){return revision14.approvals[e.id]?.signature===signature14(e);}
const historyMode15=document.createElement('div');historyMode15.className='actions';historyMode15.innerHTML='<button id="historyMode15" class="secondary">Show Full Edit History</button><button id="checkpoint15" class="secondary">Start New Review Checkpoint</button><label>Review Filter<select id="reviewFilter15"><option value="all">All Checkpoints</option><option value="pending">Needs Review</option></select></label><output id="groupCount15"></output>';$('historyList').before(historyMode15);
const history15Base=renderHistory;renderHistory=function(){if(revision15.historyMode==='operations'){history15Base();$('historyMode15').textContent='Show Review Checkpoints';$('groupCount15').textContent=journal.length+' individual operations; full audit retained.';return;}$('historyMode15').textContent='Show Full Edit History';const groups=reviewGroups15(),pending=$('reviewFilter15').value==='pending',shown=groups.filter(g=>!pending||g.entries.some(e=>!approved15(e)));$('groupCount15').textContent=groups.length+' checkpoints · '+journal.length+' operations · '+shown.length+' shown';$('historyList').replaceChildren();for(const group of shown.slice().reverse()){const entries=group.entries,n=entries.filter(approved15).length,card=document.createElement('article');card.className='history-group15';const title=document.createElement('h3');title.textContent=(document.querySelector('nav [data-tab="'+group.page+'"]')?.textContent.trim()??group.page)+' · '+entries[0].table;const summary=document.createElement('p');summary.textContent=entries.length+' operations · '+entries[0].date+' to '+entries.at(-1).date+' · '+(n===entries.length?'Approved':n?'Partially Approved ('+n+'/'+entries.length+')':'Needs Review');const approve=document.createElement('button');approve.textContent=n===entries.length?'Clear Checkpoint Approval':'Approve This Checkpoint';approve.disabled=!editingHere();approve.onclick=()=>{if(!editingHere())return;for(const e of entries)if(n===entries.length)delete revision14.approvals[e.id];else approve14(e);renderHistory();dirtyWindow();if(typeof scheduleWorkspaceCache==='function')scheduleWorkspaceCache();};const details=document.createElement('details');const label=document.createElement('summary');label.textContent='Inspect '+entries.length+' Recorded Changes';details.append(label);details.ontoggle=()=>{if(!details.open||details.dataset.built)return;details.dataset.built='true';for(const e of entries){const b=document.createElement('button');b.className='secondary';b.textContent=e.date+' · '+e.table+' · Go to Change';b.onclick=()=>goChange14(e);details.append(b);}};card.append(title,summary,approve,details);$('historyList').append(card);}if(!shown.length)$('historyList').textContent=pending?'No checkpoints need review.':'No editing operations yet.';};
$('historyMode15').onclick=()=>{revision15.historyMode=revision15.historyMode==='groups'?'operations':'groups';renderHistory();dirtyWindow();if(typeof scheduleWorkspaceCache==='function')scheduleWorkspaceCache();};$('reviewFilter15').onchange=renderHistory;$('checkpoint15').onclick=()=>{if(!editingHere())return;const last=journal.at(-1);if(last&&!revision15.breaks.includes(last.id))revision15.breaks.push(last.id);message('The next editing operation will start a new review checkpoint. Full history retained.');dirtyWindow();if(typeof scheduleWorkspaceCache==='function')scheduleWorkspaceCache();};
$('approveAll14').textContent='Approve All Review Checkpoints';$('openHistory14').textContent='Review Checkpoints';approvals14.querySelector('p').textContent='Related edits are grouped by workspace/table and pauses of more than five minutes, or an explicit checkpoint boundary. Approval covers the exact recorded operations shown in that checkpoint; later edits still need review. Full Edit History remains available.';
// Chart gestures use the SVG plot transform and distinguish click from dragging.
let range15=null;
function rawVisible15(){return rawRows.filter(r=>(!rawSourceRange||r.sourceIndex>=rawSourceRange[0]&&r.sourceIndex<=rawSourceRange[1])&&($('rawStart').value===''||r.time>=+$('rawStart').value)&&($('rawEnd').value===''||r.time<=+$('rawEnd').value));}
function zoomRange15(start,end,boost=false){if(!Number.isFinite(start)||!Number.isFinite(end)||start===end)return;range15=[Math.min(start,end),Math.max(start,end)];$('rawStart').value=range15[0];$('rawEnd').value=range15[1];if(boost){$('logStart').value=range15[0];$('logEnd').value=range15[1];drawLogChart();}renderRaw();dirtyWindow();if(typeof scheduleWorkspaceCache==='function')scheduleWorkspaceCache();}
function wholeChart15(boost){$('rawStart').value=$('rawEnd').value='';if(boost){$('logStart').value=$('logEnd').value='';drawLogChart();}renderRaw();message(rawSourceRange?'Chart zoom reset; the explicit bookmarked row restriction remains. Use the existing Show Whole Recording button to leave that bookmark.':'Showing the whole available recording.');}
function installChart15(svg,boost=false){if(!svg||svg.dataset.gestures15)return;svg.dataset.gestures15='true';const valid=()=>!boost||$('logXAxis').value==='time',bounds=()=>boost?{left:60,right:930,top:20,bottom:310,a:plotBounds().xmin,b:plotBounds().xmax}:{left:50,right:850,top:20,bottom:155,a:+svg.dataset.x0,b:+svg.dataset.x1};
svg.addEventListener('pointerdown',e=>{if(![0,2].includes(e.button)||e.shiftKey||!valid()||!editingHere())return;const b=bounds(),x=plotX14(svg,e,b.left,b.right,b.top,b.bottom);if(x===null)return;if(e.button===2)chartContextUntil17=0;e.preventDefault();e.stopImmediatePropagation();const start=b.a+(x-b.left)/(b.right-b.left)*(b.b-b.a),zoom=e.button===2;const matrix=svg.getScreenCTM()?.inverse(),prior=[$('rawStart').value,$('rawEnd').value,$('logStart').value,$('logEnd').value];let end=start,moved=false,previewFrame=0;chartDragging17=true;const rect=document.createElementNS('http://www.w3.org/2000/svg','rect');rect.setAttribute('class','chart-range15');rect.setAttribute('y',b.top);rect.setAttribute('height',b.bottom-b.top);if(zoom)svg.append(rect);const move=ev=>{const point=svg.createSVGPoint();point.x=ev.clientX;point.y=ev.clientY;const p=matrix?point.matrixTransform(matrix):null;if(!p)return;const px=Math.max(b.left,Math.min(b.right,p.x));moved ||= Math.abs(ev.clientX-e.clientX)>5;end=b.a+(px-b.left)/(b.right-b.left)*(b.b-b.a);if(zoom){rect.setAttribute('x',Math.min(x,px));rect.setAttribute('width',Math.abs(px-x));}else if(moved){svg.style.cursor='grabbing';const [a,z]=panLimits17(b.a,b.b,start-end);navHint.textContent='Panning: '+fmt(a,3)+'–'+fmt(z,3)+' s · Escape cancels';if(!previewFrame)previewFrame=requestAnimationFrame(()=>{previewFrame=0;panChart17(b.a,b.b,start-end,boost,true);});}};const cleanup=()=>{cancelAnimationFrame(previewFrame);previewFrame=0;chartDragging17=false;svg.style.cursor='';rect.remove();document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);document.removeEventListener('pointercancel',cancel);document.removeEventListener('keydown',key);navHint.textContent=gestureHint;};const cancel=()=>{cleanup();chartContextUntil17=Date.now()+500;if(!zoom&&moved){[$('rawStart').value,$('rawEnd').value,$('logStart').value,$('logEnd').value]=prior;if(boost)drawLogChart();renderRaw();}},key=ev=>{if(ev.key==='Escape')cancel();};const up=ev=>{move(ev);cleanup();if(moved){if(zoom){chartContextUntil17=Date.now()+500;suppressContext17=true;setTimeout(()=>suppressContext17=false,500);zoomRange15(start,end,boost);}else panChart17(b.a,b.b,start-end,boost);}else if(!zoom){const rows=boost?chartRows:rawVisible15(),axis=boost?plotBounds().x:'time';if(rows.length){pauseRawPlayback('Paused for point inspection.');moveRawCursor(nearest14(rows,axis,start).sourceIndex);}}};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up);document.addEventListener('pointercancel',cancel);document.addEventListener('keydown',key);},true);
const host=svg.parentElement,menu=document.createElement('div');menu.className='chart-actions15';menu.hidden=true;const actions=[['Show Whole Recording',()=>wholeChart15(boost)],['Zoom to Selected Range',()=>range15&&zoomRange15(...range15,boost)],['Center on Playback',()=>{const row=rawRows.find(r=>r.sourceIndex===rawCursor);if(!row){message('Choose timestamp units and an available sample first.','dirty');return;}const b=bounds(),span=Math.max(.1,b.b-b.a);zoomRange15(row.time-span/2,row.time+span/2,boost);}],['Copy Point Values',()=>{const item=flowItem();if(!item)return;copy('Original row '+(rawCursor+1)+'\n'+item.log.headers.map((h,j)=>h+': '+item.log.data[rawCursor][j]).join('\n'));}]];for(const [label,fn]of actions){const button=document.createElement('button');button.className='secondary';button.textContent=label;button.disabled=(label==='Zoom to Selected Range'&&!range15)||!valid();button.onclick=action(fn);menu.append(button);}host.append(menu);let suppressContext17=false;svg.oncontextmenu=e=>{if(!valid())return;e.preventDefault();if(suppressContext17||chartDragging17||Date.now()<chartContextUntil17)return;menu.hidden=false;menu.querySelector('button').focus();};const button=document.createElement('button');button.className='secondary';button.textContent='Chart Actions';button.onclick=()=>{menu.hidden=!menu.hidden;};host.append(button);const nav=document.createElement('div');nav.className='chart-nav17';const gestureHint=valid()?'Left-drag to pan · Right-drag to zoom · Left-click to inspect · Right-click for Chart Actions':'Choose Time as the horizontal axis to pan or drag-zoom';const navHint=document.createElement('span');navHint.textContent=gestureHint;for(const [label,fn]of [['Pan Earlier',()=>{const b=bounds();panChart17(b.a,b.b,-(b.b-b.a)*.25,boost);}],['Pan Later',()=>{const b=bounds();panChart17(b.a,b.b,(b.b-b.a)*.25,boost);}],['Zoom In',()=>{const b=bounds(),mid=(b.a+b.b)/2;zoomRange15(mid-(b.b-b.a)/4,mid+(b.b-b.a)/4,boost);}],['Full Datalog',()=>wholeChart15(boost)]]){const control=document.createElement('button');control.className='secondary';control.textContent=label;control.disabled=!valid();control.onclick=action(fn);nav.append(control);}nav.append(navHint);host.append(nav);}
const raw15Base=renderRaw;renderRaw=function(){raw15Base();for(const svg of $('rawPlots').querySelectorAll('svg'))installChart15(svg);};const chart15Base=drawLogChart;drawLogChart=function(){chart15Base();installChart15($('logChart').querySelector('svg'),true);};
// Existing table zoom steps; adjust scroll offsets around the selected cell.
const zoomSteps15=['0.75','1','1.25','1.5','2'];
function customZoom15(){for(const card of $('customGrid').querySelectorAll('.panel')){const host=card.querySelector('.custom-table-body');if(!host)continue;const z=+(revision15.customZoom[card.dataset.gridId]??1);host.classList.add('coordinated-zoom');for(const [name,value]of Object.entries({'--zoom-cell':14*z+'px','--zoom-header':14*z+'px','--zoom-row':8*z+'px','--zoom-col':10*z+'px','--zoom-min':64*z+'px'}))host.style.setProperty(name,value);host.style.fontSize=(14*z)+'px';for(const cell of host.querySelectorAll('td,th')){cell.style.fontSize=(14*z)+'px';cell.style.padding=(8*z)+'px '+(10*z)+'px';}}}
const wheelDelta15=new WeakMap();document.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey||e.altKey||!e.deltaY)return;const host=e.target.closest('#sourceGrid,#proposedGrid,#afmPreview,#gearGrid,.custom-table-body');if(!host?.querySelector('table'))return;const key=host.id||host.closest('.panel').dataset.gridId,isCustom=!host.id,current=String(isCustom?revision15.customZoom[key]??1:workflow.zoom[key]??1),j=zoomSteps15.indexOf(current),index=j<0?1:j,next=Math.max(0,Math.min(4,index+(e.deltaY<0?1:-1)));if(next===index)return;const previous=wheelDelta15.get(host)??0,delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?host.clientHeight:1),total=(Math.sign(previous)===Math.sign(delta)?previous:0)+delta;if(Math.abs(total)<40){wheelDelta15.set(host,total);e.preventDefault();return;}wheelDelta15.set(host,0);e.preventDefault();const selected=[...host.querySelectorAll('.selected')],anchor=selected[Math.floor(selected.length/2)]??e.target.closest('td,th')??host.querySelector('td'),before=anchor?.getBoundingClientRect();let scroller=host;while(scroller.parentElement&&scroller.scrollWidth<=scroller.clientWidth&&scroller.scrollHeight<=scroller.clientHeight)scroller=scroller.parentElement;if(isCustom){revision15.customZoom[key]=zoomSteps15[next];customZoom15();}else{workflow.zoom[key]=zoomSteps15[next];applyZoom();}const after=anchor?.getBoundingClientRect();if(before&&after){scroller.scrollLeft+=after.left+after.width/2-before.left-before.width/2;scroller.scrollTop+=after.top+after.height/2-before.top-before.height/2;}dirtyWindow();if(typeof scheduleWorkspaceCache==='function')scheduleWorkspaceCache();},{passive:false});
const custom15Base=renderCustomWorkspace;renderCustomWorkspace=function(){custom15Base();customZoom15();};
// Dedicated remote controller. The app owns the only playback timer.
let playerWindow15=null,playerToken15=null,playerProject15=null;
function playerState15(){return{type:'state15',token:playerToken15,project:windowProject,session:activeSession,logs:sessions.map(x=>({id:x.id,name:x.name})),index:rawCursor,max:Math.max(0,(flowItem()?.log.data.length??1)-1),playing:rawPlaying,allowed:editingHere(),speed:$('rawSpeed').value,unit:$('traceCommandUnit12').value,status:$('positionReadout12').textContent+' · '+commandStatus13.textContent};}
function sendPlayer15(){if(playerWindow15&&!playerWindow15.closed){playerProject15=windowProject;playerWindow15.postMessage(playerState15(),'*');}else if(playerWindow15){playerWindow15=null;collapsePlayer15(false);}}
$('popPlayer15').disabled=!!detachedPage;$('popPlayer15').onclick=()=>{if(detachedPage)return;if(playerWindow15&&!playerWindow15.closed){playerWindow15.focus();return;}playerToken15=workspaceToken();playerProject15=windowProject;playerWindow15=window.open('playback15.html?token='+encodeURIComponent(playerToken15),'TuneLabPlayback15','popup,width=820,height=470');if(!playerWindow15){message('Popup blocked. Allow popups for TuneLab or use the main Log Playback controls.','dirty');return;}collapsePlayer15(true);};
window.addEventListener('message',e=>{const m=e.data;if(e.source!==playerWindow15||!m||m.token!==playerToken15)return;if(m.type==='ready15'){sendPlayer15();return;}if(m.type!=='command15'||m.project!==windowProject||m.session!==activeSession)return;if(m.action==='dock'){playerWindow15.close();playerWindow15=null;collapsePlayer15(false);return;}if(!editingHere()){sendPlayer15();return;}if(m.action==='play')$('tracePlay11').click();else if(m.action==='step'&&['first','last',-1,1].includes(m.value))stepRaw(m.value);else if(m.action==='seek'&&Number.isInteger(m.value)&&m.value>=0&&m.value<(flowItem()?.log.data.length??0)){pauseRawPlayback('Paused for popout scrubbing.');moveRawCursor(m.value);}else if(m.action==='speed'&&['0.25','0.5','1','2','4'].includes(m.value)){$('traceSpeed11').value=m.value;$('traceSpeed11').onchange();}else if(m.action==='active'&&sessions.some(x=>x.id===m.value))setActive(m.value);else if(m.action==='unit'&&['','bar','kpa','psi'].includes(m.value)){$('traceCommandUnit12').value=m.value;$('traceCommandUnit12').dispatchEvent(new Event('change'));}sendPlayer15();});
const playerHeartbeat15=setInterval(sendPlayer15,250);window.addEventListener('beforeunload',()=>{if(playerWindow15&&!playerWindow15.closed)playerWindow15.postMessage({type:'disconnect15',token:playerToken15},'*');});
const serialize15Base=serialize;serialize=function(){return{...serialize15Base(),uiRelease:'0.15',revision15:clone(revision15)};};const load15Base=loadProject;loadProject=function(p){const r=p.revision15??{schema:1,collapsed:false,breaks:[],historyMode:'groups',customZoom:{}};if(r.schema!==1||typeof r.collapsed!=='boolean'||!Array.isArray(r.breaks)||r.breaks.some(x=>typeof x!=='string')||!['groups','operations'].includes(r.historyMode)||!r.customZoom||typeof r.customZoom!=='object'||Array.isArray(r.customZoom)||Object.values(r.customZoom).some(x=>!zoomSteps15.includes(String(x))))throw Error('Invalid v0.15 preferences');load15Base(p);revision15=clone(r);range15=null;collapsePlayer15(r.collapsed);renderHistory();customZoom15();};
document.querySelector('.brand small').textContent='LOCAL WORKSPACE · v0.15';document.querySelector('footer').textContent='TuneLab v0.15 · Local Files Only';renderHistory();collapsePlayer15(false,false);renderRaw();drawLogChart();
