'use strict';
let revision12={schema:1,range:'whole',metric:'count',showVisits:true,showMost:true,commandUnits:{}},visitCache12=null,configItem12=null,configKey12='',navigation12=false;
const tools12=document.createElement('div');tools12.className='actions playback-global';tools12.innerHTML='<label style="flex:1">Playback Position<input id="tracePosition12" type="range" min="0" max="0" value="0" step="1" aria-label="Playback position in original rows"></label><output id="positionReadout12"></output><details><summary>Tracing Options and Help</summary><div class="formrow"><label>Command Pressure Units<select id="traceCommandUnit12"><option value="">Use Log/Header Units</option><option value="bar">Absolute bar</option><option value="kpa">Absolute kPa</option><option value="psi">KTuner / exported PSI representation</option></select></label><label>Visit Range<select id="visitRange12"><option value="whole">Whole Log</option><option value="selected">Selected Playback Range</option></select></label><label>Visit Metric<select id="visitMetric12"><option value="count">Sample Count</option><option value="seconds">Time Spent · weighted seconds</option></select></label><label class="check"><input id="showVisits12" type="checkbox" checked>Show Visit Heatmap</label><label class="check"><input id="showMost12" type="checkbox" checked>Highlight Most Visited</label><button id="traceMapping12" class="secondary">Review Channel Mapping</button></div><p>Blue marker: current recorded row. Purple shading: visits in the chosen range. Purple border: maximum (ties included). Dotted coverage/counts use analysis filters independently. Visits count each original row once, regardless of replay. Time is split across interpolated cells; gaps over 1 second, resets and missing timestamps are excluded. Candidate locations do not prove ECU control influence.</p><div id="traceWhy12"></div><div id="visitSummary12"></div></details>';playbackBar11.after(tools12);
const saveMenu12=document.createElement('button');saveMenu12.id='saveMenu12';saveMenu12.className='secondary';saveMenu12.textContent='Save Menu Order';$('resetNavigation11').before(saveMenu12);saveMenu12.onclick=action(async()=>{if(!editingHere())throw Error('Choose Edit in This Window.');revision11.order=[...nav11.querySelectorAll('[data-tab]')].map(n=>n.dataset.tab);dirtyWindow();await persistWorkspaceCache();message(workflow.storageEnabled?'Menu order saved to this browser workspace and included in project JSON. Download JSON before changing folders.':'Menu order retained in this project. Browser storage is disabled; download project JSON to preserve it.');});
function commandUnit12(item){const h=item.profile?.mapping.cmd??'',override=revision12.commandUnits[item.id];return override||item.profile?.units.pressure||(/\(bar\)/i.test(h)?'bar':/\(kpa\)/i.test(h)?'kpa':/\(psi\)/i.test(h)?'psi':null);}
function traceContext12(){const item=flowItem();if(!item)return null;const p=item.profile??F.inspect(item.log),ids=Object.fromEntries(['rpm','hz','gear','cmd'].map(k=>[k,item.log.headers.indexOf(p.mapping[k])])),paId=item.log.headers.indexOf(p.mapping.pa||'PA'),unit=commandUnit12(item),gearTable=gearCurrent()?displayGear():null;
 return{item,p,ids,unit,gearTable,point(index){const raw=item.log.data[index],get=k=>ids[k]>=0?raw[ids[k]]:NaN,rpm=get('rpm'),hz=get('hz'),gear=get('gear'),loggedPa=paId>=0?raw[paId]:NaN,hasPa=Number.isFinite(loggedPa)&&loggedPa>0&&loggedPa<2,pa=hasPa?loggedPa:+$('referencePa').value,cmdRaw=get('cmd'),cmd=unit&&Number.isFinite(cmdRaw)?W.pressure(cmdRaw,unit==='psi'?'ktuner':unit,'ktuner',pa):NaN,boost={mpr:V.locations(state.mpr.source,rpm,pa),command:V.locations(state.command.source,rpm,cmd)},afm=[],gearCells=[];
 if(Number.isFinite(hz))try{const[lo,hi,w]=E.bracket(state.afm.map(x=>x.hz),hz);if(1-w>1e-12)afm.push({r:0,c:lo,weight:1-w});if(w>1e-12)afm.push({r:0,c:hi,weight:w});}catch{}
 if(gearTable&&Number.isInteger(gear)){const gi=gearTable.gears.findIndex(g=>g.gear===gear),g=gearTable.gears[gi];if(g&&(gearTable.format==='hondata'||gear===+$('selectedGear').value)){const axis=gearTable.format==='hondata'?0:hasPa?loggedPa:+$('gearPa').value;gearCells.push(...V.locations({rpm:g.rpm,axis:g.axis??[0]},rpm,axis).map(p=>gearTable.format==='hondata'?{r:gi,c:p.r,weight:p.weight}:p));}}
 return{item,rpm,hz,gear,pa,hasPa,cmd,boost,afm,gearCells};}};
}
traceState11=function(){const ctx=traceContext12();if(!ctx||!ctx.item.log.data[rawCursor])return null;const p=ctx.point(rawCursor);return{...p,afm:p.afm.map(c=>c.c)};};
function visits12(){const ctx=traceContext12();if(!ctx)return null;const key=JSON.stringify([revision12.range,$('rawTimeChannel').value,$('rawTimeUnit').value,revision12.range==='selected'?[$('rawStart').value,$('rawEnd').value,rawSourceRange]:null,ctx.p.mapping,ctx.unit,state.mpr.source.rpm,state.mpr.source.axis,state.command.source.rpm,state.command.source.axis,state.afm.map(c=>c.hz),ctx.gearTable?.gears.map(g=>[g.gear,g.rpm,g.axis]),$('selectedGear').value,$('referencePa').value,$('gearPa').value]);if(visitCache12?.item===ctx.item&&visitCache12.key===key)return visitCache12.result;
 let rows=[];try{rows=revision12.range==='selected'?playbackRows():RF.rows(ctx.item.log,$('rawTimeChannel').value,$('rawTimeUnit').value);}catch{}
 const points=new Map();const point=i=>{if(!points.has(i))points.set(i,ctx.point(i));return points.get(i);};const result=Object.fromEntries(['mpr','command','afm','gear'].map(k=>[k,TuneLabVisits.summarize(rows,i=>{const p=point(i);return k==='afm'?p.afm:k==='gear'?p.gearCells:p.boost[k];})]));visitCache12={item:ctx.item,key,result};return result;
}
function paintVisit12(host,summary,horizontal=false){if(!host)return;const max=TuneLabVisits.maxima(summary,revision12.metric);for(const cell of summary.cells){const targets=horizontal?[...host.querySelectorAll('table tbody tr')].map(r=>r.cells[cell.c+1]).filter(Boolean):[host.querySelector('tbody tr:nth-child('+(cell.r+1)+') td:nth-child('+(cell.c+2)+')')].filter(Boolean);for(const n of targets){if(revision12.showVisits){n.classList.add('visit-cell12');n.style.setProperty('--visit-alpha12',String(max.max?Math.min(.75,.12+cell[revision12.metric]/max.max*.63):.12));}if(revision12.showMost&&max.max>0&&Math.abs(cell[revision12.metric]-max.max)<1e-9)n.classList.add('most-visit12');n.dataset.visit12=cell.count+' samples / '+cell.seconds.toFixed(3)+' weighted seconds';}}}
function renderVisits12(){document.querySelectorAll('.visit-cell12,.most-visit12').forEach(n=>{n.classList.remove('visit-cell12','most-visit12');delete n.dataset.visit12;});const stats=visits12();if(!stats){$('visitSummary12').textContent='Select a recording to summarize visits.';return;}paintVisit12($('sourceGrid'),stats[kind]);paintVisit12($('proposedGrid'),stats[kind]);paintVisit12($('afmPreview'),stats.afm,true);paintVisit12($('gearGrid'),stats.gear);for(const card of customWorkspace.cards){const host=[...$('customGrid').children].find(n=>n.dataset.gridId==='custom-'+card.id)?.querySelector('.custom-table-body');if(card.key in customBoostChoices)paintVisit12(host,stats[card.key.split('-')[0]]);else if(card.key==='host:afmPreview')paintVisit12(host,stats.afm,true);else if(card.key==='host:gearGrid')paintVisit12(host,stats.gear);}
 const html='<table><thead><tr><th>Table</th><th>Most Visited Location</th><th>Mapped / Unmapped Rows</th></tr></thead><tbody>'+Object.entries(stats).map(([k,s])=>{const m=TuneLabVisits.maxima(s,revision12.metric);return'<tr><th>'+k.toUpperCase()+'</th><td>'+esc(m.cells.length?m.cells.slice(0,12).map(c=>visitLabel12(k,c)).join('; ')+(m.cells.length>12?' (and '+(m.cells.length-12)+' tied locations)':'')+' · '+m.max.toFixed(revision12.metric==='count'?0:3)+' '+(revision12.metric==='count'?'samples':'weighted seconds'):'No mapped visits')+'</td><td>'+s.mapped+' / '+s.unmapped+' · '+s.excludedIntervals+' excluded time intervals</td></tr>';}).join('')+'</tbody></table>';if($('visitSummary12').innerHTML!==html)$('visitSummary12').innerHTML=html;
}
function visitLabel12(k,c){if(k==='afm')return state.afm[c.c]?.hz+' Hz';if(k==='gear'){const t=displayGear(),g=t.format==='hondata'?t.gears[c.r]:t.gears.find(g=>g.gear===+$('selectedGear').value);return t.format==='hondata'?'Gear '+g?.gear+' / '+g?.rpm[c.c]+' RPM':'Gear '+g?.gear+' / '+g?.rpm[c.r]+' RPM / '+g?.axis[c.c]+' absolute bar PA';}const t=state[k].source;return t.rpm[c.r]+' RPM / '+t.axis[c.c]+(k==='mpr'?' absolute bar PA':' PSI command representation');}
function whyTrace12(){const ctx=traceContext12();if(!ctx){$('traceWhy12').textContent='Select a log. Then review mappings and timestamp units.';return;}const p=ctx.point(rawCursor),reasons=[];for(const k of ['mpr','command','afm','gear']){const cells=k==='afm'?p.afm:k==='gear'?p.gearCells:p.boost[k];if(cells.length)continue;let why;if(k==='command')why=ctx.ids.cmd<0?'Command channel is unmapped.':!ctx.unit?'Command pressure units are unknown; select them above.':!Number.isFinite(p.cmd)||!Number.isFinite(p.rpm)?'Missing numeric RPM or command at this row.':'RPM or converted command is outside this table’s axes.';else if(k==='mpr')why=!Number.isFinite(p.rpm)?'RPM is unmapped or missing.':'RPM or atmospheric reference is outside the axes.';else if(k==='afm')why=ctx.ids.hz<0?'AFM frequency is unmapped.':!Number.isFinite(p.hz)?'Frequency is missing at this row.':'Frequency is outside the curve.';else why=!ctx.gearTable?'No gear calibration is saved.':!Number.isInteger(p.gear)?'Gear is unmapped or missing.':!ctx.gearTable.gears.some(g=>g.gear===p.gear)?'Recorded gear is absent from the imported table.':ctx.gearTable.format==='ktuner'&&p.gear!==+$('selectedGear').value?'Recorded gear differs from displayed gear.':'RPM or atmosphere is outside the gear table.';reasons.push(k.toUpperCase()+': '+why);}const text=reasons.join(' · ')||'All four calibration locations can be mapped at this row.';if($('traceWhy12').textContent!==text)$('traceWhy12').textContent=text;
}
const renderTrace12Base=renderTrace11;renderTrace11=function(){renderTrace12Base();const item=flowItem(),ix=item?.log.headers.indexOf($('rawTimeChannel').value),raw=item?.log.data[rawCursor],time=raw&&ix>=0?raw[ix]/($('rawTimeUnit').value==='ms'?1000:1):NaN,p=traceState11();$('tracePosition12').max=Math.max(0,(item?.log.data.length??1)-1);$('tracePosition12').value=rawCursor;$('tracePosition12').disabled=!item||!editingHere();setText11($('positionReadout12'),item?'Row '+(rawCursor+1)+' · '+fmt(time,3)+' s · '+fmt(p?.rpm,0)+' RPM · Gear '+fmt(p?.gear,0):'No recording');whyTrace12();renderVisits12();};renderOverlays=renderTrace11;
$('tracePosition12').oninput=()=>{if(!editingHere())return;const index=+$('tracePosition12').value;pauseRawPlayback('Paused for scrubbing.');moveRawCursor(index);};$('traceMapping12').onclick=()=>goPage('library');
for(const [id,key]of [['visitRange12','range'],['visitMetric12','metric'],['showVisits12','showVisits'],['showMost12','showMost']])$(id).onchange=()=>{if(!editingHere())return;revision12[key]=$(id).type==='checkbox'?$(id).checked:$(id).value;renderTrace11();dirtyWindow();scheduleWorkspaceCache();};$('traceCommandUnit12').onchange=()=>{if(!editingHere()||!flowItem())return;const unit=$('traceCommandUnit12').value;if(unit)revision12.commandUnits[activeSession]=unit;else delete revision12.commandUnits[activeSession];renderTrace11();dirtyWindow();scheduleWorkspaceCache();};
function loadPrefs12(){for(const[id,key]of [['visitRange12','range'],['visitMetric12','metric'],['showVisits12','showVisits'],['showMost12','showMost']])if($(id).type==='checkbox')$(id).checked=revision12[key];else $(id).value=revision12[key];$('traceCommandUnit12').value=revision12.commandUnits[activeSession]??'';}
const configure12Base=configureRaw;configureRaw=function(){const item=flowItem(),key=JSON.stringify([item?.purpose,item?.profile?.mapping,item?.profile?.units]);if(item===configItem12&&key===configKey12&&rawRows.length){renderTrace11();return;}configure12Base();configItem12=item;configKey12=key;loadPrefs12();};
// Automatic legacy inspection refreshes must not move the raw playback cursor.
inspectFrame=function(...args){inspectTrace11Base(...args);if(!rawPlaying&&!navigation12&&document.activeElement?.id==='frameSlider'){const row=reviewRows[selectedFrame];if(row)moveRawCursor(row.sourceIndex);}};
nav11.addEventListener('click',()=>{renderTrace11();loadPrefs12();});nav11.addEventListener('click',()=>{navigation12=true;queueMicrotask(()=>navigation12=false);},true);
const boost12Base=renderBoost;renderBoost=function(){boost12Base();renderTrace11();};const afm12Base=renderAfm;renderAfm=function(){afm12Base();renderTrace11();};
const parseGear12Base=W.parseGear;W.parseGear=function(...args){if(args[1]==='ktuner'&&(!Number.isInteger(args[3])||args[3]<1||args[3]>6))throw Error('Civic Si gear number must be a whole number from 1–6.');let g;try{g=parseGear12Base(...args);}catch(e){if(/Gear must/i.test(e.message))throw Error('Civic Si gear rows must be whole numbers 1–6. Check the imported format and first column; paste calibration tables, not a datalog.');throw e;}if(g.gears.some(x=>x.gear>6))throw Error('Current Civic Si imports support gears 1–6.');return g;};$('gearNumber').max='6';
const serial12Base=serialize;serialize=function(){return{...serial12Base(),uiRelease:'0.12',revision12:clone(revision12)};};const load12Base=loadProject;loadProject=function(p){const x=p.revision12??{schema:1,range:'whole',metric:'count',showVisits:true,showMost:true,commandUnits:{}};if(x.schema!==1||!['whole','selected'].includes(x.range)||!['count','seconds'].includes(x.metric)||typeof x.showVisits!=='boolean'||typeof x.showMost!=='boolean'||!x.commandUnits||typeof x.commandUnits!=='object'||Array.isArray(x.commandUnits)||Object.values(x.commandUnits).some(v=>!['bar','kpa','psi'].includes(v)))throw Error('Invalid v0.12 tracing preferences');load12Base(p);revision12=clone(x);visitCache12=null;loadPrefs12();renderTrace11();};
const style12=document.createElement('style');style12.textContent='.visit-cell12{background-image:linear-gradient(rgba(150,90,210,var(--visit-alpha12)),rgba(150,90,210,var(--visit-alpha12)))}.most-visit12{box-shadow:inset 0 0 0 2px #c78bff}.operating-cell{outline:2px solid #56bbff!important;outline-offset:-2px}.playback-global details{width:100%}';document.head.append(style12);document.querySelector('footer').textContent='TuneLab v0.12 · Local Files Only';document.querySelector('.brand small').textContent='LOCAL WORKSPACE · v0.12';loadPrefs12();renderTrace11();

const gearCurrent12Base=gearCurrent;gearCurrent=function(){const g=gearCurrent12Base();if(!g)return null;const gears=g.gears.filter(x=>x.gear>=1&&x.gear<=6);return gears.length?{...g,gears}:null;};
const gearNotice12=document.createElement('p');gearNotice12.className='hint';$('gearGrid').before(gearNotice12);
const gearRender12Base=renderGear;renderGear=function(){gearRender12Base();const extra=gearCurrent12Base()?.gears.filter(x=>x.gear>6).length??0;gearNotice12.textContent=extra?'Civic Si view and exports show gears 1–6. '+extra+' legacy gear rows remain in the project backup; they are not deleted.':gearCurrent12Base()?.userTemplate?'User-supplied Hondata starting template · 3.00 absolute bar · gears 1–6. Confirm against your installed calibration before use.':'Civic Si gear calibration: gears 1–6 only. A datalog does not supply calibration tables.';renderTrace11();};
document.addEventListener('mouseover',e=>{const n=e.target.closest('[data-visit12]');if(n&&n.dataset.visitBase12===undefined){n.dataset.visitBase12=n.title;n.title+='\nRecorded visits: '+n.dataset.visit12;}});document.addEventListener('mouseout',e=>{const n=e.target.closest('[data-visit-base12]');if(n){n.title=n.dataset.visitBase12;delete n.dataset.visitBase12;}});
renderGear();
