'use strict';
// Interface-only preferences; calibration values and evidence signatures are preserved.
let revision16={schema:1,compact:true};
const css16=document.createElement('style');css16.textContent=`
.revision-toolbar{align-items:center!important;position:relative!important;max-height:none!important;overflow:visible!important}.revision-toolbar output{min-width:0!important}.revision-toolbar button{padding:7px 9px}.revision-toolbar>.setup16{padding:3px;margin:0}.revision-toolbar .drop14{border:0;padding:3px}.revision-toolbar .drop14:after{content:' — click to import'}#logBox14.compact16 #traceFirst11,#logBox14.compact16 #traceLast11{display:none}#logBox14.compact16 label:has(#traceCommandUnit12):not(:has(.needs-units13)){display:none}#logBox14.compact16 .playback-global>output{margin:0}#batchResult11:empty{display:none} .revision-toolbar>.actions{display:contents}
#logBox14.compact16{height:auto!important;max-height:none!important;overflow:visible}#logBox14.compact16 .playback-global{display:flex;flex-wrap:wrap}#logBox14.compact16 #positionReadout12{display:none}#logBox14.compact16 .position-row14{margin:0}#logBox14.compact16 label{font-size:12px;min-width:0}#logBox14.compact16 #traceReadout11{display:none}#logBox14.compact16 #commandStatus13{display:block;border:0!important;padding:2px!important;font-size:12px!important}#logBox14.compact16 details{display:none}#logBox14.compact16~.log-resize14{display:none}#logBox14.compact16 .position-row14{max-height:32px}#logBox14.compact16 .position-row14 input{padding:0}#logBox14.compact16 #traceCommandUnit12{max-width:190px}#logBox14.compact16 .playback-global button{padding:6px}#logBox14.compact16 .playback-global{padding:0!important}#logBox14.compact16 #positionReadout12{display:none}#logBox14.compact16~.drop14{padding:4px;font-size:12px}#logBox14.compact16 .playback-global>strong{display:none}
#commandStatus13.empty16{border-color:var(--line);font-weight:400} .setup16{border:1px solid var(--line);border-radius:6px;padding:8px;margin:6px 0}.setup16>summary{cursor:pointer;font-weight:600}.setup16[open]>summary{margin-bottom:8px}.setup16>button{margin:4px}.table-actions16{display:flex;align-items:center;flex-wrap:wrap;gap:6px;font-size:12px;color:var(--muted);margin:4px 0}.table-actions16 button{padding:5px 8px}.skip16{position:fixed;left:8px;top:-100px;z-index:10000;background:var(--surface);padding:12px;color:var(--text)}.skip16:focus{top:8px}:focus-visible{outline:2px solid var(--accent);outline-offset:3px}#reviewRevisionStatus{padding:12px;border:1px solid var(--line);border-radius:6px}#reviewRevisionStatus[data-reviewed=true]{border-color:#50b9b0}.sessionbar{display:none!important}.revision-toolbar .sessionbar{display:block!important}.revision-toolbar>details{flex-basis:100%}.settings-group16{grid-column:1/-1} .settings-group16>.panel{margin-top:12px}#rawReviewPanel>p:first-of-type{font-size:12px;margin:4px 0}#rawReviewPanel .formrow{gap:6px;margin:4px 0}@media(max-width:900px){.revision-toolbar{gap:4px!important}.revision-toolbar button{padding:7px}#logBox14.compact16 .playback-global{gap:4px} .setup16{max-width:100%;overflow:auto}}
`;document.head.append(css16);
const skip16=document.createElement('a');skip16.className='skip16';skip16.href='#pageTitle';skip16.textContent='Skip to Current Workspace';document.body.prepend(skip16);$('pageTitle').tabIndex=-1;
const menu16=document.createElement('details');menu16.className='setup16';menu16.innerHTML='<summary>Menu and Layout Options</summary>';document.querySelector('nav').after(menu16);for(const b of [...bar11.querySelectorAll('button')])if(/Menu Order/.test(b.textContent))menu16.append(b);
const compact16=document.createElement('button');compact16.id='compactPlayer16';compact16.className='secondary';playerControls15.prepend(compact16);
function compactPlayer16(persist=false){logBox14.classList.toggle('compact16',revision16.compact);compact16.textContent=revision16.compact?'Player Details':'Compact Player';compact16.setAttribute('aria-expanded',String(!revision16.compact));if(persist){dirtyWindow();scheduleWorkspaceCache();}}
compact16.onclick=()=>{revision16.compact=!revision16.compact;compactPlayer16(true);};
// Import remains one shared route, with purpose selection disclosed on demand.
const windowOptions16=document.createElement('details');windowOptions16.className='setup16';windowOptions16.innerHTML='<summary>Workspace Window and Panel Options</summary>';const windowBar16=document.querySelector('.workspace-toolbar');if(windowBar16){windowBar16.append(windowOptions16);windowOptions16.append($('resetWorkspaceGrid'));}
const import16=document.createElement('details');import16.id='importOptions16';import16.className='setup16';import16.innerHTML='<summary>Import Datalogs / Set Intended Purpose</summary>';const session16=document.querySelector('.sessionbar');if(session16){bar11.append(import16);import16.append(session16);}const drop16=bar11.querySelector('.drop14');if(drop16){const dropOutput16=drop16.querySelector('output');drop16.textContent='Import or Drop CSV / TXT Datalogs · Set Intended Purpose';if(dropOutput16)drop16.append(dropOutput16);import16.querySelector('summary').replaceChildren(drop16);}
// The conversion workspace remains addressable for older projects and search.
const conversionNav16=document.querySelector('nav [data-tab="compare"]');if(conversionNav16)conversionNav16.hidden=true;
function conversionButton16(parent){if(!parent||parent.querySelector('[data-conversion16]'))return;const b=document.createElement('button');b.className='secondary';b.dataset.conversion16='true';b.textContent='Pressure Conversion Tool';b.onclick=()=>{goPage('compare');$('compareTable').focus();};parent.append(b);}
conversionButton16($('boost').querySelector('.formrow'));conversionButton16($('gears').querySelector('.formrow'));
const back16=document.createElement('button');back16.className='secondary';back16.textContent='Back to Boost Tables';back16.onclick=()=>goPage('boost');$('compare').prepend(back16);
const conversionNote16=document.createElement('p');conversionNote16.className='hint';conversionNote16.textContent='One source table shown in different pressure units. Check absolute versus gauge units and atmospheric reference before transferring values. This is not an independent calibration comparison.';$('compare').prepend(conversionNote16);
// Keep meaningful current-configuration and readiness messages; disclose detailed controls.
function disclose16(panel,title){if(!panel||panel.dataset.disclosed16)return;panel.dataset.disclosed16='true';const d=document.createElement('details');d.className='setup16';const s=document.createElement('summary');s.textContent=title;d.append(s);const tools=panel.querySelector(':scope > .panel-tools');for(const n of [...panel.childNodes])if(n!==tools)d.append(n);panel.append(d);}
const logs16=$('logs');logs16.prepend(rawPanel);const rawTimeSetup16=document.createElement('details');rawTimeSetup16.className='setup16';rawTimeSetup16.innerHTML='<summary>Timestamp Channel and Units</summary>';const timeRow16=$('rawTimeChannel').closest('.formrow');timeRow16.before(rawTimeSetup16);rawTimeSetup16.append(timeRow16,$('rawChannelPickers'));rawTimeSetup16.querySelector('summary').textContent='Channels and Timestamp Setup';disclose16(reviewFlowPanel,'Purpose and Channel Readiness — Setup and Recovery');
const logSetup16=$('logMapping').closest('.panel');disclose16(logSetup16,'Boost Review Units, Filters and Channel Mapping');
const guide16=logs16.querySelector('.guide-workflow');if(guide16){disclose16(guide16,'Review Shortcuts');const b=document.createElement('button');b.className='secondary';b.textContent='Continue Guided Tutorial';b.onclick=()=>tutorialButton15.click();guide16.prepend(b);}
for(const id of ['flowPlan'])if($(id)){$(id).textContent='Logging Instructions';}
for(const b of document.querySelectorAll('.sessionbar button'))if(/Review plan/i.test(b.textContent)){b.textContent='Logging Instructions';}
const strategyGuide16=document.createElement('button');strategyGuide16.className='secondary';strategyGuide16.textContent='Start or Resume Guided Tutorial';strategyGuide16.onclick=()=>tutorialButton15.click();$('strategy').prepend(strategyGuide16);
// Move the boost editor ahead of secondary panels within its existing layout grid.
for(const id of ['boost','afm']){const guide=$(id).querySelector('.guide-workflow');if(guide)disclose16(guide,'Guided Workflow Shortcuts');}
for(const [id,hostId]of [['boost','sourceGrid'],['afm','afmPreview']]){const panel=$(hostId)?.closest('.panel');if(panel&&panel.parentElement!==document.body){const grid=panel.parentElement;const order=gridDefaults.get(grid);if(order){gridDefaults.set(grid,[panel.dataset.gridId,...order.filter(x=>x!==panel.dataset.gridId)]);if(!panelLayouts[windowRole][id])grid.prepend(panel);}else grid.prepend(panel);if(id==='boost'&&grid.parentElement===$(id))$(id).prepend(grid);}}
// Gear import/conversion fields are setup; native table editing remains immediately accessible.
const gearSetup16=document.createElement('details');gearSetup16.className='setup16';gearSetup16.innerHTML='<summary>Import and Pressure Conversion Setup</summary>';const gp=$('gearPaste').parentElement;const start=[...gp.children].findIndex(n=>n.contains($('gearImportFormat'))),end=[...gp.children].findIndex(n=>n.id==='gearEditor');if(start>=0&&end>start){const nodes=[...gp.children].slice(start,end);nodes[0].before(gearSetup16);for(const n of nodes)gearSetup16.append(n);}
// Separate acknowledgement scope from the journal approvals and the destination check.
$('releaseReview').querySelector('h2').textContent='Current Proposal Review';
function reviewReasons16(){if(!reviewAcknowledgement)return 'Current proposals have not been reviewed.';try{const before=JSON.parse(reviewAcknowledgement.signature),after=JSON.parse(revisionSignature()),names={mpr:'MPR table or controls',command:'Command table or controls',afm:'AFM curve',afmCells:'AFM proposal evidence',afmDirty:'AFM analysis freshness',gear:'Gear table',gearOriginal:'Gear original',gearView:'Gear display/reference',evidence:'Log, mapping, calibration or filters',evidenceRange:'Evidence range',evidenceBin:'Evidence selection',rules:'Review rules'};return Object.keys(after).filter(k=>JSON.stringify(after[k])!==JSON.stringify(before[k])).map(k=>names[k]??k).join('; ')||'Evidence configuration changed.';}catch{return 'Saved review context differs from the current proposals.';}}
const reviewStatus16Base=updateReviewStatus;updateReviewStatus=function(){reviewStatus16Base();const reviewed=reviewAcknowledgement?.signature===revisionSignature();$('markRevisionReviewed').disabled=reviewed;$('markRevisionReviewed').textContent=reviewed?'Current Proposals Reviewed':'Mark Current Proposals Reviewed';$('reviewRevisionStatus').dataset.reviewed=String(reviewed);$('reviewRevisionStatus').textContent=reviewed?'Reviewed '+reviewAcknowledgement.date+' — current proposals and evidence context. Vehicle outcome remains unvalidated.':'Pending — '+reviewReasons16();};
const reviewHeading16=$('changeSummary').closest('.panel').querySelector('h2');if(reviewHeading16)reviewHeading16.textContent='Proposed Changes and Supporting Evidence';
// Group settings without changing IDs, handlers or appearance inheritance.
const settings16=$('settings');if(settings16){const groups=new Map();for(const p of [...settings16.querySelectorAll('.panel')]){if(p.closest('.panel')!==p||p.dataset.settings16)continue;const title=p.querySelector('h2')?.textContent??'',group=/appearance|font|theme|typograph/i.test(title)?'Appearance':/layout|workspace|navigation/i.test(title)?'Workspace Layout':/stor|cache/i.test(title)?'Storage and Projects':'Units and Review Preferences';let d=groups.get(group);if(!d){d=document.createElement('details');d.className='setup16 settings-group16';d.innerHTML='<summary>'+group+'</summary>';d.open=group==='Appearance';p.before(d);groups.set(group,d);}p.dataset.settings16='true';d.append(p);}}
const saveNote16=document.createElement('p');saveNote16.className='hint';saveNote16.textContent='Save Project downloads a portable JSON backup. Browser workspace storage is local convenience storage; it is not that downloaded backup. Save a project before moving computers or clearing browser data.';$('project').prepend(saveNote16);
function tableActions16(){for(const host of document.querySelectorAll('#sourceGrid,#proposedGrid,#afmPreview,#afmGrid,#gearGrid,.custom-table-body')){if(host.dataset.actions16)continue;host.dataset.actions16='true';const row=document.createElement('div');row.className='table-actions16';const trace=host.previousElementSibling?.dataset.traceHost14!==undefined?host.previousElementSibling:null;if(trace)row.append(trace);const eligible=['sourceGrid','proposedGrid','afmPreview','gearGrid'].includes(host.id)||host.classList.contains('custom-table-body');const hint=document.createElement('span');hint.textContent=eligible?'Select a cell, then wheel to zoom. Ctrl+wheel keeps browser zoom.':'Use appearance sizing for this table.';row.append(hint);if(eligible){for(const [text,delta]of [['Zoom In',-100],['Zoom Out',100]]){const b=document.createElement('button');b.className='secondary';b.textContent=text;b.onclick=()=>host.querySelector('td')?.dispatchEvent(new WheelEvent('wheel',{deltaY:delta,bubbles:true,cancelable:true}));row.append(b);}}host.before(row);}}
const custom16Base=renderCustomWorkspace;renderCustomWorkspace=function(){custom16Base();tableActions16();};
const command16Base=commandStatusUpdate13;commandStatusUpdate13=function(){command16Base();commandStatus13.classList.toggle('empty16',!flowItem());};
const page16Base=goPage;goPage=function(id){page16Base(id);tableActions16();};
const serialize16Base=serialize;serialize=function(){return{...serialize16Base(),uiRelease:'0.16',revision16:clone(revision16)};};const load16Base=loadProject;loadProject=function(p){const prefs=p.revision16??{schema:1,compact:true};if(prefs.schema!==1||typeof prefs.compact!=='boolean')throw Error('Invalid v0.16 interface preferences');load16Base(p);revision16=clone(prefs);compactPlayer16();updateReviewStatus();tableActions16();};
// A live editing lease or newly selected log must always update the remote controller.
window.addEventListener('focus',sendPlayer15);document.addEventListener('visibilitychange',sendPlayer15);
compactPlayer16();updateReviewStatus();tableActions16();commandStatusUpdate13();document.querySelector('.brand small').textContent='LOCAL WORKSPACE · v0.16';document.querySelector('footer').textContent='TuneLab v0.16 · Local Files Only';
