'use strict';
const loggingStrategies={
 afm:{title:'Warm steady driving · AFM evidence',drive:'Warm the engine to its normal operating temperature. Collect varied, legal, light-to-moderate steady driving, holding a stable pedal where practical. Avoid using acceleration transitions, open-loop operation or a boost pull as steady trim evidence. Set up recording before driving; a passenger or onboard recorder handles capture.',channels:'Timestamp, engine RPM, AFM frequency in Hz, coolant temperature, pedal position, manifold pressure with explicit units, commanded mixture, measured mixture, fuel-system / closed-loop status, short-term trim and total trim with defined meanings.',review:'Record the installed AFM curve and calibration revision. Confirm the actual channel units and closed-loop status encoding. Review eligibility exclusions and coverage before calculating. TuneLab currently uses a frequency-based AFM curve; voltage-only AFM data needs a supported workflow and must not be relabeled as Hz.',source:'Hondata documents warm varied driving and closed-loop trim review for its voltage-based AFM procedure. Its stock-injector/stock-table prerequisites and voltage axes do not establish applicability to your modified setup or TuneLab’s Hz calculation.'},
 boost:{title:'Loaded pull · boost tracking',drive:'Use a dyno or closed course with a tuner-defined gear, RPM range, load, endpoint and abort criteria appropriate to the vehicle. Begin recording before load increases and retain the transition, steady section and lift. Do not use a generic gear/redline recipe or operate a laptop while driving.',channels:'Timestamp, RPM, pedal / throttle, actual boost or MAP, boost command / target, atmospheric pressure and gear. Record units and whether each pressure is absolute or gauge. Useful tuner context: wastegate command, measured and commanded lambda/AFR, intake and coolant temperature, knock/ignition corrections and fuel-pressure channels where supported.',review:'Review spool / overshoot with the transient preset before selecting a steady section. Compare actual and command at the same timestamp. Record fuel, hardware, calibration revision and ambient conditions. Coverage and small boost error do not establish engine safety; this app does not assess every fuel/knock channel.'},
 startup:{title:'Startup / idle · capture context',drive:'Park securely in a ventilated location. Configure recording before starting, then capture available pre-start/key-on data, cranking, initial idle and stabilization without driving. Identify cold versus warm start, soak duration and starting conditions. Follow the vehicle/tuner’s starting procedure; do not extend cranking just to fill a log.',channels:'Timestamp, RPM, coolant and intake temperature, battery voltage, pedal / throttle, MAP with units, commanded mixture, measured mixture when the sensor is ready, fuel-system status and fuel pressure / injector data where available.',review:'Mark start/crank/idle intervals and sensor readiness. Save the original export and note the calibration revision. Use raw sample inspection for available channels; the current charts remain boost-oriented. Startup / open-loop samples are not steady AFM correction evidence and TuneLab does not calculate startup fueling changes.'},
 validation:{title:'Post-change validation · matched conditions',drive:'Repeat the original purpose under comparable fuel, hardware, temperature and operating conditions using the tuner-approved capture method. Change one planned calibration item at a time when feasible. Record the exact applied revision and any other changes.',channels:'Use the same channels, units and recording configuration as the baseline purpose. Keep separate baseline and validation files with unambiguous calibration identifiers.',review:'Only assign validation after checking that its installed curve matches the applied proposal. Compare eligible ranges and coverage as well as trim/error. An unrelated historical drive is context, not proof that a proposal worked.'}
};
addSection('strategy','Logging strategy',`<div class="panel"><h2>Plan a useful datalog</h2><p>Choose the question before collecting data. Channel availability and ECU meaning depend on the vehicle, logger and calibration.</p><label>Logging purpose<select id="loggingPurpose"><option value="afm">Steady AFM evidence</option><option value="boost">Boost pull / tracking</option><option value="startup">Startup / idle</option><option value="validation">Post-change validation</option></select></label><div id="loggingPlan"></div></div><div class="panel"><h2>Recording and source applicability</h2><p>Keep the original export, installed calibration identifier, fuel, hardware and conditions. Check headers and units before assigning evidence roles. Additional logged channels remain available in raw inspection; they are not all plotted or analyzed.</p><p>Hondata’s <a href="https://www.hondata.com/help/flashpro/tuning_afm_flow.htm" target="_blank" rel="noopener">AFM procedure</a> describes warm closed-loop review using AFM voltage, with specific starting-calibration prerequisites. TuneLab’s frequency-based analysis has separate requirements.</p><p>KTuner documents <a href="https://www.ktuner.com/KTunerHelp/tuning.htm" target="_blank" rel="noopener">recording and saving logs</a> and <a href="https://www.ktuner.com/KTunerHelp/on_board_logging.htm" target="_blank" rel="noopener">onboard logging on supported hardware</a>. Verify your hardware and logging configuration. These references do not establish common channel meanings across platforms.</p><p>The boost, startup and validation plans are TuneLab capture guidance, not an official vehicle-specific tuning procedure. Agree on vehicle-specific limits and interpretation with your tuner.</p></div>`);
descriptions.strategy=['Logging strategy','Choose how to drive, load the file and follow a review plan.'];
const reviewSteps={
 afm:['Import the saved CSV and choose Steady AFM evidence as its intended purpose.','Open Log library, record the installed calibration and conditions, and review any format or missing-channel warnings.','In AFM scaler, load the actual installed curve and select this log as Baseline. Confirm the match only when you know that curve was installed for the drive.','Select Analyze. Inspect accepted/excluded samples and supported bins; unsupported bins stay unchanged.','Review the proposed curve and Change review. Discuss unsupported changes or unusual trims with your tuner before applying anything.','After an approved change is applied outside TuneLab, repeat comparable driving and import the new log as Validation. Confirm its match to the applied proposal before comparing.'],
 boost:['Import the CSV with Boost pull / tracking as its intended purpose. Record the installed revision and conditions in Log library.','Open Log review and verify any format or pressure-unit warnings. Choose Spool / overshoot to retain the load transition.','Select the recorded pull or time range. Move the cursor through spool, peak and the steady portion; compare actual boost and command at the same instant.','Inspect error, coverage and gaps. Compare another historical log only when gear, calibration and conditions are understood.','Record the observed pattern for your tuner. Use Change review if you create a table proposal; the log does not prove which table controlled the ECU or establish engine safety.'],
 startup:['Import the saved CSV with Startup / idle as its intended purpose. Note cold/warm start, soak duration and the installed revision.','Open Log review, choose Whole drive / RPM selection and set minimum RPM to 0 so pre-start and cranking samples are not excluded.','Use the frame slider and raw sample inspection to find pre-start, cranking, initial idle and stabilization. Note which sensors were ready.','Record timestamps and observations such as RPM or battery voltage changes where those channels exist. The current charts are boost-oriented; arbitrary-channel plotting is not available.','Save the project and original export for your tuner. Startup samples are not steady AFM evidence; TuneLab does not propose startup fueling changes.'],
 validation:['Import the new CSV with Post-change validation as its intended purpose. Record exactly which revision was applied and any fuel/hardware/condition changes.','Open the original baseline and the new log. Check comparable ranges, temperatures and usable coverage; an unrelated historical drive is context.','For an AFM change, select the new log as Validation in AFM scaler and confirm it matches the applied proposed curve. Keep the original Baseline assigned.','Analyze and compare validation trims in supported bins. Validation never drives a new correction by itself. For boost, compare simultaneous actual/command error in comparable segments.','Record the result and remaining gaps in your notes, then save project JSON. Collect additional matched evidence or ask your tuner to review inconclusive results.']
};
function renderLoggingPlan(){const p=loggingStrategies[$('loggingPurpose').value];$('loggingPlan').innerHTML=`<h3>${esc(p.title)}</h3><h4>Driving / capture instructions</h4><p>${esc(p.drive)}</p><h4>After loading the file</h4><ol>${reviewSteps[$('loggingPurpose').value].map(step=>`<li>${esc(step)}</li>`).join('')}</ol><details><summary>Optional logger details and applicability</summary><p>${esc(p.channels)}</p>${p.source?`<p class="hint">${esc(p.source)}</p>`:''}</details>`;}
$('loggingPurpose').onchange=renderLoggingPlan;renderLoggingPlan();
const purposeNames={unknown:'Not specified',afm:'Steady AFM evidence',boost:'Boost pull / tracking',startup:'Startup / idle',validation:'Post-change validation'};
function purposeOptions(value='unknown'){return Object.entries(purposeNames).map(([id,name])=>`<option value="${id}" ${id===value?'selected':''}>${esc(name)}</option>`).join('');}
const purposePicker=document.createElement('label');purposePicker.innerHTML='Intended purpose for imported logs<select id="importPurpose">'+purposeOptions()+'</select>';$('sessionFiles').closest('label').before(purposePicker);
const reviewPlanButton=document.createElement('button');reviewPlanButton.id='logReviewPlan';reviewPlanButton.className='secondary';reviewPlanButton.textContent='Review plan';$('manageLogs').after(reviewPlanButton);
reviewPlanButton.onclick=()=>{const purpose=sessions.find(x=>x.id===activeSession)?.purpose;if(loggingStrategies[purpose])$('loggingPurpose').value=purpose;renderLoggingPlan();goPage('strategy');};
const importPurposeBase=importSession;importSession=async function(text,name,purpose){const existing=sessions.find(x=>x.text===text),item=await importPurposeBase(text,name);if(!existing){item.purpose=Object.hasOwn(purposeNames,purpose)?purpose:$('importPurpose').value;rebuildSessionList();await persistSessionStore();}return item;};
const rebuildPurposeBase=rebuildSessionList;rebuildSessionList=function(){rebuildPurposeBase();for(const item of sessions){const heading=[...$('sessionList').querySelectorAll('.session-entry h3')].find(n=>n.parentElement.querySelector('[data-session-meta]')?.dataset.sessionMeta===item.id);if(!heading)continue;const label=document.createElement('label');label.innerHTML=`Intended purpose<select data-session-meta="${esc(item.id)}" data-field="purpose">${purposeOptions(item.purpose)}</select>`;heading.after(label);}const item=sessions.find(x=>x.id===activeSession);if(item)$('activeContext').textContent+=' · '+(purposeNames[item.purpose]??purposeNames.unknown);};
rebuildSessionList();
