// Expand this catalog with independently sourced model/year/color entries.
const vehicleThemes={"civic-si":{label:"Honda Civic Si",generation:"11th generation",years:{2022:['blue','orange','black','white','red','sonic'],2023:['blue','orange','black','white','red','sonic'],2024:['blue','orange','black','white','red','sonic'],2025:['black','white','red','urban'],2026:['black','white','red','urban']},colors:{blue:{name:'Aegean Blue Metallic',accent:'#429ce4',surface:'#182634',background:'#0d1823'},orange:{name:'Blazing Orange Pearl',accent:'#ed9847',surface:'#30251e',background:'#1c1612'},black:{name:'Crystal Black Pearl',accent:'#b9c3d2',surface:'#202126',background:'#111216'},white:{name:'Platinum White Pearl',accent:'#e9edf3',surface:'#30343e',background:'#191d25'},red:{name:'Rallye Red',accent:'#f36a70',surface:'#302026',background:'#1d1218'},sonic:{name:'Sonic Gray Pearl',accent:'#b0c3cb',surface:'#29333a',background:'#192228'},urban:{name:'Urban Gray Pearl',accent:'#b6bbb7',surface:'#303632',background:'#1c231f'}}}};
function vehicleThemeSelection(){const match=/^vehicle:([^:]+):(\d{4}):([^:]+)$/.exec($('theme').value);if(!match)return null;const model=vehicleThemes[match[1]],year=match[2],color=match[3];return model?.years[year]?.includes(color)?{model:match[1],year,color,paint:model.colors[color]}:null;}
function syncVehicleTheme(){const picked=vehicleThemeSelection(),modelKey=picked?.model??$('themeModel').value,model=vehicleThemes[modelKey];if(!model)return;$('themeModel').value=modelKey;const year=picked?.year??($('themeYear').value||'2026');$('themeYear').innerHTML=Object.keys(model.years).map(y=>`<option value="${y}">${y}</option>`).join('');$('themeYear').value=model.years[year]?year:Object.keys(model.years).at(-1);const color=picked?.color??$('themeColor').value,available=model.years[$('themeYear').value];$('themeColor').innerHTML=available.map(k=>`<option value="${k}">${model.colors[k].name}</option>`).join('');$('themeColor').value=available.includes(color)?color:available[0];for(const id of ['themeModel','themeYear','themeColor'])$(id).disabled=$('theme').value!=='vehicle'&&!picked;}
function pickVehicleTheme(){syncVehicleTheme();const key=`vehicle:${$('themeModel').value}:${$('themeYear').value}:${$('themeColor').value}`;if(![...$('theme').options].some(o=>o.value===key))$('theme').add(new Option('Vehicle · '+vehicleThemes[$('themeModel').value].label+' '+$('themeYear').value+' · '+$('themeColor').selectedOptions[0].text,key));$('theme').value=key;$('accent').value=vehicleThemeSelection().paint.accent;applyAppearance();}
$('themeModel').innerHTML=Object.entries(vehicleThemes).map(([key,m])=>`<option value="${key}">${m.label} · ${m.generation}</option>`).join('');
for(const [modelKey,model]of Object.entries(vehicleThemes))for(const [year,colors]of Object.entries(model.years))for(const color of colors)$('theme').add(new Option(`${model.label} ${year} · ${model.colors[color].name}`,`vehicle:${modelKey}:${year}:${color}`));
for(const o of $('theme').options)if(o.value.startsWith('vehicle:'))o.hidden=true;
for(const id of ['themeModel','themeYear','themeColor'])$(id).addEventListener('change',()=>{$('theme').value='vehicle';pickVehicleTheme();});
$('theme').addEventListener('change',()=>{if($('theme').value==='vehicle')pickVehicleTheme();else syncVehicleTheme();});
