'use strict';
// Minimal offline XLSX writer: numeric cells remain numeric; text is never a formula.
window.TuneLabWorkbook={build(sheets){
const enc=new TextEncoder(),xml=x=>String(x).replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c])),col=i=>{let s='';for(i++;i;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s;};
const files=[],add=(n,s)=>files.push({name:enc.encode(n),data:enc.encode(s)}),ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';
add('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'+sheets.map((_,i)=>'<Override PartName="/xl/worksheets/sheet'+(i+1)+'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>').join('')+'</Types>');
add('_rels/.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
add('xl/workbook.xml','<workbook xmlns="'+ns+'" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'+sheets.map((s,i)=>'<sheet name="'+xml(s.name)+'" sheetId="'+(i+1)+'" r:id="rId'+(i+1)+'"/>').join('')+'</sheets></workbook>');
add('xl/_rels/workbook.xml.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+sheets.map((_,i)=>'<Relationship Id="rId'+(i+1)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'+(i+1)+'.xml"/>').join('')+'<Relationship Id="styles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>');
add('xl/styles.xml','<styleSheet xmlns="'+ns+'"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF176879"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFill="1" applyFont="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>');
sheets.forEach((s,i)=>{if(!s.rows.length||s.rows.length>1048576||Math.max(...s.rows.map(r=>r.length))>16384)throw Error('Invalid worksheet dimensions');const width=Math.max(...s.rows.map(r=>r.length)),views=s.axes?'<sheetViews><sheetView workbookViewId="0"><pane xSplit="1" ySplit="1" topLeftCell="B2" activePane="bottomRight" state="frozen"/></sheetView></sheetViews>':'';add('xl/worksheets/sheet'+(i+1)+'.xml','<worksheet xmlns="'+ns+'"><dimension ref="A1:'+col(width-1)+s.rows.length+'"/>'+views+'<cols><col min="1" max="'+width+'" width="'+(s.notes?32:14)+'" customWidth="1"/></cols><sheetData>'+s.rows.map((r,j)=>'<row r="'+(j+1)+'">'+r.map((v,k)=>{const ref=col(k)+(j+1),style=s.axes&&(j===0||k===0)?' s="1"':'';if(typeof v==='number'){if(!Number.isFinite(v))throw Error('Nonfinite worksheet value');return'<c r="'+ref+'"'+style+'><v>'+v+'</v></c>';}return'<c r="'+ref+'" t="inlineStr"'+style+'><is><t xml:space="preserve">'+xml(v??'')+'</t></is></c>';}).join('')+'</row>').join('')+'</sheetData></worksheet>');});
const table=new Uint32Array(256);for(let i=0;i<256;i++){let x=i;for(let j=0;j<8;j++)x=x&1?0xedb88320^(x>>>1):x>>>1;table[i]=x;}const crc=b=>{let x=0xffffffff;for(const v of b)x=table[(x^v)&255]^(x>>>8);return(x^0xffffffff)>>>0;},header=(n)=>new Uint8Array(n),write=(b,o,v,size)=>{for(let i=0;i<size;i++)b[o+i]=(v>>>(8*i))&255;};
let offset=0;const chunks=[],central=[];for(const f of files){const sum=crc(f.data),h=header(30);write(h,0,0x04034b50,4);write(h,4,20,2);write(h,10,0,2);write(h,12,33,2);write(h,14,sum,4);write(h,18,f.data.length,4);write(h,22,f.data.length,4);write(h,26,f.name.length,2);chunks.push(h,f.name,f.data);const c=header(46);write(c,0,0x02014b50,4);write(c,4,20,2);write(c,6,20,2);write(c,14,33,2);write(c,16,sum,4);write(c,20,f.data.length,4);write(c,24,f.data.length,4);write(c,28,f.name.length,2);write(c,42,offset,4);central.push(c,f.name);offset+=h.length+f.name.length+f.data.length;}const count=central.reduce((n,x)=>n+x.length,0),end=header(22);write(end,0,0x06054b50,4);write(end,8,files.length,2);write(end,10,files.length,2);write(end,12,count,4);write(end,16,offset,4);return new Blob([...chunks,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
}};
