'use strict';
const F=TuneLabWorkflows;
let workflow={schema:1,storageEnabled:true,roles:{},zoom:{},guideSteps:{}},projectEpoch=0;

// Central settings use the existing controls and their event handlers.
addSection('settings','Settings',`<div class="panel"><h2>Workspace defaults</h2><p>Choose presentation, platform terminology and calculation behavior. Imported source units stay explicit beside each table.</p><div id="workspaceSettings"></div></div><div class="panel"><h2>Appearance inheritance</h2><label>Page for appearance overrides<select id="appearancePage"></select></label><div id="appearanceSettings"></div></div><div class="panel"><h2>Units and destination</h2><div id="unitSettings" class="formrow"></div><p>Pressure defaults apply to new work. Existing source tables and proposals retain their units and values.</p><div class="formrow"><label>New boost output units<select id="defaultPressure"></select></label><button id="applyPressureDefault" class="secondary">Apply to both current boost proposals</button></div></div><div class="panel"><h2>Review thresholds</h2><div id="reviewSettings"></div></div><div class="panel"><h2>Storage and backup</h2><label class="check"><input id="browserStorage" type="checkbox" checked>Keep historical log library in this browser</label><p>Browser storage holds logs, metadata, observations, history and layout. It is not a full calibration backup. Save project JSON to include tables, proposals, raw CSVs, settings, roles, history, layout and mapping provenance.</p><button id="fullBackup">Download complete workspace backup</button><p id="backupReport" role="status">v0.3–v0.5 projects can be opened; originals are unchanged. Reconfirm calibration matches after reopening.</p><p>Personal reference attachments are not supported in this release and are not included. Keep original exports and previous backup files separately.</p></div>`);
$('workspaceSettings').append(document.querySelector('.preferences'));
$('appearanceSettings').append(layoutBar);
layoutBar.open=true;
$('appearancePage').innerHTML=[...document.querySelectorAll('.page')].filter(x=>x.id!=='settings').map(x=>`<option value="${x.id}">${esc(descriptions[x.id]?.[0]??x.id)}</option>`).join('');
$('appearancePage').onchange=()=>loadPagePrefs();
for(const id of ['flowUnits','afmPlatform'])$('unitSettings').append($(id).closest('label'));
const gearUnitsSetting=document.createElement('label');gearUnitsSetting.innerHTML='Gear display / export units<select id="gearDisplaySettings"></select>';$('unitSettings').append(gearUnitsSetting);$('gearDisplaySettings').innerHTML=$('gearDisplay').innerHTML;$('gearDisplaySettings').value=$('gearDisplay').value;$('gearDisplaySettings').onchange=()=>{$('gearDisplay').value=$('gearDisplaySettings').value;$('gearDisplay').dispatchEvent(new Event('change',{bubbles:true}));};$('gearDisplay').addEventListener('change',()=>$('gearDisplaySettings').value=$('gearDisplay').value);
const localUnits=document.createElement('div');localUnits.className='formrow';localUnits.innerHTML='<label>Airflow display / copy units<select id="flowUnitsLocal"></select></label><label>Destination presentation<select id="afmPlatformLocal"></select></label>';$('afmPreview').before(localUnits);
for(const id of ['flowUnits','afmPlatform']){const local=$(id+'Local');local.innerHTML=$(id).innerHTML;local.value=$(id).value;local.onchange=()=>{$(id).value=local.value;$(id).dispatchEvent(new Event('change',{bubbles:true}));};$(id).addEventListener('change',()=>local.value=$(id).value);}
$('defaultPressure').innerHTML=$('outputUnits').innerHTML;
$('defaultPressure').value=$('outputUnits').value;
$('defaultPressure').onchange=()=>{workflow.defaultPressure=$('defaultPressure').value;try{localStorage.setItem('TuneLabDefaultsV6',JSON.stringify({pressure:workflow.defaultPressure,storage:workflow.storageEnabled}));}catch{message('Browser settings could not be saved. Download workspace JSON.','error');}};
$('reviewSettings').append($('warningSettings'));
$('warningSettings').classList.remove('advanced-only');$('warningSettings').open=true;
$('browserStorage').onchange=()=>{workflow.storageEnabled=$('browserStorage').checked;try{localStorage.setItem('TuneLabDefaultsV6',JSON.stringify({pressure:workflow.defaultPressure??$('defaultPressure').value,storage:workflow.storageEnabled}));}catch{}message(workflow.storageEnabled?'Browser library persistence enabled. Save JSON for a complete backup.':'Browser writes paused. Existing browser data remains available; save JSON before closing.');};
$('fullBackup').onclick=action(()=>download('TuneLab-v0.9-workspace.json',JSON.stringify(serialize(),null,2),'application/json'));
$('applyPressureDefault').onclick=action(()=>{const original=kind;for(const k of ['mpr','command']){switchKind(k);$('outputUnits').value=$('defaultPressure').value;$('outputUnits').dispatchEvent(new Event('change',{bubbles:true}));}switchKind(original);updateStatusStrip();});

const strip=document.createElement('div');strip.id='workspaceStatus';strip.className='workspace-status';strip.setAttribute('role','status');document.querySelector('header').after(strip);
function updateStatusStrip(){const item=sessions.find(x=>x.id===activeSession),page=currentPage(),p=page==='afm'?(afmDirty?'Stale':afmResult?'Current':'Not calculated'):(state[kind].dirty?'Stale':state[kind].proposal?'Current':'Not calculated');strip.textContent=`${$('platformMode').selectedOptions[0].text} · ${item?.name??'No active log'} · ${item?.calibration||'Calibration unrecorded'} · Boost ${state[kind].controls.outputUnits} / airflow ${$('flowUnits').selectedOptions[0].text} · ${page==='afm'?'AFM':kind.toUpperCase()} proposal: ${p}`;}
for(const name of ['change','click'])document.addEventListener(name,()=>queueMicrotask(updateStatusStrip));
for(const [name,fn]of [['boost',renderBoost],['afm',renderAfm]]){if(name==='boost')renderBoost=function(){fn();applyZoom();updateStatusStrip();};else renderAfm=function(){fn();for(const id of ['flowUnits','afmPlatform'])$(id+'Local').value=$(id).value;drawAfmDeltas();applyZoom();updateStatusStrip();};}

// Coordinated zoom applies sizes rather than browser transforms; indices and exports stay exact.
for(const id of ['sourceGrid','proposedGrid','afmPreview','gearGrid']){const bar=document.createElement('div');bar.className='table-zoom';bar.innerHTML=`<label>Table zoom<select data-table-zoom="${id}"><option value="0.75">75%</option><option value="1" selected>100%</option><option value="1.25">125%</option><option value="1.5">150%</option><option value="2">200%</option><option value="fit">Fit width · readable minimum</option></select></label>`;$(id).before(bar);bar.querySelector('select').onchange=e=>{workflow.zoom[id]=e.target.value;applyZoom();};}
function applyZoom(){for(const id of ['sourceGrid','proposedGrid','afmPreview','gearGrid']){const node=$(id),table=node.querySelector('table');if(!table)continue;const page=node.closest('.page').id,p={...layoutPrefs.app,...layoutPrefs.pages[page]},choice=workflow.zoom[id]??'1',columns=table.rows[0]?.cells.length??1;let z=Number(choice)||1;if(choice==='fit'){const width=node.clientWidth;z=width?Math.max(.75,Math.min(2,width/(columns*(p.font*5+p.col*2)))):.75;}node.classList.add('coordinated-zoom');node.style.setProperty('--zoom-cell',Math.max(9,p.font*z)+'px');node.style.setProperty('--zoom-header',Math.max(9,p.header*z)+'px');node.style.setProperty('--zoom-row',p.row*z+'px');node.style.setProperty('--zoom-col',p.col*z+'px');node.style.setProperty('--zoom-min',Math.max(54,64*z)+'px');document.querySelector(`[data-table-zoom="${id}"]`).value=choice;}}
if(window.ResizeObserver){const observer=new ResizeObserver(applyZoom);for(const id of ['sourceGrid','proposedGrid','afmPreview','gearGrid'])observer.observe($(id));}
const gearRenderV5=renderGear;renderGear=function(){gearRenderV5();$('gearDisplaySettings').value=$('gearDisplay').value;applyZoom();};

// Pointer selection uses the same protected-cell edit engine as keyboard selection.
let drag=null,suppressClick=false,edgeFrame=null;
function pickCell(cell,extend=false){const target=cell.dataset.edit,p=[+cell.dataset.er,+cell.dataset.ec];if(extend&&selection.target===target&&selection.a)selection.b=p;else selection={target,a:p,b:p};paintSelection();selectionSummary();}
function selectionSummary(){if(!selection.a)return;const cells=[...document.querySelectorAll('.selected[data-edit]')],locked=cells.filter(x=>x.classList.contains('locked')).length,n=$(selection.target+'Selection');if(n)n.textContent=`${cells.length} cells selected · ${locked} protected cells stay unchanged. Drag or Shift-click to extend; double-click or Enter to edit.`;}
const paintV5=paintSelection;paintSelection=function(){paintV5();document.querySelectorAll('[data-edit]').forEach(cell=>{cell.setAttribute('aria-selected',cell.classList.contains('selected')?'true':'false');cell.classList.remove('selection-top','selection-bottom','selection-left','selection-right');if(!cell.classList.contains('selected'))return;const a=selection.a,b=selection.b??a,r=+cell.dataset.er,c=+cell.dataset.ec;for(const [side,yes]of [['top',r===Math.min(a[0],b[0])],['bottom',r===Math.max(a[0],b[0])],['left',c===Math.min(a[1],b[1])],['right',c===Math.max(a[1],b[1])]])if(yes)cell.classList.add('selection-'+side);});};
function dragAt(x,y){if(!drag)return;drag.x=x;drag.y=y;const cell=document.elementFromPoint?.(x,y)?.closest('[data-edit]');if(cell&&cell.dataset.edit===selection.target){selection.b=[+cell.dataset.er,+cell.dataset.ec];paintSelection();selectionSummary();}}
function edgeScroll(){if(!drag)return;const sc=drag.scroll,r=sc.getBoundingClientRect(),speed=(v,lo,hi)=>v<lo+28?-12:v>hi-28?12:0;sc.scrollLeft+=speed(drag.x,r.left,r.right);sc.scrollTop+=speed(drag.y,r.top,r.bottom);dragAt(drag.x,drag.y);edgeFrame=requestAnimationFrame(edgeScroll);}
document.addEventListener('pointerdown',e=>{const cell=e.target.closest('[data-edit]');if(!cell||e.button!==0)return;e.preventDefault();pickCell(cell,e.shiftKey);cell.focus({preventScroll:true});drag={id:e.pointerId,x:e.clientX,y:e.clientY,scroll:cell.closest('.table-scroll')};suppressClick=true;edgeFrame=requestAnimationFrame(edgeScroll);});
document.addEventListener('pointermove',e=>{if(drag&&e.pointerId===drag.id){e.preventDefault();dragAt(e.clientX,e.clientY);}});
function endDrag(){drag=null;if(edgeFrame!==null)cancelAnimationFrame(edgeFrame);setTimeout(()=>suppressClick=false,0);}
document.addEventListener('pointerup',endDrag);document.addEventListener('pointercancel',endDrag);window.addEventListener('blur',endDrag);
document.addEventListener('click',e=>{if(suppressClick&&e.target.closest('[data-edit]'))e.stopImmediatePropagation();},true);
document.addEventListener('keydown',e=>{const cell=e.target.closest('[data-edit]');if(!cell||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const r=+cell.dataset.er+(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0),c=+cell.dataset.ec+(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0),next=document.querySelector(`[data-edit="${cell.dataset.edit}"][data-er="${r}"][data-ec="${c}"]`);if(next){pickCell(next,e.shiftKey);next.focus();next.scrollIntoView?.({block:'nearest',inline:'nearest'});}});
for(const target of ['boost','airflow','gear'])$(target+'Selection').textContent='Drag cells or Shift-click to select a rectangle. Protected cells stay unchanged. Use Shift + arrow keys to extend.';

const deltaPanel=document.createElement('div');deltaPanel.className='panel';deltaPanel.innerHTML=`<h2>Airflow change detail</h2><div class="formrow"><label>Delta display<select id="afmDeltaUnits"><option value="percent">Percentage</option><option value="absolute">g/s</option></select></label><label>Magnification<select id="afmMagnify"><option value="1">1×</option><option value="5">5×</option><option value="10">10×</option></select></label></div><p id="afmDeltaNote"></p><div id="afmDeltaChart" class="chart"></div><output id="afmDeltaReadout">Hover either curve to inspect the same frequency.</output>`;$('afmChart').closest('.panel').after(deltaPanel);
function drawAfmDeltas(){const cells=afmResult?.cells??state.afm.map(x=>({...x,proposed:x.flow})),d=F.deltas(cells),plotD=d.filter(x=>x.original>0),percent=$('afmDeltaUnits').value==='percent',magnify=+$('afmMagnify').value;chart('afmDeltaChart',[{name:(percent?'%':'g/s')+' delta × '+magnify,color:'#e96f75',points:plotD.map(x=>[x.hz,(percent?x.percent:x.absolute)===null?null:(percent?x.percent:x.absolute)*magnify])}],'Hz',`Displayed ${percent?'%':'g/s'} delta × ${magnify}`);$('afmDeltaNote').textContent=`${d.filter(x=>x.changed).length} changed points. Delta is magnified ${magnify}× for visibility; tooltips and table values report the actual change.`;
 for(const id of ['afmChart','afmDeltaChart']){const svg=$(id).querySelector('svg');if(!svg)continue;if(!plotD.length)continue;svg.onmousemove=e=>{const rect=svg.getBoundingClientRect(),xmin=Math.min(...plotD.map(x=>x.hz)),xmax=Math.max(...plotD.map(x=>x.hz)),hz=xmin+((e.clientX-rect.left)/rect.width*900-54)/(900-54-18)*(xmax-xmin);const x=plotD.reduce((a,b)=>Math.abs(b.hz-hz)<Math.abs(a.hz-hz)?b:a);$('afmDeltaReadout').textContent=`${x.hz} Hz · original ${fmt(x.original,3)} g/s · proposed ${fmt(x.proposed,3)} g/s · actual delta ${fmt(x.absolute,4)} g/s / ${fmt(x.percent,4)}%${x.protected?' · protected':''}`;const tip=$(id).querySelector('.chart-tooltip');if(tip)tip.textContent=$('afmDeltaReadout').textContent;document.querySelectorAll('.afm-inspected').forEach(n=>n.classList.remove('afm-inspected'));$('afmPreview').querySelector(`[data-ec="${d.indexOf(x)}"]`)?.classList.add('afm-inspected');for(const chartId of ['afmChart','afmDeltaChart']){const s=$(chartId).querySelector('svg');s?.querySelector('.afm-link')?.remove();if(s){const line=document.createElementNS('http://www.w3.org/2000/svg','line'),px=54+(x.hz-xmin)/(xmax-xmin)*828;for(const[k,v]of Object.entries({x1:px,x2:px,y1:15,y2:175,stroke:'var(--accent)','stroke-dasharray':'4 3',class:'afm-link'}))line.setAttribute(k,v);s.append(line);}}};}
 const curve=$('afmChart').querySelector('svg');if(curve&&plotD.length){const ys=plotD.flatMap(x=>[x.original,x.proposed]),lo=Math.min(...ys),hi=Math.max(...ys),pad=(hi-lo)*.09||1,xmin=plotD[0].hz,xmax=plotD.at(-1).hz;for(const x of plotD.filter(x=>x.changed)){const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('cx',54+(x.hz-xmin)/(xmax-xmin)*828);dot.setAttribute('cy',175-(x.proposed-lo+pad)/(hi-lo+2*pad)*160);dot.setAttribute('r','3');dot.setAttribute('fill','var(--accent)');const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent=`${x.hz} Hz: ${fmt(x.absolute,4)} g/s / ${fmt(x.percent,4)}% change`;dot.append(title);curve.append(dot);}}
 $('afmPreview').querySelectorAll('[data-edit]').forEach((cell,j)=>{const x=d[j];cell.title=`${x.hz} Hz: ${fmt(x.original,3)} → ${fmt(x.proposed,3)} g/s; Δ ${fmt(x.absolute,4)} g/s / ${fmt(x.percent,4)}%${x.protected?' · protected, edits skipped':''}`;});
}
for(const id of ['afmDeltaUnits','afmMagnify'])$(id).onchange=drawAfmDeltas;

// One selector and adjacent import action for each evidence role.
for(const role of ['baseline','validation']){const sel=$(role+'Session'),file=$(role+'File'),box=document.createElement('div');box.className='evidence-picker';sel.closest('label').before(box);box.append(sel.closest('label'));const fileLabel=file.closest('label');box.append(fileLabel);fileLabel.classList.add('secondary');fileLabel.firstChild.textContent='Import and assign '+role+' ';const note=document.createElement('p');note.id=role+'Evidence';note.className='hint';box.append(note);}
function refreshEvidence(){for(const role of ['baseline','validation']){const item=sessions.find(x=>x.id===$(role+'Session').value);$(role+'Evidence').textContent=item?`${item.name} · calibration: ${item.calibration||'not recorded'} · ${role==='baseline'?'drives correction only after confirmation':'checks the applied proposal; never drives correction'}`:`${role==='baseline'?'Choose the log recorded with the current curve.':'Optional: choose a log recorded with the applied proposed curve.'}`;}}
$('validationSession').closest('.evidence-picker').before($('baselineSession').closest('.evidence-picker'));
const rebuildV5=rebuildSessionList;rebuildSessionList=function(){rebuildV5();refreshEvidence();};
for(const role of ['baseline','validation'])$(role+'Session').addEventListener('change',()=>{workflow.roles[role]=$(role+'Session').value;refreshEvidence();});

// Per-log mapping provenance is explicit; inference never automatically confirms evidence.
const profilePanel=document.createElement('div');profilePanel.className='panel';profilePanel.innerHTML=`<h2>Log format and channel provenance</h2><p id="formatEvidence"></p><div class="formrow"><label>Exporting platform<select id="logPlatform"><option value="unknown">Unknown / other</option><option value="hondata">Hondata</option><option value="ktuner">KTuner</option></select></label><label>Timestamp units<select id="profileTime"><option value="">Choose explicitly</option><option value="ms">Milliseconds</option><option value="s">Seconds</option></select></label><label>Actual and commanded boost units<select id="profilePressure"><option value="">Choose explicitly</option><option value="psi">Standard-reference PSI · v0.5 convention</option><option value="bar">Absolute bar</option><option value="kpa">Absolute kPa</option></select></label><label>Coolant units<select id="profileEct"><option value="">Choose explicitly</option><option value="f">°F</option><option value="c">°C</option></select></label><label>Trim units<select id="profileTrim"><option value="">Choose explicitly</option><option value="points">Percentage points</option><option value="fraction">Fraction</option></select></label></div><div id="profileMapping" class="formrow"></div><label class="check"><input id="profileConfirmed" type="checkbox">I checked channel meanings and units against the original export</label><button id="saveLogProfile">Save this log's mapping</button><p id="profileReport" role="status"></p><p>Mappings are saved per file; raw CSV is preserved. Similar names do not prove identical ECU meanings. Confirm atmospheric versus standard pressure reference in the exporting software.</p>`;$('sessionList').closest('.panel').after(profilePanel);
const mapUnitLabel=document.createElement('label');mapUnitLabel.innerHTML='MAP units for stability filter<select id="profileMapUnit"><option value="native">Native / unspecified</option><option value="mbar">mbar</option><option value="kpa">kPa</option><option value="bar">bar</option><option value="psi">PSI</option></select>';profilePanel.querySelector('.formrow').append(mapUnitLabel);
const meaning=document.createElement('p');meaning.textContent='AFM uses commanded AFR and Fuel Status = 2 for closed loop. Verify these meanings in each export; unsupported mixture/status conventions require separate review.';profilePanel.append(meaning);
function profileFor(item){return item.profile??F.inspect(item.log);}
function showLogProfile(){const item=sessions.find(x=>x.id===activeSession);if(!item){$('formatEvidence').textContent='Select an active historical log to review its format.';$('profileMapping').innerHTML='';return;}const p=profileFor(item);$('formatEvidence').textContent=p.evidence+' '+item.log.rejectedRows+' malformed-width rows excluded; missing measurements remain missing.';$('logPlatform').value=p.platform;$('profileTime').value=p.units.time??'';$('profilePressure').value=p.units.pressure??'';$('profileEct').value=p.units.ect??'';$('profileTrim').value=p.units.trim??'';$('profileMapUnit').value=p.units.map??'native';$('profileConfirmed').checked=p.confirmed;
 $('profileMapping').innerHTML=Object.keys(p.mapping).map(k=>`<label>${esc(k==='cmdAf'?'Commanded AFR':k)}<select data-profile-map="${k}"><option value="">Not mapped</option>${item.log.headers.map(h=>`<option ${h===p.mapping[k]?'selected':''}>${esc(h)}</option>`).join('')}</select></label>`).join('');}
function applyProfileToControls(item,afmOnly=false){if(!item?.profile?.confirmed)return;const p=item.profile;if(!afmOnly){for(const k of Object.keys(logMapping))$('logmap_'+k).value=p.mapping[k]??'';if(p.units.time)$('logTime').value=p.units.time;if(p.units.pressure)$('logPressure').value=p.units.pressure;return;}for(const k of Object.keys(afmMapping))$('map_'+k).value=p.mapping[k==='cmd'?'cmdAf':k]??'';if(p.units.time)$('timeUnit').value=p.units.time;if(p.units.ect)$('ectUnit').value=p.units.ect.toUpperCase();if(p.units.trim)$('trimUnit').value=p.units.trim;}
const activeV5=setActive;setActive=function(id){const item=sessions.find(x=>x.id===id);applyProfileToControls(item);activeV5(id);showLogProfile();updateStatusStrip();};
const importV5=importSession;importSession=async function(text,name){const item=await importV5(text,name);if(!item.profile)item.profile=F.inspect(item.log);showLogProfile();await persistSessionStore();if(item.log.rejectedRows)message(name+': '+item.log.data.length.toLocaleString()+' rows retained; '+item.log.rejectedRows.toLocaleString()+' rows rejected because their columns do not match the header. Raw CSV preserved; review or re-export before analysis.','dirty');return item;};
$('saveLogProfile').onclick=action(async()=>{const item=sessions.find(x=>x.id===activeSession);if(!item)throw Error('Select an active log first');const mapping=Object.fromEntries([...document.querySelectorAll('[data-profile-map]')].map(n=>[n.dataset.profileMap,n.value])),p={...profileFor(item),platform:$('logPlatform').value,mapping,units:{time:$('profileTime').value||null,pressure:$('profilePressure').value||null,ect:$('profileEct').value||null,trim:$('profileTrim').value||null,map:$('profileMapUnit').value},confirmed:$('profileConfirmed').checked,reviewedAt:new Date().toISOString(),evidence:'User-reviewed mapping; original CSV retained.'};F.validateProfile(p,item.log);if(p.confirmed&&(!p.units.time||((item.purpose==='boost'||!item.purpose||item.purpose==='unknown')&&!p.units.pressure)||!(item.purpose==='afm'?['time','rpm','hz','ect','pedal','map','cmdAf','trim','fuel']:item.purpose==='startup'||item.purpose==='validation'?['time','rpm']:['time','rpm','bp','cmd']).every(k=>mapping[k])))throw Error('Map timestamp, RPM, actual/commanded boost and choose units before confirming.');item.profile=p;applyProfileToControls(item);$('baselineConfirm').checked=$('validationConfirm').checked=false;markAfmDirty();setActive(item.id);$('profileReport').textContent='Saved mapping and unit provenance for '+item.name;await persistSessionStore();});
const logOptsV5=getLogOptions;getLogOptions=function(item=sessions.find(x=>x.id===activeSession)){const o=logOptsV5();if(item?.profile?.confirmed){const p=item.profile;o.mapping=Object.fromEntries(Object.keys(logMapping).map(k=>[k,p.mapping[k]??'']));o.timeUnit=p.units.time;o.pressure=p.units.pressure;}return o;};
for(const role of ['baseline','validation'])$(role+'Session').addEventListener('change',()=>{const item=sessions.find(x=>x.id===$(role+'Session').value);if(role==='baseline')applyProfileToControls(item,true);});
const optionsV5=afmOptions;afmOptions=function(){const opts=optionsV5();if(normalizingAfm)return{...opts,mapDelta:opts.mapDelta*F.mapFactor(sessions.find(x=>x.id===$('baselineSession').value)?.profile?.units.map),ectUnit:'F',timeUnit:'ms',trimUnit:'points',channels:{...E.AFM_DEFAULTS.channels}};return opts;};
let normalizingAfm=false;
const analysisV5=analyze;analyze=function(){const b=sessions.find(x=>x.id===$('baselineSession').value),v=sessions.find(x=>x.id===$('validationSession').value);const savedBaseline=baseline,savedValidation=validation;try{if(b?.profile?.confirmed){baseline=F.normalizeAfm(b.log,b.profile);if(validation){if(!v?.profile?.confirmed)throw Error('Review the validation log mapping before combining it with a normalized baseline.');if((!b.profile.units.map||b.profile.units.map==='native'||!v.profile.units.map||v.profile.units.map==='native')&&(b.profile.mapping.map!==v.profile.mapping.map||b.profile.units.map!==v.profile.units.map))throw Error('Choose known MAP units for both exports before combining different AFM formats.');validation=F.normalizeAfm(v.log,v.profile);}normalizingAfm=true;}else if(v?.profile?.confirmed&&baseline)throw Error('Review the baseline mapping before combining it with a normalized validation log.');analysisV5();}finally{normalizingAfm=false;baseline=savedBaseline;validation=savedValidation;}};

const persistV5=persistSessionStore;persistSessionStore=async function(){if(!workflow.storageEnabled)return;return persistV5();};
function backupWorkflow(){return{...clone(workflow),roles:Object.fromEntries(['baseline','validation','comparison'].map(r=>[r,$(r+'Session').value])),guideSteps:clone(guideSteps),panelState:Object.fromEntries([...document.querySelectorAll('[data-panel-id]')].map(p=>[p.dataset.panelId,{width:p.style.width,height:p.style.height,collapsed:p.classList.contains('panel-collapsed')}]))};}
const serializeV5=serialize;serialize=function(){const p=serializeV5();return{...p,version:6,workflow:backupWorkflow(),backupCoverage:['source tables','proposals','raw logs','mapping provenance','calibration metadata','edit history','learning observations','preferences','panel layout','evidence roles']};};
function validateBackup(p){for(const k of ['mpr','command']){E.validateTable(p.state[k].source);if(p.state[k].proposal)E.validateTable(p.state[k].proposal);if(!p.state[k].controls)throw Error('Missing boost controls');}E.analyzeAfm(p.state.afm,null,null,E.AFM_DEFAULTS);if(!Array.isArray(p.state.snapshots))throw Error('Invalid snapshot list');for(const k of ['gear','gearOriginal','gearProposal'])if(p.workbench?.[k])W.validateGear(p.workbench[k]);if(p.workbench?.afmProposal){const cells=p.workbench.afmProposal;if(cells.length!==p.state.afm.length||cells.some((x,j)=>x.hz!==p.state.afm[j].hz||!Number.isFinite(x.proposed)))throw Error('Saved airflow proposal does not match source');}const library=p.sessionLibrary;if(library){if(!Array.isArray(library.sessions)||!Array.isArray(library.learning)||!Array.isArray(library.journal))throw Error('Invalid session library');const ids=new Set();for(const x of library.sessions){if(typeof x.text!=='string'||!x.id||ids.has(x.id))throw Error('Invalid or duplicate session identity');ids.add(x.id);const log=E.parseLog(x.text,x.name);if(x.profile)F.validateProfile(x.profile,log);}if(library.preferences&&(!library.preferences.app||!library.preferences.pages||!library.preferences.panels))throw Error('Invalid appearance preferences');}for(const [id,z]of Object.entries(p.workflow.zoom??{}))if(!['sourceGrid','proposedGrid','afmPreview','gearGrid'].includes(id)||!['0.75','1','1.25','1.5','2','fit'].includes(String(z)))throw Error('Invalid saved zoom');if(p.workflow.roles&&Object.values(p.workflow.roles).some(id=>id&&!library?.sessions.some(x=>x.id===id)))throw Error('Evidence role refers to a missing log');}
const loadV5=loadProject;
loadProject=function(input){const {project:p,report}=F.migrate(input);validateBackup(p);const previous=serialize(),priorWorkflow=clone(workflow);try{clearTimeout(autoTimer);projectEpoch++;window.TuneLabProjectEpoch=projectEpoch;window.TuneLabProjectOpened=true;sessions=[];learning=[];journal=[];activeSession=null;const compatible={...p,version:5};loadV5(compatible);workflow={...workflow,...p.workflow};$('browserStorage').checked=workflow.storageEnabled;wb.history=clone(p.workbench?.history??[]);wb.redo=clone(p.workbench?.redo??[]);Object.assign(guideSteps,workflow.guideSteps??{});for(const role of ['baseline','validation','comparison']){const id=workflow.roles?.[role]??p.inputs?.[role+'Session']??'';$(role+'Session').value=id;if(role==='baseline')baseline=sessions.find(x=>x.id===id)?.log??null;if(role==='validation')validation=sessions.find(x=>x.id===id)?.log??null;}$('baselineConfirm').checked=$('validationConfirm').checked=false;applyPanelBackup(workflow.panelState??layoutPrefs.panels);refreshEvidence();applyZoom();drawAfmDeltas();showLogProfile();updateStatusStrip();$('defaultPressure').value=workflow.defaultPressure??p.inputs?.defaultPressure??state.mpr.controls.outputUnits;$('backupReport').textContent=report+' Calibration confirmations cleared; saved proposals retained.';message($('backupReport').textContent);}catch(e){workflow=priorWorkflow;loadV5({...previous,version:5});wb.history=clone(previous.workbench?.history??[]);wb.redo=clone(previous.workbench?.redo??[]);for(const role of ['baseline','validation','comparison'])$(role+'Session').value=previous.workflow.roles[role]??'';baseline=sessions.find(x=>x.id===previous.workflow.roles.baseline)?.log??null;validation=sessions.find(x=>x.id===previous.workflow.roles.validation)?.log??null;applyPanelBackup(previous.workflow.panelState);refreshEvidence();updateStatusStrip();throw Error('Backup restore failed; previous project restored: '+e.message);}};
function applyPanelBackup(panels){for(const panel of document.querySelectorAll('[data-panel-id]')){const p=panels?.[panel.dataset.panelId];panel.style.width=p?.width??'';panel.style.height=p?.height??'';panel.classList.toggle('panel-collapsed',!!p?.collapsed);panel.classList.remove('panel-maximized');const btn=panel.querySelector('[data-collapse-panel]');if(btn)btn.textContent=p?.collapsed?'Open':'Collapse';}}
try{const defaults=JSON.parse(localStorage.getItem('TuneLabDefaultsV6'));if(defaults){workflow.storageEnabled=defaults.storage!==false;$('browserStorage').checked=workflow.storageEnabled;if([...$('defaultPressure').options].some(n=>n.value===defaults.pressure)){workflow.defaultPressure=defaults.pressure;$('defaultPressure').value=defaults.pressure;for(const k of ['mpr','command'])state[k].controls.outputUnits=defaults.pressure;$('outputUnits').value=defaults.pressure;renderBoost();}}}catch{}
descriptions.settings=['Settings','Set workspace defaults, appearance, review rules and backup preferences.'];
pageHelp.settings=['Workspace settings','Choose app defaults and page appearance overrides. Source units stay explicit at their tables. Download workspace JSON to preserve tables, proposals, raw logs, mappings and preferences across browser origins.'];
drawAfmDeltas();showLogProfile();refreshEvidence();applyZoom();updateStatusStrip();

document.addEventListener('change',e=>{const id=e.target.id;if(!id.startsWith('logmap_')&&!['logTime','logPressure'].includes(id))return;const item=sessions.find(x=>x.id===activeSession);if(item?.profile?.confirmed){item.profile.confirmed=false;item.profile.evidence='Mapping changed in Log review; confirm the updated format in Log library.';showLogProfile();message('Per-log mapping needs review after this change. Raw CSV retained.','dirty');}},true);
