(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.TuneLabWorkflows=api;})(globalThis,()=>{
'use strict';
const aliases={time:['time_ms','time_s','time_seconds','time','Time (s)','Time (ms)','Time(s)','Time(ms)'],rpm:['RPM','Engine Speed','Engine Speed (rpm)'],bp:['BP','Boost','Boost (psi)','Boost (bar)','Boost (kPa)'],cmd:['BP CMD','Boost Target','Boost Target (psi)','Boost Command'],pedal:['TPedal','Accelerator Pedal','Pedal (%)'],gear:['Gear'],wg:['WGCMD','Wastegate Duty'],hz:['AFM Hz','MAF Frequency','MAF Frequency (Hz)'],ect:['ECT','ECT (C)','ECT (F)','ECT(C)','ECT(F)'],map:['MAP','MAP (kPa)','MAP (bar)','MAP(mBar)','MAP (mBar)'],trim:['Trim','Fuel Trim','Fuel Trim (%)'],fuel:['Fuel Status'],af:['AF','AFR'],cmdAf:['AFCMD','Commanded AFR']};
function inspect(log){const mapping={};for(const[k,names]of Object.entries(aliases)){const matches=log.headers.filter(h=>names.some(n=>n.toLowerCase()===h.toLowerCase()));mapping[k]=matches.length===1?matches[0]:'';}
 const text=log.metadata??'',mentions=['hondata','ktuner'].filter(p=>new RegExp('\\b'+p+'\\b','i').test(text));
 const platform=mentions.length===1?mentions[0]:'unknown',evidence=mentions.length===1?'Platform name appears in CSV metadata; verify the exporting software.':'Headers alone do not establish platform identity.';
 const time=/\bms\b|_ms$/i.test(mapping.time)?'ms':/\(s\)|_s$|_seconds$/i.test(mapping.time)?'s':null;
 const pressure=/\(psi\)/i.test(mapping.bp)&&/\(psi\)/i.test(mapping.cmd)?'psi':/\(bar\)/i.test(mapping.bp)&&/\(bar\)/i.test(mapping.cmd)?'bar':/\(kpa\)/i.test(mapping.bp)&&/\(kpa\)/i.test(mapping.cmd)?'kpa':null;
 return{version:1,platform,evidence,confirmed:false,mapping,units:{time,pressure,ect:/\(c\)/i.test(mapping.ect)?'c':/\(f\)/i.test(mapping.ect)?'f':null,trim:/\(%\)/.test(mapping.trim)?'points':null,map:/\(mbar\)/i.test(mapping.map)?'mbar':'native'},warnings:log.headers.filter(h=>h.includes('(')&&!Object.values(mapping).includes(h)).map(h=>'Unmapped channel: '+h),rejectedRows:log.rejectedRows};
}
function validateProfile(p,log){if(!p||!['unknown','hondata','ktuner'].includes(p.platform)||!p.mapping||!p.units)throw Error('Invalid log mapping profile');for(const h of Object.values(p.mapping))if(h&&!log.headers.includes(h))throw Error('Mapped channel is absent: '+h);if(!['ms','s',null].includes(p.units.time)||!['psi','bar','kpa',null].includes(p.units.pressure)||!['c','f',null].includes(p.units.ect)||!['points','fraction',null].includes(p.units.trim)||(p.units.map!==undefined&&!['native','kpa','bar','psi','mbar'].includes(p.units.map)))throw Error('Invalid log units');return p;}
function mapFactor(unit){return unit==='mbar'?0.1:unit==='bar'?100:unit==='psi'?6.894757293:1;}
function normalizeAfm(log,p){validateProfile(p,log);if(!p.confirmed||!p.units.time||!p.units.ect||!p.units.trim)throw Error('Review timestamp, coolant and trim units for each AFM evidence log.');const keys=['time','hz','ect','pedal','map','cmdAf','trim','fuel','af','rpm'],headers=['time_ms','AFM Hz','ECT','TPedal','MAP','AFCMD','Trim','Fuel Status','AF','RPM'],ids=keys.map(k=>log.headers.indexOf(p.mapping[k]));if(ids.slice(0,8).some(i=>i<0))throw Error('Map every required AFM channel before using this evidence.');const data=log.data.map(row=>Float64Array.from(ids,(ix,j)=>{let v=ix<0?NaN:row[ix];if(j===0&&p.units.time==='s')v*=1000;if(j===2&&p.units.ect==='c')v=v*9/5+32;if(j===4)v*=mapFactor(p.units.map);if(j===6&&p.units.trim==='fraction')v*=100;return v;}));return{...log,headers,data,normalizedFrom:p};}
function migrate(input){const p=JSON.parse(JSON.stringify(input));if(p.format!=='TuneLabProject'||![3,4,5,6].includes(p.version)||!p.state)throw Error('Expected a TuneLab v0.3–v0.6 project. Current work was preserved.');const from=p.version;p.version=6;p.workflow??={schema:1,storageEnabled:true,roles:{},zoom:{},guideSteps:{}};if(p.workflow.schema!==1)throw Error('Unsupported workflow backup schema');return{project:p,report:from===6?'Opened v0.6 backup.':'Migrated v0.'+from+' to v0.6; original file unchanged. Older backups may omit preferences and attachments.'};}
function deltas(cells){return cells.map(x=>({hz:x.hz,original:x.flow,proposed:x.proposed,absolute:x.proposed-x.flow,percent:x.flow>0?(x.proposed/x.flow-1)*100:null,changed:Math.abs(x.proposed-x.flow)>1e-9,protected:!!x.protect}));}
return{inspect,validateProfile,normalizeAfm,mapFactor,migrate,deltas};
});
