'use strict';
// Window-local navigation and grid layout. Project changes use a single editable
// window at a time; a revisioned handoff flushes edits before granting the lease.
function matchingWindowOrigin(origin){return location.protocol==='file:'?['null','file://'].includes(origin):origin===location.origin;}
function workspaceToken(){return Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>x.toString(16).padStart(2,'0')).join('');}
const detachedParams=new URLSearchParams(location.search),detachedPage=detachedParams.get('workspace'),windowToken=detachedParams.get('token');
const windowRole=detachedPage?'detached':'main',windowPeers=new Map();
let panelLayouts={main:{},detached:{}},windowRevision=0,windowProject=workspaceToken(),windowLease='main',windowApplying=false,windowDirty=false,windowPending=0,windowLastSeen=Date.now(),windowDisconnected=false,windowLatest=null,windowRecovering=false,windowSwitchPending=false,windowPort=null;
const ownerToken=windowRole==='main'?workspaceToken():windowToken;
const toolbar=document.createElement('div');toolbar.className='workspace-toolbar';toolbar.innerHTML='<button id="toggleNavigation" class="secondary" aria-expanded="true">Collapse menu</button><label class="workspace-select">Workspace<select id="workspaceSelect"></select></label><button id="detachWorkspace" class="secondary">Open in new window</button><button id="resetWorkspaceGrid" class="secondary">Reset workspace panels</button><button id="editThisWindow" class="secondary">Edit in this window</button><button id="windowRecovery" class="secondary" hidden>Save recovery backup</button><button id="returnMain" class="secondary" hidden>Return to main</button><output id="windowState" aria-live="polite"></output>';
document.querySelector('header').after(toolbar);
document.querySelectorAll('nav [data-tab]').forEach(n=>{for(const t of [...n.childNodes])if(t.nodeType===3)t.remove();});
$('workspaceSelect').innerHTML=[...document.querySelectorAll('nav [data-tab]')].map(n=>`<option value="${n.dataset.tab}">${esc(n.textContent.trim())}</option>`).join('');
const navigateV6=goPage;goPage=function(id){if(detachedPage&&id!==detachedPage){sendWindow({type:'navigate',page:id});return;}navigateV6(id);$('workspaceSelect').value=id;};
$('workspaceSelect').onchange=()=>goPage($('workspaceSelect').value);
document.querySelector('nav').addEventListener('click',()=>{$('workspaceSelect').value=currentPage();});
$('toggleNavigation').onclick=()=>{const collapsed=document.body.classList.toggle('compact-navigation');$('toggleNavigation').textContent=collapsed?'Show menu':'Collapse menu';$('toggleNavigation').setAttribute('aria-expanded',String(!collapsed));};
// Only analysis/preview cards move. Coupled import/control forms stay anchored.
const movable={boost:['rampChart','boostChart','sourceGrid','proposedGrid','boostEvidenceSummary'],afm:['afmPreview','afmChart','trimChart','afmGrid','afmReasons','afmDeltaChart','afmEvidenceSummary'],logs:['logChart','eventsGrid','logQuality','errorHistogram','errorScatter'],gears:['gearChart','alignmentGrid','gearsEvidenceSummary'],project:['snapshots'],library:['learningList'],history:['historyList'],compare:[]};
const gridDefaults=new Map();
for(const [page,ids]of Object.entries(movable)){
 const cards=[...new Set(ids.map(id=>$(id)?.closest('.panel')).filter(Boolean))];if(!cards.length)continue;
 const parents=new Map();for(const card of cards){const parent=card.parentElement;if(!parents.has(parent))parents.set(parent,[]);parents.get(parent).push(card);}
 for(const [parent,list]of parents){const grid=document.createElement('div');grid.className='panel-grid';grid.dataset.gridPage=page;list[0].before(grid);for(const card of list){const key=ids.find(id=>card.contains($(id)));card.dataset.gridId=page+'-'+key;card.dataset.span='2';grid.append(card);installGridCard(card,page);}
 gridDefaults.set(grid,[...grid.children].map(n=>n.dataset.gridId));}
}
function installGridCard(card,page){const tools=document.createElement('div');tools.className='grid-tools';tools.innerHTML='<button class="secondary panel-handle" aria-label="Drag panel or use Alt plus arrow keys">Move panel</button><button class="secondary" data-grid-up aria-label="Move panel earlier">↑</button><button class="secondary" data-grid-down aria-label="Move panel later">↓</button><button class="secondary" data-grid-span>Half width</button><button class="secondary" data-grid-left disabled aria-label="Snap half-width panel left">Snap left</button><button class="secondary" data-grid-right disabled aria-label="Snap half-width panel right">Snap right</button>';card.prepend(tools);const handle=tools.querySelector('.panel-handle');handle.onkeydown=e=>{if(e.altKey&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();if(card.dataset.span==='1'&&['ArrowLeft','ArrowRight'].includes(e.key))snapCard(card,e.key==='ArrowLeft'?'left':'right');else moveCard(card,['ArrowUp','ArrowLeft'].includes(e.key)?-1:1);}};tools.querySelector('[data-grid-up]').onclick=()=>moveCard(card,-1);tools.querySelector('[data-grid-down]').onclick=()=>moveCard(card,1);tools.querySelector('[data-grid-span]').onclick=()=>{card.dataset.span=card.dataset.span==='1'?'2':'1';card.style.width='';card.dataset.side='auto';updateSpan(card);saveGrid(page);};tools.querySelector('[data-grid-left]').onclick=()=>snapCard(card,'left');tools.querySelector('[data-grid-right]').onclick=()=>snapCard(card,'right');handle.onpointerdown=e=>startPanelDrag(e,card);}
function updateSpan(card){card.querySelector('[data-grid-span]').textContent=card.dataset.span==='1'?'Full width':'Half width';for(const side of ['left','right']){const button=card.querySelector('[data-grid-'+side+']');button.disabled=card.dataset.span!=='1';button.setAttribute('aria-pressed',String(card.dataset.side===side));}}
function snapCard(card,side){if(card.dataset.span!=='1')return;card.dataset.side=side;card.style.width='';updateSpan(card);saveGrid(card.closest('[data-grid-page]').dataset.gridPage);}
function moveCard(card,direction){const sibling=direction<0?card.previousElementSibling:card.nextElementSibling;if(!sibling)return;if(direction<0)sibling.before(card);else sibling.after(card);saveGrid(card.closest('[data-grid-page]').dataset.gridPage);card.querySelector('.panel-handle').focus();}
function startPanelDrag(e,card){
 if(e.button!==0||card.classList.contains('panel-maximized'))return;e.preventDefault();const handle=e.currentTarget,grid=card.parentElement;handle.setPointerCapture(e.pointerId);card.classList.add('dragging');let target=null,after=false,side=null,marker=null;
 const clear=()=>{grid.querySelectorAll('.drop-target').forEach(n=>n.classList.remove('drop-target'));marker?.remove();marker=null;};
 const move=ev=>{clear();target=null;side=null;const bounds=grid.getBoundingClientRect(),twoColumns=getComputedStyle(grid).gridTemplateColumns.split(' ').length>1;if(ev.clientX<bounds.left||ev.clientX>bounds.right||ev.clientY<bounds.top||ev.clientY>bounds.bottom)return;
  if(card.dataset.span==='1'&&twoColumns){side=ev.clientX<bounds.left+bounds.width/2?'left':'right';const cards=[...grid.children];target=cards.find(n=>{const r=n.getBoundingClientRect();return n!==card&&ev.clientX>=r.left&&ev.clientX<=r.right&&ev.clientY>=r.top&&ev.clientY<=r.bottom;})??cards.find(n=>{const r=n.getBoundingClientRect();return ev.clientY>=r.top&&ev.clientY<=r.bottom;})??cards.reduce((best,n)=>Math.abs(n.getBoundingClientRect().top-ev.clientY)<Math.abs(best.getBoundingClientRect().top-ev.clientY)?n:best,card);const r=target.getBoundingClientRect();after=target.dataset.span==='1'&&target.dataset.side!==side?side==='right':ev.clientY>r.top+r.height/2;
   marker=document.createElement('div');marker.className='grid-drop-slot';marker.textContent='Snap '+side;Object.assign(marker.style,{position:'fixed',left:(bounds.left+(side==='right'?bounds.width/2:0))+'px',top:r.top+'px',width:(bounds.width/2-9)+'px',height:Math.min(r.height,200)+'px'});document.body.append(marker);
  }else{target=[...grid.children].find(n=>{if(n===card)return false;const r=n.getBoundingClientRect();return ev.clientX>=r.left&&ev.clientX<=r.right&&ev.clientY>=r.top&&ev.clientY<=r.bottom;});if(target){const r=target.getBoundingClientRect();after=ev.clientY>r.top+r.height/2;target.classList.add('drop-target');target.setAttribute('data-drop-position',after?'after':'before');}}
 };
 const finish=ev=>{if(ev.type!=='pointercancel'&&target){if(target!==card){if(after)target.after(card);else target.before(card);}if(side)card.dataset.side=side;updateSpan(card);saveGrid(grid.dataset.gridPage);}clear();card.classList.remove('dragging');handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',finish);handle.removeEventListener('pointercancel',finish);};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',finish);handle.addEventListener('pointercancel',finish);
}
function saveGrid(page){const cards=[...$(page).querySelectorAll('.panel-grid>.panel')];panelLayouts[windowRole][page]={order:cards.map(n=>n.dataset.gridId),cards:Object.fromEntries(cards.map(n=>[n.dataset.gridId,{span:n.dataset.span,side:n.dataset.side??'auto',width:n.style.width,height:n.style.height,collapsed:n.classList.contains('panel-collapsed')}]))};if(!windowApplying){try{localStorage.setItem('TuneLabGridV7',JSON.stringify(panelLayouts));}catch{}if(windowRole==='detached')sendWindow({type:'layout',projectId:windowProject,page,layout:panelLayouts.detached[page]});else broadcastWindow({type:'layouts',layouts:panelLayouts});}}
function restoreGrid(page=null){for(const grid of gridDefaults.keys()){if(page&&grid.dataset.gridPage!==page)continue;const prefs=panelLayouts[windowRole][grid.dataset.gridPage];for(const id of prefs?.order??gridDefaults.get(grid)){const card=[...grid.children].find(n=>n.dataset.gridId===id);if(card)grid.append(card);}for(const card of grid.children){const p=prefs?.cards?.[card.dataset.gridId];card.dataset.span=p?.span==='1'?'1':'2';card.dataset.side=p?.side??'auto';card.style.width=p?.width??'';card.style.height=p?.height??'';card.classList.toggle('panel-collapsed',!!p?.collapsed);updateSpan(card);const collapse=card.querySelector('[data-collapse-panel]');if(collapse)collapse.textContent=card.classList.contains('panel-collapsed')?'Open':'Collapse';}}}
$('resetWorkspaceGrid').title='Reset order, left/right placement, size and collapsed/expanded state for this workspace in this window. Table zoom and other workspaces stay as chosen.';
$('resetWorkspaceGrid').onclick=()=>{const page=currentPage();delete panelLayouts[windowRole][page];for(const panel of $(page).querySelectorAll('.panel')){panel.style.width=panel.style.height='';panel.classList.remove('panel-collapsed','panel-maximized');const collapse=panel.querySelector('[data-collapse-panel]'),expand=panel.querySelector('[data-max-panel]');if(collapse)collapse.textContent='Collapse';if(expand)expand.textContent='Expand';if(panel.dataset.panelId){delete layoutPrefs.panels[panel.dataset.panelId];if(workflow.panelState)delete workflow.panelState[panel.dataset.panelId];}}for(const table of $(page).querySelectorAll('.table-scroll'))table.style.width=table.style.height='';restoreGrid(page);saveGrid(page);try{localStorage.setItem('TuneLabLayoutV5',JSON.stringify(layoutPrefs));}catch{}message('Workspace panels reset: order, placement, sizes and open state restored in this window.');};
document.addEventListener('pointerup',()=>{if(!windowApplying)saveGrid(currentPage());});
function validateGrid(input){if(!input)return{main:{},detached:{}};for(const role of ['main','detached']){if(!input[role]||typeof input[role]!=='object'||Array.isArray(input[role]))throw Error('Invalid window panel layout');for(const [page,p]of Object.entries(input[role])){if(!$(page)?.classList.contains('page')||!Array.isArray(p.order)||new Set(p.order).size!==p.order.length||!p.order.every(x=>typeof x==='string')||!p.cards||typeof p.cards!=='object')throw Error('Invalid panel arrangement');for(const card of Object.values(p.cards)){if((card.side!==undefined&&!['auto','left','right'].includes(card.side))||!['1','2'].includes(card.span)||!['width','height'].every(k=>typeof card[k]==='string'&&/^(|\d+(\.\d+)?px)$/.test(card[k])))throw Error('Invalid panel size');}}}return clone(input);}
const serializeV6Workspace=serialize;serialize=function(){return{...serializeV6Workspace(),version:10,panelLayouts:clone(panelLayouts)};};
const loadV6Workspace=loadProject;loadProject=function(input){const openingVersion=input.version,layouts=validateGrid(input.panelLayouts);if([7,8,9,10].includes(input.version))input={...input,version:6};loadV6Workspace(input);if([7,8,9,10].includes(openingVersion)&&!windowApplying){$('backupReport').textContent='Opened v0.'+openingVersion+' backup. Calibration confirmations cleared; proposals and separate window layouts retained.';message($('backupReport').textContent);}if(!input.panelLayouts){for(const role of ['main','detached'])for(const page of new Set([...gridDefaults.keys()].map(g=>g.dataset.gridPage))){const cards=[...$(page).querySelectorAll('.panel-grid>.panel')];layouts[role][page]={order:cards.map(n=>n.dataset.gridId),cards:Object.fromEntries(cards.map(n=>[n.dataset.gridId,{span:'2',width:n.style.width,height:n.style.height,collapsed:n.classList.contains('panel-collapsed')}]))};}}panelLayouts=layouts;restoreGrid();if(!windowApplying){if(windowRole==='main'){windowProject=workspaceToken();windowRevision=0;}else windowSwitchPending=true;windowDirty=true;flushWindow();}};
// Snapshot backups are supplemented with live AFM evidence and confirmation flags
// for synchronization. Opening a file still clears confirmations as in v0.6.
function captureWindow(){return{project:serialize(),live:{kind,afmResult:afmResult?(typeof structuredClone==='function'?structuredClone(afmResult):clone(afmResult)):null,statusText:$('status').textContent,statusClass:$('status').className,afmDirty,baselineConfirm:$('baselineConfirm').checked,validationConfirm:$('validationConfirm').checked}};}
function applyWindow(snapshot){const page=currentPage(),localKind=kind;windowApplying=true;try{loadProject(snapshot.project);afmResult=snapshot.live.afmResult;afmDirty=snapshot.live.afmDirty;$('baselineConfirm').checked=snapshot.live.baselineConfirm;$('validationConfirm').checked=snapshot.live.validationConfirm;switchKind(localKind,true);renderAfm();drawAfmDeltas();navigateV6(detachedPage??page);$('workspaceSelect').value=detachedPage??page;windowLatest=snapshot;$('status').textContent=snapshot.live.statusText??'';$('status').className=snapshot.live.statusClass??'status';}finally{windowApplying=false;}}
function sendWindow(msg){const data={...msg,tuneLabWindow:ownerToken};if(windowPort)windowPort.postMessage(data);else if(msg.type==='hello'&&opener&&!opener.closed)opener.postMessage(data,'*');}
function broadcastWindow(msg){for(const [token,peer]of windowPeers)if(!peer.ref.closed)peer.port?.postMessage({...msg,tuneLabWindow:token});}
function editingHere(){return!windowDisconnected&&windowLease===(windowRole==='main'?'main':windowToken);}
function windowControls(note){const editable=editingHere()&&!windowRecovering;document.body.classList.toggle('window-readonly',!editable);document.querySelectorAll('.page,.sessionbar').forEach(n=>n.inert=!editable);$('demo').inert=!editable;$('openProject').disabled=!editable;$('saveProject').disabled=!!windowPending;$('editThisWindow').disabled=editable||windowDisconnected;$('windowRecovery').hidden=!windowDisconnected;$('windowState').textContent=note??(windowDisconnected?'Main window disconnected. Edits paused; save a recovery backup.':`Revision ${windowRevision} · ${editable?'Editing here':'Viewing · choose Edit in this window to make changes'}`);}
function flushWindow(){if(!windowDirty||windowApplying||!editingHere()||windowPending||window.TuneLabActions)return;windowDirty=false;const snapshot=captureWindow();windowLatest=snapshot;if(windowRole==='main'){windowRevision++;broadcastWindow({type:'state',projectId:windowProject,revision:windowRevision,lease:windowLease,snapshot});}else{windowPending=Date.now();sendWindow({type:'commit',projectId:windowProject,revision:windowRevision,newProject:windowSwitchPending,snapshot});}windowControls();}
function dirtyWindow(){if(!windowApplying&&editingHere()){windowDirty=true;setTimeout(flushWindow,450);}}
for(const type of ['input','change','click','pointerup','keydown'])document.addEventListener(type,e=>{if(e.target.closest('.workspace-toolbar,.grid-tools,nav'))return;dirtyWindow();});
window.TuneLabStateChanged=dirtyWindow;
document.addEventListener('keydown',e=>{if((!editingHere()||windowRecovering)&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.stopImmediatePropagation();windowControls('Choose Edit in this window before undo or redo.');}},true);
const persistenceV6Workspace=persistSessionStore;persistSessionStore=async function(){if(windowApplying)return;dirtyWindow();if(windowRole==='detached')return;return persistenceV6Workspace();};
let handoffTarget=null;
function grantWindow(target){windowLatest=captureWindow();windowLease=target;handoffTarget=null;windowControls();broadcastWindow({type:'lease',lease:target,projectId:windowProject,revision:windowRevision,snapshot:windowLatest??captureWindow()});}
function requestLease(target){if(window.TuneLabActions){setTimeout(()=>requestLease(target),100);return;}if(windowLease===target)return;if(windowLease==='main'){clearTimeout(autoTimer);flushWindow();grantWindow(target);}else{handoffTarget=target;windowPeers.get(windowLease)?.port?.postMessage({tuneLabWindow:windowLease,type:'release'});}}
$('editThisWindow').onclick=()=>windowRole==='main'?requestLease('main'):sendWindow({type:'requestLease'});
$('windowRecovery').onclick=()=>download('TuneLab-v0.9-recovery.json',JSON.stringify(serialize(),null,2),'application/json');
$('returnMain').onclick=()=>{if(opener&&!opener.closed)opener.focus();else windowControls('Main window unavailable. Save recovery backup, then open it in a new main window.');};
$('detachWorkspace').onclick=()=>{flushWindow();const token=workspaceToken(),url=new URL(location.href);url.search='';url.searchParams.set('workspace',currentPage());url.searchParams.set('token',token);const ref=window.open(url.href,'_blank','popup=yes,width=1200,height=850,resizable=yes,scrollbars=yes');if(!ref){windowControls('Popup blocked. Allow popups for TuneLab, then try again.');return;}windowPeers.set(token,{ref,page:currentPage()});};
function handleWindowMessage(e){
 const m=e.data;if(!m)return;
 if(windowRole==='main'){
  const entry=[...windowPeers].find(([,p])=>p.ref===e.source);if(!entry)return;const [token,peer]=entry;if(m.tuneLabWindow!==token)return;
  if(m.type==='hello'&&!e.viaPort){if(!matchingWindowOrigin(e.origin))return;peer.port?.close();const channel=new MessageChannel();peer.port=channel.port1;peer.port.onmessage=event=>handleWindowMessage({source:peer.ref,data:event.data,viaPort:true});peer.ref.postMessage({tuneLabWindow:token,type:'channel',token},'*',[channel.port2]);return;}
  if(!e.viaPort)return;
  if(m.type==='ready'){peer.port.postMessage({tuneLabWindow:token,type:'welcome',token,projectId:windowProject,revision:windowRevision,lease:windowLease,snapshot:captureWindow()});return;}
  if(m.type==='requestLease'){requestLease(token);return;}
  if(m.type==='navigate'){goPage(m.page);window.focus();return;}
  if(m.type==='ping'){peer.port.postMessage({tuneLabWindow:token,type:'pong'});return;}
  if(m.type==='layout'){if(m.projectId!==windowProject)return;try{const next=clone(panelLayouts);next.detached[m.page]=m.layout;panelLayouts=validateGrid(next);broadcastWindow({type:'layouts',layouts:panelLayouts});}catch(error){windowControls(error.message);}return;}
  if(m.type==='commit'){
   if(token!==windowLease||m.projectId!==windowProject||m.revision!==windowRevision){peer.port.postMessage({tuneLabWindow:token,type:'conflict',projectId:windowProject,revision:windowRevision,lease:windowLease,snapshot:captureWindow()});return;}
   try{const layouts=clone(panelLayouts);applyWindow(m.snapshot);if(!m.newProject)panelLayouts=layouts;restoreGrid();windowLatest=captureWindow();if(m.newProject){windowProject=workspaceToken();windowRevision=0;}windowRevision++;broadcastWindow({type:'state',projectId:windowProject,revision:windowRevision,lease:windowLease,snapshot:windowLatest});windowControls();}catch(error){peer.port.postMessage({tuneLabWindow:token,type:'error',message:error.message});}return;
  }
  if(m.type==='released'&&token===windowLease){grantWindow(handoffTarget??'main');return;}
 }else{
  if(e.source!==opener||m.tuneLabWindow!==ownerToken||windowDisconnected)return;windowLastSeen=Date.now();
  if(m.type==='channel'&&!e.viaPort){if(!matchingWindowOrigin(e.origin)||!e.ports?.[0])return;windowPort=e.ports[0];windowPort.onmessage=event=>handleWindowMessage({source:opener,data:event.data,viaPort:true});sendWindow({type:'ready'});return;}
  if(!e.viaPort)return;
  if(m.type==='pong')return;
  if(m.type==='release'){releaseWindow();return;}
  if(['welcome','state','lease','conflict'].includes(m.type)){
   if(m.type==='welcome'&&m.token!==windowToken)return;
   if(m.type==='state'&&m.projectId===windowProject&&m.revision<windowRevision)return;
   const ownAcknowledgment=m.type==='state'&&windowPending&&m.lease===windowToken;windowPending=0;windowSwitchPending=false;windowProject=m.projectId;windowRevision=m.revision;windowLease=m.lease;try{if(ownAcknowledgment){windowLatest=m.snapshot;panelLayouts=clone(m.snapshot.project.panelLayouts);}else applyWindow(m.snapshot);}catch(error){windowDisconnected=true;windowControls('Synchronization failed: '+error.message);return;}
   if(windowRecovering){windowRecovering=false;if(windowDirty){releaseWindow();windowControls();return;}windowLease='main';sendWindow({type:'released'});}
   windowControls(m.type==='conflict'?'Stale edit rejected. Current project restored; review before editing.':undefined);return;
  }
  if(m.type==='layouts'){panelLayouts=validateGrid(m.layouts);if(!editingHere())restoreGrid();return;}
  if(m.type==='error'){windowDisconnected=true;windowControls('Sync failed: '+m.message);}
 }
}
window.addEventListener('message',handleWindowMessage);
function releaseWindow(){if(window.TuneLabActions){setTimeout(releaseWindow,100);return;}clearTimeout(autoTimer);flushWindow();if(windowPending){windowRecovering=true;windowControls('Finishing edits before handoff…');return;}windowLease='main';windowControls();sendWindow({type:'released'});}
if(detachedPage){document.body.classList.add('detached-workspace');$('toggleNavigation').hidden=$('detachWorkspace').hidden=true;$('returnMain').hidden=false;$('workspaceSelect').parentElement.hidden=true;windowLease='main';if($(detachedPage)?.classList.contains('page'))navigateV6(detachedPage);else windowDisconnected=true;sendWindow({type:'hello'});}else windowLatest=captureWindow();
try{if(windowRole==='main'){const saved=localStorage.getItem('TuneLabGridV7');if(saved){panelLayouts=validateGrid(JSON.parse(saved));restoreGrid();}}}catch{}
windowControls();
setInterval(()=>{if(windowRole==='detached'){if(!opener||opener.closed||Date.now()-windowLastSeen>6500||(windowPending&&Date.now()-windowPending>6500)){windowDisconnected=true;windowControls();}else sendWindow({type:'ping'});}else{for(const [token,peer]of windowPeers)if(peer.ref.closed){windowPeers.delete(token);if(windowLease===token){windowLease='main';windowControls('Editing returned to main. Last synchronized revision retained. Use a recovery backup for any unsent edits.');broadcastWindow({type:'lease',lease:'main',projectId:windowProject,revision:windowRevision,snapshot:windowLatest});}}}flushWindow();},1000);
window.addEventListener('beforeunload',e=>{flushWindow();if(windowRole==='detached'&&(windowPending||windowDirty||window.TuneLabActions)){e.preventDefault();e.returnValue='';}});
