(function(root,factory){const api=factory(typeof module==='object'?require('./engine.js'):root.TuneLabEngine);if(typeof module==='object'&&module.exports)module.exports=api;else root.TuneLabWorkbench=api;})(globalThis,E=>{
'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
const units=['bar','kpa','psiAbs','psiGauge','ktuner','ratio'];
function pressure(v,from,to,pa=.98,offset=0){if(!units.includes(from)||!units.includes(to)||!Number.isFinite(v)||!Number.isFinite(pa)||pa<=0||!Number.isFinite(offset))throw Error('Check pressure value, units and atmospheric reference');const b=from==='bar'?v:from==='kpa'?v/100:from==='psiAbs'?v/E.BAR:from==='psiGauge'?v/E.BAR+pa:from==='ktuner'?(v-offset+E.STD)/E.BAR:v*pa;return to==='bar'?b:to==='kpa'?b*100:to==='psiAbs'?b*E.BAR:to==='psiGauge'?(b-pa)*E.BAR:to==='ktuner'?b*E.BAR-E.STD+offset:b/pa;}
function flow(v,from,to){const factors={gs:1,kgh:3.6,lbmin:.132277357};if(!Number.isFinite(v)||!factors[from]||!factors[to])throw Error('Invalid airflow units');return v/factors[from]*factors[to];}
function edit(values,rows,cols,op,amount,opts={}){if(!Array.isArray(values)||!values.length||!values[0].length||values.some(r=>r.length!==values[0].length||r.some(v=>!Number.isFinite(v))))throw Error('Invalid table body');if(!rows.length||!cols.length)throw Error('Select cells first');if(rows.some(r=>!Number.isInteger(r)||r<0||r>=values.length)||cols.some(c=>!Number.isInteger(c)||c<0||c>=values[0].length))throw Error('Selection outside table');if(!Number.isFinite(amount)||!['set','add','percent','smooth','rpm','axis','blend'].includes(op))throw Error('Check editing operation and amount');const out=clone(values),rr=[...new Set(rows)].sort((a,b)=>a-b),cc=[...new Set(cols)].sort((a,b)=>a-b),xa=opts.rowAxis??values.map((_,i)=>i),ya=opts.colAxis??values[0].map((_,i)=>i);if((op==='smooth')&&(amount<0||amount>100))throw Error('Smoothing strength must be 0–100%');for(const r of rr)for(const c of cc){if(opts.protect?.[r]?.[c])continue;let v=values[r][c];if(op==='blend'){const dr=rr.length>1?Math.min(r-rr[0],rr.at(-1)-r)/Math.max(1,(rr.at(-1)-rr[0])/2):1,dc=cc.length>1?Math.min(c-cc[0],cc.at(-1)-c)/Math.max(1,(cc.at(-1)-cc[0])/2):1,t=Math.min(dr,dc);v+=amount*t*t*(3-2*t);}if(op==='set')v=amount;if(op==='add')v+=amount;if(op==='percent')v*=1+amount/100;if(op==='rpm'||op==='axis'){const a=op==='rpm'?rr:cc,index=op==='rpm'?r:c,axis=op==='rpm'?xa:ya,lo=a[0],hi=a.at(-1);if(index===lo||index===hi)continue;const den=axis[hi]-axis[lo];if(!(den>0))throw Error('Interpolation endpoints need distinct ordered indices');const t=(axis[index]-axis[lo])/den;v=op==='rpm'?values[lo][c]*(1-t)+values[hi][c]*t:values[r][lo]*(1-t)+values[r][hi]*t;}
if(op==='smooth'){const n=[];for(const [dr,dc]of [[-1,0],[1,0],[0,-1],[0,1]])if(rr.includes(r+dr)&&cc.includes(c+dc))n.push(values[r+dr][c+dc]);if(n.length<2||opts.keepBoundary&&((rr.length>1&&(r===rr[0]||r===rr.at(-1)))||(cc.length>1&&(c===cc[0]||c===cc.at(-1)))))continue;v+=(n.reduce((a,b)=>a+b,0)/n.length-v)*amount/100;}if(!Number.isFinite(v))throw Error('Editing produced a nonfinite value');out[r][c]=v;}return out;}
function summarize(base,proposed,thresholds={}){if(base.length!==proposed.length||base.some((r,j)=>r.length!==proposed[j].length))throw Error('Comparison dimensions differ');const t={absolute:2,percent:10,max:30,gradient:5,...thresholds};if(Object.values(t).some(v=>!Number.isFinite(v)||v<0))throw Error('Warning thresholds must be finite and nonnegative');let changed=0,maxAbs=0,maxPercent=0,noPercent=0,alerts=[];base.forEach((row,r)=>row.forEach((b,c)=>{const p=proposed[r][c];if(!Number.isFinite(b)||!Number.isFinite(p))throw Error('Comparison contains invalid values');const d=p-b;if(Math.abs(d)<1e-9)return;changed++;maxAbs=Math.max(maxAbs,Math.abs(d));const pct=b>1e-6?Math.abs(d/b*100):null;if(pct===null)noPercent++;else maxPercent=Math.max(maxPercent,pct);if(Math.abs(d)>t.absolute)alerts.push({r,c,reason:'Absolute change',value:d});if(pct!==null&&pct>t.percent)alerts.push({r,c,reason:'Percentage change',value:pct});if(p>t.max)alerts.push({r,c,reason:'Result exceeds configured maximum',value:p});for(const[nr,nc]of [[r-1,c],[r,c-1],[r+1,c],[r,c+1]])if(nr>=0&&nc>=0&&nr<base.length&&nc<row.length){const gap=Math.abs(p-proposed[nr][nc]),old=Math.abs(b-base[nr][nc]);if(gap>t.gradient&&gap>old+1e-9){alerts.push({r,c,reason:'Increased neighboring-cell step',value:gap});break;}}}));return{changed,maxAbs,maxPercent,noPercent,alerts};}
function parseGear(text,format,units,gear=1){if(!text.trim())throw Error('Paste a table first');const lines=text.trim().split(/\r?\n/).filter(x=>x.trim()).map(x=>x.includes('\t')?x.split('\t'):x.split(','));if(lines.length<2)throw Error('Paste a header row and body');if(format==='hondata'){const rpm=lines[0].slice(1).map(E.numeric),gears=lines.slice(1).map(r=>({gear:E.numeric(r[0]),rpm:[...rpm],axis:null,values:r.slice(1).map(x=>[E.numeric(x)])}));const out={format,units,gears};validateGear(out);return out;}if(format!=='ktuner')throw Error('Unknown gear format');const out={format,units,gears:[{gear,rpm:lines.slice(1).map(r=>E.numeric(r[0])),axis:lines[0].slice(1).map(E.numeric),values:lines.slice(1).map(r=>r.slice(1).map(E.numeric))}]};validateGear(out);return out;}
function validateGear(g){if(!g||!['hondata','ktuner'].includes(g.format)||!units.includes(g.units)||!Array.isArray(g.gears)||!g.gears.length||new Set(g.gears.map(x=>x.gear)).size!==g.gears.length)throw Error('Invalid gear table');for(const x of g.gears){if(!Number.isInteger(x.gear)||x.gear<1||x.gear>10)throw Error('Gear must be 1–10');E.validateTable({rpm:x.rpm,axis:x.axis??[1],values:x.values});if(x.axis?.some(v=>v<=0))throw Error('Atmospheric indices must be positive bar');}if(g.format==='hondata'&&g.gears.some(x=>x.axis||JSON.stringify(x.rpm)!==JSON.stringify(g.gears[0].rpm)))throw Error('Hondata gears need shared RPM indices and no atmospheric axis');if(g.format==='ktuner'&&g.gears.some(x=>!x.axis))throw Error('KTuner gears need atmospheric indices');return g;}
function gearCurve(g,gear,pa,output='psiGauge',offset=0){validateGear(g);const x=g.gears.find(x=>x.gear===gear);if(!x)throw Error('Selected gear has not been imported');let br=x.axis?E.bracket(x.axis,pa):[0,0,0];return x.rpm.map((rpm,r)=>{const[lo,hi,w]=br,a=pressure(x.values[r][lo],g.units,'bar',x.axis?.[lo]??pa,offset),b=pressure(x.values[r][hi],g.units,'bar',x.axis?.[hi]??pa,offset);return[rpm,pressure(a*(1-w)+b*w,'bar',output,pa,offset)];});}
function translateGear(g,format,pa,axis,strategy,output,offset=0){validateGear(g);if(!['hondata','ktuner'].includes(format)||!['gauge','absolute'].includes(strategy))throw Error('Invalid translation strategy');const gears=g.gears.map(x=>{const curve=gearCurve(g,x.gear,pa,'bar',offset);if(format==='hondata')return{gear:x.gear,rpm:[...x.rpm],axis:null,values:curve.map(([,v])=>[pressure(v,'bar',output,pa,offset)])};if(!Array.isArray(axis)||axis.length<1||axis.some((v,j)=>!Number.isFinite(v)||v<=0||j&&v<=axis[j-1]))throw Error('Atmospheric indices must increase');return{gear:x.gear,rpm:[...x.rpm],axis:[...axis],values:curve.map(([,b])=>axis.map(a=>pressure(strategy==='gauge'?b-pa+a:b,'bar',output,a,offset)))};});return validateGear({format,units:output,gears,referencePa:pa,strategy,derived:true});}
function sampleCurve(curve,rpm){const[lo,hi,w]=E.bracket(curve.map(x=>x[0]),rpm);return curve[lo][1]*(1-w)+curve[hi][1]*w;}
return{pressure,flow,edit,summarize,parseGear,validateGear,gearCurve,translateGear,sampleCurve,units};
});
